import {MarcaSicom} from '@/features/apariencia/MarcaSicom';
import {useApariencia} from '@/features/apariencia/AparienciaProvider';
import {fondo,variables} from '@/features/apariencia/tema';
import {useState} from 'react';import {useNavigate,Link} from 'react-router-dom';import {useQuery,useQueryClient} from '@tanstack/react-query';import {apiClient} from '@/api/client';import {useAuthStore} from '@/stores/authStore';import {getApiErrorMessage} from '@/api/errors';import type {LoginResponse} from '@/types/auth';
type Perfil={id:number;nombre:string;apellido:string;administrador:boolean};
const almacen='sicom-sesion-empresa';
const leer=()=>{try{const v=JSON.parse(localStorage.getItem(almacen)||sessionStorage.getItem(almacen)||'null');return v&&new Date(v.vence).getTime()>Date.now()?v:null;}catch{return null;}};
export default function AccesoEmpresa(){
 const apariencia=useApariencia();
 const [sesion,setSesion]=useState<{sesionEmpresa:string;empresa:string;vence:string}|null>(leer),[perfil,setPerfil]=useState<Perfil|null>(null),[cuenta,setCuenta]=useState(''),[password,setPassword]=useState(''),[codigo,setCodigo]=useState(''),[recordar,setRecordar]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);const navigate=useNavigate(),qc=useQueryClient();
 const perfiles=useQuery({queryKey:['perfiles-empresa',sesion?.sesionEmpresa],queryFn:async()=>(await apiClient.get<{empresa:string;perfiles:Perfil[]}>('/auth/empresa/perfiles',{headers:{'X-Sicom-Empresa':sesion?.sesionEmpresa}})).data,enabled:!!sesion,retry:false});
 async function salirEmpresa(){try{if(sesion)await apiClient.post('/auth/empresa/salir',{}, {headers:{'X-Sicom-Empresa':sesion.sesionEmpresa}});}finally{localStorage.removeItem(almacen);sessionStorage.removeItem(almacen);useAuthStore.getState().logout();qc.clear();setSesion(null);setPerfil(null);setPassword('');setCodigo('');setError('');}}
 async function entrar(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{if(!sesion){const r=(await apiClient.post('/auth/empresa/iniciar',{cuenta,password,codigoDobleFactor:codigo||null,recordar})).data;localStorage.removeItem(almacen);sessionStorage.removeItem(almacen);(recordar?localStorage:sessionStorage).setItem(almacen,JSON.stringify(r));qc.clear();setSesion(r);}else if(perfil){const r=(await apiClient.post<LoginResponse>('/auth/empresa/perfil',{usuarioId:perfil.id,password,codigoDobleFactor:codigo||null},{headers:{'X-Sicom-Empresa':sesion.sesionEmpresa}})).data;qc.clear();useAuthStore.getState().setSession(r);const cfg=(await apiClient.get<{facturador:boolean}>('/sicom/me')).data;navigate(cfg.facturador?'/app/facturacion':'/',{replace:true});}}catch(e){setError(getApiErrorMessage(e,'No fue posible ingresar'));}finally{setBusy(false);setPassword('');setCodigo('');}}
 const input='mt-2 w-full p-3 rounded bg-slate-800';
 return <main className={`min-h-screen bg-slate-950 text-white flex items-center justify-center p-6 ${apariencia.activo?'sicom-login-personalizado':''}`} style={apariencia.activo?{...variables(apariencia),...fondo(apariencia.login)}:undefined}><section className="w-full max-w-3xl text-center"><h1 className="text-3xl font-semibold"><MarcaSicom/></h1>{apariencia.activo&&<p className="mt-2 text-slate-300">{apariencia.subtitulo}</p>}<p className="mt-3 text-slate-300">{sesion?sesion.empresa:'Ingresa a tu empresa'}</p>
 {sesion&&!perfil&&<><h2 className="mt-6 text-xl">¿Quién va a ingresar?</h2>{perfiles.isLoading&&<p>Cargando perfiles…</p>}{perfiles.isError&&<p className="mt-6 text-red-300">{getApiErrorMessage(perfiles.error,'No se pudo consultar la sesión. Vuelve a ingresar a la empresa.')}</p>}<div className="mt-10 grid grid-cols-2 sm:grid-cols-4 gap-5">{perfiles.data?.perfiles.map(p=><button key={p.id} onClick={()=>{setPerfil(p);setError('');setPassword('');setCodigo('');}} className="rounded-2xl p-5 bg-slate-800 hover:bg-slate-700 focus:ring-2 focus:ring-green-400"><span className="mx-auto flex h-20 w-20 rounded-2xl bg-emerald-600 items-center justify-center text-3xl">{p.nombre.slice(0,1).toUpperCase()}</span><span className="block mt-4">{p.nombre} {p.apellido}</span><small>{p.administrador?'Administrador':'Empleado'}</small></button>)}</div>{perfiles.data?.perfiles.length===0&&<p>No hay perfiles activos disponibles.</p>}</>}
 {(!sesion||perfil)&&<form onSubmit={entrar} style={apariencia.activo?{maxWidth:apariencia.loginCajaAncho,transform:`translate(${apariencia.loginCajaX}px,${apariencia.loginCajaY}px)`}:undefined} className="mt-8 mx-auto max-w-sm space-y-4">{perfil&&<h2 className="text-xl">{perfil.nombre} {perfil.apellido}</h2>}{!sesion&&<label className="block text-left">Cuenta de empresa<input required autoComplete="username" value={cuenta} onChange={e=>setCuenta(e.target.value)} className={input}/></label>}<label className="block text-left">{sesion?'Contraseña del perfil':'Contraseña de empresa'}<input required type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} className={input}/></label><label className="block text-left text-sm">Código del autenticador (si lo activaste)<input autoComplete="one-time-code" inputMode="numeric" value={codigo} onChange={e=>setCodigo(e.target.value)} className={input}/></label>{!sesion&&<label className="block text-left text-sm"><input type="checkbox" checked={recordar} onChange={e=>setRecordar(e.target.checked)}/> Recordar empresa en este dispositivo (30 días)</label>}{error&&<p role="alert" className="text-red-300">{error}</p>}<button disabled={busy} className="sicom-ingresar w-full rounded bg-emerald-600 p-3 disabled:opacity-50">{busy?'Ingresando…':sesion?'Ingresar con este perfil':'Continuar a perfiles'}</button>{perfil&&<button type="button" onClick={()=>{setPerfil(null);setPassword('');setCodigo('');setError('');}} className="text-slate-300">Elegir otro perfil</button>}{!sesion&&<p className="text-sm text-slate-400">Primer ingreso: usa el usuario y contraseña del administrador de tu empresa. Después podrá configurar credenciales de empresa independientes.</p>}</form>}
 {sesion&&<button disabled={busy} onClick={()=>salirEmpresa()} className="block mx-auto mt-10 text-sm text-slate-400">Cerrar sesión de empresa / cambiar empresa</button>}<Link to="/acceso-general" className="block mt-6 text-sm text-slate-400">Acceso administrador / superadministrador</Link><Link to="/registro" className="block mt-3 text-sm text-slate-400">Registrar empresa</Link></section></main>;
}
