import {useState,useRef} from 'react';
import {apiClient} from '@/api/client';
import {getApiErrorMessage} from '@/api/errors';
import {useProductos} from '@/hooks/useInventario';
import {useCajaAbierta} from '@/hooks/usePos';
import {usePosStore} from '@/stores/posStore';
import {useQueryClient} from '@tanstack/react-query';
import type {Venta} from '@/types/pos';
type Original=Venta&{clienteId:number|null};
export default function CambioMercancia(){
 const {sucursalId}=usePosStore();const {data:caja}=useCajaAbierta(sucursalId);const {data:productos=[]}=useProductos();const qc=useQueryClient();
 const [id,setId]=useState(''),[original,setOriginal]=useState<Original|null>(null),[devuelto,setDevuelto]=useState(''),[cantidad,setCantidad]=useState('1'),[nuevo,setNuevo]=useState(''),[cantidadNueva,setCantidadNueva]=useState('1'),[motivo,setMotivo]=useState(''),[total,setTotal]=useState<number|null>(null),[mensaje,setMensaje]=useState(''),[ocupado,setOcupado]=useState(false);const operacion=useRef<{firma:string;clave:string}|null>(null);
 const p=productos.find(x=>x.id===Number(nuevo));
 function editar(fn:()=>void){fn();setTotal(null);}
 async function cargar(){setOcupado(true);try{setOriginal((await apiClient.get<Original>(`/ventas/${id}`)).data);setMensaje('Venta cargada');setTotal(null);}catch(e){setMensaje(getApiErrorMessage(e,'No se pudo cargar'));}finally{setOcupado(false);}}
 async function calcular(){if(!p||!original)return;setOcupado(true);try{const c=(await apiClient.post<{total:number}>('/ventas/calcular',{detalles:[{productoId:p.id,cantidad:Number(cantidadNueva),precioUnitario:p.precioVenta}],clienteId:original.clienteId,puntosCanjear:0})).data;setTotal(c.total);}catch(e){setMensaje(getApiErrorMessage(e,'No se pudo calcular'));}finally{setOcupado(false);}}
 async function cambiar(){if(!original||!caja||!sucursalId||!p||total===null)return;setOcupado(true);try{const payload={ventaOriginalId:original.id,devolucion:{motivo,detalles:[{productoId:Number(devuelto),cantidad:Number(cantidad)}],cajaSesionId:caja.id},nuevaVenta:{sucursalId,cajaSesionId:caja.id,clienteId:original.clienteId,detalles:[{productoId:p.id,cantidad:Number(cantidadNueva),precioUnitario:p.precioVenta}],pagos:[{metodoPago:'EFECTIVO',monto:total}],facturar:true,totalEsperado:total}};
 const firma=JSON.stringify(payload);if(operacion.current?.firma!==firma)operacion.current={firma,clave:crypto.randomUUID()};
 const r=(await apiClient.post<{devolucionId:number;ventaNuevaId:number;diferenciaEfectivo:number}>('/ventas/cambios',{...payload,clave:operacion.current.clave})).data;setMensaje(`Cambio registrado: devolución #${r.devolucionId}, venta #${r.ventaNuevaId}. ${r.diferenciaEfectivo>=0?'Cobrar':'Entregar'} diferencia en efectivo: $${Math.abs(r.diferenciaEfectivo).toLocaleString('es-CO')}`);setTotal(null);setOriginal(null);await qc.invalidateQueries();}catch(e){setMensaje(getApiErrorMessage(e,'No se pudo registrar el cambio'));}finally{setOcupado(false);}}
 return <section className="border rounded-xl p-4 space-y-3"><h3 className="font-semibold">Cambio de mercancía</h3><p className="text-sm">Para administradores, ventas originales de contado y liquidación en efectivo. Registra devolución y nueva venta juntas; si una falla, ambas se deshacen. Para crédito o medicamentos con fórmula, utiliza el flujo de devolución y POS.</p><div className="flex gap-2"><input aria-label="Identificación de venta original" className="input" placeholder="ID de venta original" value={id} onChange={e=>setId(e.target.value)}/><button className="border rounded p-2" disabled={ocupado||!id} onClick={cargar}>Buscar venta</button></div>{original&&<><p>{original.numero} · {original.cliente??'Consumidor final'} · {original.tipoVenta}</p><select aria-label="Producto devuelto" className="input" value={devuelto} onChange={e=>editar(()=>setDevuelto(e.target.value))}><option value="">Producto a devolver</option>{original.detalles.filter(d=>d.productoId).map(d=><option key={d.productoId} value={d.productoId!}>{d.producto} · {d.cantidad} vendidas</option>)}</select><input aria-label="Cantidad devuelta" className="input" type="number" min="0.01" step="0.01" value={cantidad} onChange={e=>editar(()=>setCantidad(e.target.value))}/><select aria-label="Producto de reemplazo" className="input" value={nuevo} onChange={e=>editar(()=>setNuevo(e.target.value))}><option value="">Producto de reemplazo</option>{productos.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select><input aria-label="Cantidad nueva" className="input" type="number" min="0.01" step="0.01" value={cantidadNueva} onChange={e=>editar(()=>setCantidadNueva(e.target.value))}/><input className="input" placeholder="Motivo del cambio" value={motivo} onChange={e=>editar(()=>setMotivo(e.target.value))}/><button className="border rounded p-2" disabled={ocupado||!nuevo||!devuelto||!motivo||!caja} onClick={calcular}>Calcular nueva venta</button>{total!==null&&<><p>Nueva venta: ${total.toLocaleString('es-CO')}. El reintegro se calcula con los valores de la venta original y las devoluciones anteriores.</p><button className="bg-slate-800 text-white rounded p-2" disabled={ocupado||!caja} onClick={()=>{if(window.confirm('Confirmar devolución y nueva venta, liquidando la diferencia en efectivo?'))cambiar();}}>Registrar cambio</button></>}</>}{mensaje&&<p role="status">{mensaje}</p>}{!caja&&<p className="text-sm">Selecciona sucursal y abre caja en POS antes de realizar el cambio.</p>}</section>;
}
