import CambioMercancia from './CambioMercancia';
import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {apiClient} from '@/api/client';
import {getApiErrorMessage} from '@/api/errors';
import {useProductos} from '@/hooks/useInventario';
import {useClientes} from '@/hooks/usePos';
import {useSucursales} from '@/hooks/useSucursales';
type Variante={producto_id:number;producto_base:string;nombre:string;talla:string;color:string;codigo_barras:string};
type Reserva={id:number;cliente:string;sucursal:string;estado_actual:string;vence:string};
type Precio={producto_id:number;nombre:string;precio:number;precio_actual:number};
export default function Comercio(){
 const qc=useQueryClient();const {data:productos=[]}=useProductos();const {data:clientes=[]}=useClientes();const {data:sucursales=[]}=useSucursales();
 const [base,setBase]=useState(''),[variante,setVariante]=useState(''),[talla,setTalla]=useState(''),[color,setColor]=useState(''),[cliente,setCliente]=useState(''),[sucursal,setSucursal]=useState(''),[vence,setVence]=useState(''),[producto,setProducto]=useState(''),[cantidad,setCantidad]=useState('1'),[lineas,setLineas]=useState<{productoId:number;cantidad:number}[]>([]),[lista,setLista]=useState(''),[nombreLista,setNombreLista]=useState(''),[precio,setPrecio]=useState(''),[mensaje,setMensaje]=useState(''),[ocupado,setOcupado]=useState(false);
 const {data:variantes=[]}=useQuery({queryKey:['comercio-variantes'],queryFn:async()=>(await apiClient.get<Variante[]>('/inventario/comercio/variantes')).data});
 const {data:reservas=[]}=useQuery({queryKey:['comercio-reservas'],queryFn:async()=>(await apiClient.get<Reserva[]>('/ventas/reservas')).data});
 const {data:listas=[]}=useQuery({queryKey:['comercio-listas'],queryFn:async()=>(await apiClient.get<{id:number;nombre:string}[]>('/inventario/comercio/listas')).data});
 const {data:precios=[]}=useQuery({queryKey:['comercio-precios',lista],enabled:!!lista,queryFn:async()=>(await apiClient.get<Precio[]>(`/inventario/comercio/listas/${lista}`)).data});
 async function accion(fn:()=>Promise<unknown>,exito:string){setOcupado(true);try{await fn();setMensaje(exito);await qc.invalidateQueries({queryKey:['comercio-variantes']});await qc.invalidateQueries({queryKey:['comercio-reservas']});await qc.invalidateQueries({queryKey:['comercio-listas']});await qc.invalidateQueries({queryKey:['comercio-precios']});await qc.invalidateQueries({queryKey:['productos']});}catch(e){setMensaje(getApiErrorMessage(e,'No se pudo completar'));}finally{setOcupado(false);}}
 function seleccionar(value:string,set:(v:string)=>void,label:string){return <select aria-label={label} className="input" value={value} onChange={e=>set(e.target.value)}><option value="">{label}</option>{productos.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select>;}
 return <div className="space-y-5"><h2 className="text-xl font-semibold">Variantes, reservas y listas de precios</h2>
 <section className="border rounded-xl p-4 space-y-3"><h3 className="font-semibold">Variantes por talla y color</h3><p className="text-sm">Crea cada variante como producto con su propio código de barras, precio y stock. Aquí la vinculas con el producto base.</p><div className="grid sm:grid-cols-2 gap-2">{seleccionar(base,setBase,'Producto base')}{seleccionar(variante,setVariante,'Producto variante')}<input className="input" placeholder="Talla" value={talla} onChange={e=>setTalla(e.target.value)}/><input className="input" placeholder="Color" value={color} onChange={e=>setColor(e.target.value)}/></div><button className="border rounded p-2" disabled={ocupado||!base||!variante||!talla||!color} onClick={()=>accion(()=>apiClient.post('/inventario/comercio/variantes',{productoBaseId:Number(base),productoId:Number(variante),talla,color}),'Variante vinculada')}>Vincular variante</button>{variantes.map(v=><p key={v.producto_id} className="text-sm">{v.producto_base} · {v.nombre} · {v.talla} / {v.color} · {v.codigo_barras??'Sin código de barras'}</p>)}</section>
 <section className="border rounded-xl p-4 space-y-3"><h3 className="font-semibold">Reserva de mercancía</h3><div className="grid sm:grid-cols-3 gap-2"><select aria-label="Cliente de reserva" className="input" value={cliente} onChange={e=>setCliente(e.target.value)}><option value="">Cliente</option>{clientes.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select><select aria-label="Sucursal de reserva" className="input" value={sucursal} onChange={e=>setSucursal(e.target.value)}><option value="">Sucursal</option>{sucursales.map(s=><option key={s.id} value={s.id}>{s.nombre}</option>)}</select><input aria-label="Vencimiento de reserva" className="input" type="datetime-local" value={vence} onChange={e=>setVence(e.target.value)}/></div><div className="flex gap-2">{seleccionar(producto,setProducto,'Producto')}<input aria-label="Cantidad de reserva" className="input" type="number" min="0.01" step="0.01" value={cantidad} onChange={e=>setCantidad(e.target.value)}/><button className="border rounded p-2" disabled={!producto||Number(cantidad)<=0||lineas.some(l=>l.productoId===Number(producto))} onClick={()=>setLineas([...lineas,{productoId:Number(producto),cantidad:Number(cantidad)}])}>Agregar</button></div>{lineas.map(l=><p key={l.productoId}>{productos.find(p=>p.id===l.productoId)?.nombre} · {l.cantidad}<button className="ml-3 underline" onClick={()=>setLineas(lineas.filter(x=>x.productoId!==l.productoId))}>Quitar</button></p>)}<button className="border rounded p-2" disabled={ocupado||!cliente||!sucursal||!vence||!lineas.length} onClick={()=>accion(async()=>{await apiClient.post('/ventas/reservas',{clienteId:Number(cliente),sucursalId:Number(sucursal),vence:new Date(vence).toISOString(),detalles:lineas});setLineas([]);},'Reserva creada. Selecciónala al cobrar al mismo cliente en POS.')}>Guardar reserva</button>{reservas.map(r=><div key={r.id} className="text-sm border-t py-2">#{r.id} · {r.cliente} · {r.sucursal} · {r.estado_actual} · {r.vence}{r.estado_actual==='ACTIVA'&&<button className="ml-2 underline" disabled={ocupado} onClick={()=>{const motivo=window.prompt('Motivo de cancelación');if(motivo?.trim())accion(()=>apiClient.post(`/ventas/reservas/${r.id}/cancelar`,{motivo}),'Reserva cancelada');}}>Cancelar</button>}</div>)}</section>
 <section className="border rounded-xl p-4 space-y-3"><h3 className="font-semibold">Listas de precios</h3><p className="text-sm">Prepara una lista y revisa sus valores. Publicarla reemplaza los precios del catálogo para ventas nuevas; no cambia ventas anteriores.</p><div className="flex gap-2"><input className="input" placeholder="Nombre de lista" value={nombreLista} onChange={e=>setNombreLista(e.target.value)}/><button className="border rounded p-2" disabled={ocupado||!nombreLista} onClick={()=>accion(async()=>{setLista(String((await apiClient.post<number>('/inventario/comercio/listas',{nombre:nombreLista})).data));},'Lista creada')}>Crear lista</button></div><select aria-label="Lista de precios" className="input" value={lista} onChange={e=>setLista(e.target.value)}><option value="">Selecciona lista</option>{listas.map(l=><option key={l.id} value={l.id}>{l.nombre}</option>)}</select>{lista&&<><div className="flex gap-2">{seleccionar(producto,setProducto,'Producto de la lista')}<input aria-label="Precio de la lista" className="input" type="number" min="0.01" step="0.01" value={precio} onChange={e=>setPrecio(e.target.value)}/><button className="border rounded p-2" disabled={ocupado||!producto||!precio} onClick={()=>accion(()=>apiClient.put(`/inventario/comercio/listas/${lista}`,{productoId:Number(producto),precio:Number(precio)}),'Precio guardado')}>Guardar precio</button></div>{precios.map(p=><p key={p.producto_id} className="text-sm">{p.nombre}: actual ${p.precio_actual.toLocaleString('es-CO')} → lista ${p.precio.toLocaleString('es-CO')}</p>)}<button className="bg-slate-800 text-white rounded p-2" disabled={ocupado||!precios.length} onClick={()=>{if(window.confirm(`Publicar ${precios.length} precios en el catálogo de esta empresa?`))accion(()=>apiClient.post(`/inventario/comercio/listas/${lista}/publicar`),'Precios publicados');}}>Publicar lista en catálogo</button></>}</section>
 <CambioMercancia/>
 {mensaje&&<p role="status" className="rounded bg-slate-100 p-3">{mensaje}</p>}</div>;
}
