import ImpuestosConfiguracion from './ImpuestosConfiguracion';
import {useEffect,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {apiClient} from '@/api/client';
import {getApiErrorMessage} from '@/api/errors';
import {ACCIONES,useSicom,type Facturador} from './api';
import {useAuthStore} from '@/stores/authStore';
export default function ConfiguracionSicom(){
 const {data:cfg}=useSicom();const qc=useQueryClient();const admin=useAuthStore(s=>s.esAdministradorTotal||s.esSuperadmin);
 const [activa,setActiva]=useState(false),[pesos,setPesos]=useState('10000'),[porCompra,setPorCompra]=useState('0'),[valor,setValor]=useState('0'),[minimo,setMinimo]=useState('1'),[mensaje,setMensaje]=useState(''),[ocupado,setOcupado]=useState(false);
 const {data:usuarios}=useQuery({queryKey:['sicom-usuarios'],queryFn:async()=>(await apiClient.get<Facturador[]>('/sicom/usuarios')).data,enabled:admin});
 useEffect(()=>{if(cfg){setActiva(cfg.fidelizacion_activa);setPesos(String(cfg.pesos_por_punto));setPorCompra(String(cfg.puntos_por_compra));setValor(String(cfg.valor_punto));setMinimo(String(cfg.minimo_canje));}},[cfg]);
 async function guardar(e:React.FormEvent){e.preventDefault();setOcupado(true);try{await apiClient.put('/sicom/configuracion',{activa,pesosPorPunto:Number(pesos),puntosPorCompra:Number(porCompra),valorPunto:Number(valor),minimoCanje:Number(minimo)});await qc.invalidateQueries({queryKey:['sicom-config']});setMensaje('Configuración guardada');}catch(e){setMensaje(getApiErrorMessage(e,'No se pudo guardar'));}finally{setOcupado(false);}}
 async function usuario(u:Facturador,habilitado:boolean,acciones:string[]){setOcupado(true);try{await apiClient.put(`/sicom/usuarios/${u.id}`,{habilitado,acciones});await qc.invalidateQueries({queryKey:['sicom-usuarios']});setMensaje('Permisos actualizados');}catch(e){setMensaje(getApiErrorMessage(e,'No se pudo actualizar'));}finally{setOcupado(false);}}
 if(!admin)return null;
 return <section className="rounded-xl border bg-white p-5 lg:col-span-2 space-y-5"><h2 className="text-xl font-semibold">Facturación y fidelización</h2><a href="/app/facturacion" className="text-blue-700">Abrir app de facturación</a>
 {cfg?.acceso&&<div><p>Enlace de acceso por perfiles de esta empresa:</p><a className="text-blue-700 break-all" href={`/empresa/${cfg.acceso}`}>{window.location.origin}/empresa/{cfg.acceso}</a><p className="text-xs text-slate-500 mt-1">Compártelo únicamente con tu equipo. Cada perfil requiere su contraseña.</p></div>}
 <form onSubmit={guardar} className="space-y-3"><label className="flex gap-2"><input type="checkbox" checked={activa} onChange={e=>setActiva(e.target.checked)}/>Activar puntos para esta empresa</label><p className="text-sm text-slate-500">Se suman los puntos por monto y por compra. Desactivar no elimina saldos ni historial.</p><div className="grid sm:grid-cols-4 gap-3">{[['Pesos por punto',pesos,setPesos,'0.01'],['Puntos por compra',porCompra,setPorCompra,'1'],['Valor de cada punto ($)',valor,setValor,'0.01'],['Mínimo de puntos para canjear',minimo,setMinimo,'1']].map(([label,v,set,step])=><label key={label as string} className="text-sm">{label as string}<input required type="number" min={label==='Puntos por compra'||label==='Valor de cada punto ($)'?'0':'0.01'} step={step as string} value={v as string} onChange={e=>(set as (v:string)=>void)(e.target.value)} className="input mt-1"/></label>)}</div><button disabled={ocupado} className="rounded bg-slate-800 text-white p-2">Guardar reglas</button></form>
 <ImpuestosConfiguracion/>
 <h3 className="font-semibold">Usuarios de la app de facturación</h3><p className="text-sm text-slate-500">Los administradores mantienen acceso completo. Los facturadores quedan limitados a las acciones elegidas.</p>
 <div className="space-y-4">{usuarios?.map(u=><div key={u.id} className="rounded border p-3"><label className="flex gap-2 font-medium"><input disabled={ocupado} type="checkbox" checked={u.facturador} onChange={e=>usuario(u,e.target.checked,['VENDER','VER_PROPIAS','REIMPRIMIR','REGISTRAR_CLIENTE'])}/>{u.nombre}{!u.activo&&' (inactivo)'}</label>{u.facturador&&<div className="mt-2 grid sm:grid-cols-3 gap-2">{Object.entries(ACCIONES).map(([codigo,label])=><label key={codigo} className="text-sm flex gap-2"><input disabled={ocupado} type="checkbox" checked={u.acciones.includes(codigo)} onChange={e=>usuario(u,true,e.target.checked?[...u.acciones,codigo]:u.acciones.filter(a=>a!==codigo))}/>{label}</label>)}</div>}</div>)}</div>{mensaje&&<p role="status">{mensaje}</p>}</section>;
}
