import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {apiClient} from '@/api/client';
import {getApiErrorMessage} from '@/api/errors';
interface Cuenta {id:number;username:string;nombre:string;empresa:string;activo:boolean;esContador:boolean;habilitado:boolean}
export function ContadoresPlataforma(){
 const cache=useQueryClient(); const [busqueda,setBusqueda]=useState(''); const [error,setError]=useState(''); const [ocupado,setOcupado]=useState<number|null>(null);
 const {data,isLoading,isError}=useQuery({queryKey:['plataforma-contadores'],queryFn:async()=>(await apiClient.get<Cuenta[]>('/plataforma/contadores')).data});
 async function guardar(u:Cuenta,esContador:boolean,habilitado:boolean){setOcupado(u.id);setError('');try{await apiClient.put(`/plataforma/contadores/${u.id}`,{esContador,habilitado});await cache.invalidateQueries({queryKey:['plataforma-contadores']});}catch(e){setError(getApiErrorMessage(e,'No se pudo guardar'));}finally{setOcupado(null)}}
 return <section className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Acceso de contadores</h2><p className="my-2 text-sm text-ink-500">Primero identifica la cuenta como contador y después habilita su acceso. La empresa cliente debe conceder acceso a sus datos. El usuario debe volver a ingresar para actualizar su menú.</p><input className="input my-3" placeholder="Buscar usuario o empresa" value={busqueda} onChange={e=>setBusqueda(e.target.value)}/>{error&&<p role="alert" className="text-red-600">{error}</p>}{isLoading?<p>Cargando…</p>:isError?<p>No se pudieron consultar las cuentas.</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="text-left">Cuenta</th><th>Empresa</th><th>Contador</th><th>Habilitado</th></tr></thead><tbody>{data?.filter(u=>`${u.username} ${u.nombre} ${u.empresa}`.toLowerCase().includes(busqueda.toLowerCase())).map(u=><tr key={u.id} className="border-t"><td className="py-3">{u.nombre}<br/><span className="text-ink-400">{u.username}{!u.activo?' · Inactivo':''}</span></td><td>{u.empresa}</td><td className="text-center"><input aria-label={`Contador ${u.username}`} type="checkbox" disabled={ocupado===u.id} checked={u.esContador} onChange={e=>guardar(u,e.target.checked,false)}/></td><td className="text-center"><input aria-label={`Habilitar ${u.username}`} type="checkbox" disabled={!u.esContador||!u.activo||ocupado===u.id} checked={u.habilitado} onChange={e=>guardar(u,u.esContador,e.target.checked)}/></td></tr>)}</tbody></table></div>}</section>
}
