import {useAuthStore} from '@/stores/authStore';
import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {apiClient} from '@/api/client';
import {getApiErrorMessage} from '@/api/errors';
export function DobleFactor(){
 const cache=useQueryClient();const [password,setPassword]=useState('');const [codigo,setCodigo]=useState('');const [secreto,setSecreto]=useState('');const [recuperacion,setRecuperacion]=useState<string[]>([]);const [error,setError]=useState('');const [ocupado,setOcupado]=useState(false);
 const {data}=useQuery({queryKey:['doble-factor'],queryFn:async()=>(await apiClient.get<{activo:boolean;configurable:boolean}>('/plataforma/doble-factor')).data});
 async function iniciar(){setOcupado(true);setError('');try{const r=await apiClient.post<{secreto:string}>('/plataforma/doble-factor/iniciar',{password});setSecreto(r.data.secreto);setPassword('');}catch(e){setError(getApiErrorMessage(e,'No se pudo iniciar'));}finally{setOcupado(false)}}
 async function confirmar(){setOcupado(true);setError('');try{const r=await apiClient.post<{codigos:string[];accessToken:string;refreshToken:string}>('/plataforma/doble-factor/confirmar',{codigo});useAuthStore.setState({accessToken:r.data.accessToken,refreshToken:r.data.refreshToken});setRecuperacion(r.data.codigos);setSecreto('');setCodigo('');await cache.invalidateQueries({queryKey:['doble-factor']});}catch(e){setError(getApiErrorMessage(e,'Código inválido'));}finally{setOcupado(false)}}
 return <section className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Doble factor del superadministrador</h2><p className="my-3 text-sm">Estado: {data?.activo?'Activo':'Sin activar'}. Usa una aplicación de autenticación que genere códigos de seis dígitos cada 30 segundos.</p>{!data?.configurable&&<p>Debes configurar la clave de cifrado SICOM_SECRETS_KEY en el backend antes de activar esta función.</p>}{error&&<p role="alert" className="text-red-600">{error}</p>}{!secreto&&data?.configurable&&<div className="space-y-2"><label>Confirma tu contraseña<input type="password" autoComplete="current-password" className="input" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={ocupado||!password} className="rounded-lg bg-ink-800 px-4 py-2 text-white" onClick={iniciar}>{data.activo?'Cambiar autenticador':'Configurar autenticador'}</button></div>}{secreto&&<div className="space-y-3"><p>Agrega una cuenta TOTP manual en tu autenticador con nombre SICOM y esta clave. No compartas la clave.</p><code className="block break-all rounded bg-ink-50 p-3">{secreto}</code><label>Código generado<input className="input" autoComplete="one-time-code" inputMode="numeric" value={codigo} onChange={e=>setCodigo(e.target.value)}/></label><button disabled={ocupado} className="rounded-lg bg-teal-700 px-4 py-2 text-white" onClick={confirmar}>Confirmar y activar</button></div>}{recuperacion.length>0&&<div className="mt-4 rounded bg-amber-50 p-4"><p className="font-semibold">Guarda estos códigos de recuperación antes de salir. Se muestran una sola vez y cada uno permite un solo ingreso.</p><pre className="mt-2 whitespace-pre-wrap">{recuperacion.join('\n')}</pre></div>}</section>
}
