import SoportesDispensacion from './SoportesDispensacion';
import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {apiClient} from '@/api/client';
import {getApiErrorMessage} from '@/api/errors';
import {useProductos} from '@/hooks/useInventario';
import {useSucursales} from '@/hooks/useSucursales';
type Ficha={maneja_lotes?:boolean;principio_activo?:string;concentracion?:string;laboratorio?:string;presentacion?:string;registro_sanitario?:string;requiere_formula?:boolean;temperatura_min?:number;temperatura_max?:number;humedad_max?:number};
type Lote={id:number;producto_id:number;producto:string;sucursal:string;codigo:string;vencimiento:string;estado:string;cantidad:number;vencido:boolean;alerta_vencimiento:boolean};
type Lectura={id:number;producto:string;sucursal:string;temperatura:number;humedad:number;fecha:string;alerta:boolean};
type Traza={fecha:string;referencia_tipo:string;referencia_id:number;direccion:string;cantidad:number};
export default function Drogueria(){
 const qc=useQueryClient();const {data:productos=[]}=useProductos();const {data:sucursales=[]}=useSucursales();
 const [producto,setProducto]=useState(''),[sucursal,setSucursal]=useState(''),[mensaje,setMensaje]=useState(''),[ocupado,setOcupado]=useState(false),[ficha,setFicha]=useState<Ficha>({});
 const [codigo,setCodigo]=useState(''),[vence,setVence]=useState(''),[cantidad,setCantidad]=useState(''),[temperatura,setTemperatura]=useState(''),[humedad,setHumedad]=useState(''),[obs,setObs]=useState('');
 const [nombrePresentacion,setNombrePresentacion]=useState(''),[unidades,setUnidades]=useState(''),[barras,setBarras]=useState(''),[historial,setHistorial]=useState<Traza[]>([]);
 const {data:lotes=[],isError:errorLotes}=useQuery({queryKey:['drogueria-lotes'],queryFn:async()=>(await apiClient.get<Lote[]>('/inventario/drogueria/lotes')).data});
 const {data:lecturas=[]}=useQuery({queryKey:['drogueria-lecturas'],queryFn:async()=>(await apiClient.get<Lectura[]>('/inventario/drogueria/almacenamiento')).data});
 const {data:presentaciones=[]}=useQuery({queryKey:['presentaciones',producto],enabled:!!producto,queryFn:async()=>(await apiClient.get<{id:number;nombre:string;unidades:number;codigo_barras:string}[]>(`/inventario/drogueria/presentaciones/${producto}`)).data});
 async function accion(fn:()=>Promise<unknown>,exito:string){setOcupado(true);setMensaje('');try{await fn();setMensaje(exito);await qc.invalidateQueries({queryKey:['drogueria-lotes']});await qc.invalidateQueries({queryKey:['drogueria-lecturas']});await qc.invalidateQueries({queryKey:['presentaciones']});}catch(e){setMensaje(getApiErrorMessage(e,'No se pudo completar'));}finally{setOcupado(false);}}
 async function elegir(id:string){setProducto(id);setFicha({});if(id)await accion(async()=>setFicha((await apiClient.get<Ficha>(`/inventario/drogueria/fichas/${id}`)).data),'Ficha cargada');}
 function texto(k:keyof Ficha,label:string){return <label className="text-sm" key={k}>{label}<input className="input" value={String(ficha[k]??'')} onChange={e=>setFicha({...ficha,[k]:e.target.value})}/></label>;}
 const n=(v:unknown)=>v===undefined||v===null||v===''?null:Number(v);
 return <div className="space-y-5"><h2 className="font-semibold text-xl">Droguería: trazabilidad y almacenamiento</h2><p className="text-sm text-slate-600">Las cantidades se expresan en unidades base. Distribuye el stock existente por lotes antes de activar el control. Las devoluciones quedan en cuarentena. Medicamentos de control especial requieren un módulo específico.</p>
 <div className="flex gap-3"><select className="input" aria-label="Producto de droguería" value={producto} onChange={e=>elegir(e.target.value)}><option value="">Selecciona producto</option>{productos.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select><select className="input" aria-label="Sucursal" value={sucursal} onChange={e=>setSucursal(e.target.value)}><option value="">Selecciona sucursal</option>{sucursales.map(s=><option key={s.id} value={s.id}>{s.nombre}</option>)}</select></div>
 {producto&&<section className="border rounded-xl p-4 space-y-3"><h3 className="font-semibold">Ficha del producto</h3><div className="grid sm:grid-cols-2 gap-3">{texto('principio_activo','Principio activo')}{texto('concentracion','Concentración')}{texto('laboratorio','Laboratorio')}{texto('presentacion','Presentación')}{texto('registro_sanitario','Registro sanitario')}{texto('temperatura_min','Temperatura mínima °C')}{texto('temperatura_max','Temperatura máxima °C')}{texto('humedad_max','Humedad máxima %')}</div><label className="flex gap-2"><input type="checkbox" checked={!!ficha.maneja_lotes} onChange={e=>setFicha({...ficha,maneja_lotes:e.target.checked})}/>Controlar inventario por lote</label><label className="flex gap-2"><input type="checkbox" checked={!!ficha.requiere_formula} onChange={e=>setFicha({...ficha,requiere_formula:e.target.checked})}/>Exigir soporte de fórmula al cobrar</label><button disabled={ocupado} className="rounded bg-slate-800 text-white p-2" onClick={()=>accion(()=>apiClient.put(`/inventario/drogueria/fichas/${producto}`,{manejaLotes:!!ficha.maneja_lotes,principioActivo:ficha.principio_activo,concentracion:ficha.concentracion,laboratorio:ficha.laboratorio,presentacion:ficha.presentacion,registroSanitario:ficha.registro_sanitario,requiereFormula:!!ficha.requiere_formula,controlEspecial:false,temperaturaMin:n(ficha.temperatura_min),temperaturaMax:n(ficha.temperatura_max),humedadMax:n(ficha.humedad_max)}),'Ficha guardada')}>Guardar ficha</button>
 <div className="border-t pt-3"><h4 className="font-medium">Distribuir stock existente sin cambiar su cantidad</h4><div className="grid sm:grid-cols-3 gap-2"><input aria-label="Código de lote" className="input" placeholder="Lote" value={codigo} onChange={e=>setCodigo(e.target.value)}/><input aria-label="Vencimiento" className="input" type="date" value={vence} onChange={e=>setVence(e.target.value)}/><input aria-label="Cantidad del lote" className="input" type="number" min="0.01" step="0.01" value={cantidad} onChange={e=>setCantidad(e.target.value)}/></div><button disabled={ocupado||!sucursal||!codigo||!vence||!cantidad} className="border rounded p-2 mt-2" onClick={()=>accion(()=>apiClient.post('/inventario/drogueria/lotes/inicial',{productoId:Number(producto),sucursalId:Number(sucursal),codigo,vencimiento:vence,cantidad:Number(cantidad)}),'Distribución registrada')}>Asignar cantidad a lote</button></div>
 <div className="border-t pt-3"><h4 className="font-medium">Presentaciones y equivalencias</h4><p className="text-xs">Una presentación representa esta cantidad de unidades base.</p><div className="grid sm:grid-cols-3 gap-2"><input className="input" placeholder="Caja / blíster / unidad" value={nombrePresentacion} onChange={e=>setNombrePresentacion(e.target.value)}/><input className="input" type="number" placeholder="Unidades base" value={unidades} onChange={e=>setUnidades(e.target.value)}/><input className="input" placeholder="Código de barras" value={barras} onChange={e=>setBarras(e.target.value)}/></div><button disabled={ocupado||!nombrePresentacion||!unidades} className="border rounded p-2 mt-2" onClick={()=>accion(()=>apiClient.post(`/inventario/drogueria/presentaciones/${producto}`,{nombre:nombrePresentacion,unidades:Number(unidades),codigoBarras:barras}),'Presentación guardada')}>Guardar equivalencia</button>{presentaciones.map(p=><p key={p.id} className="text-sm">{p.nombre}: {p.unidades} unidades · {p.codigo_barras}</p>)}</div></section>}
 <section className="border rounded-xl p-4"><h3 className="font-semibold">Lotes y alertas de vencimiento</h3>{errorLotes&&<p>No se pudieron cargar los lotes.</p>}<div className="overflow-auto"><table className="w-full text-sm"><thead><tr><th>Producto</th><th>Sucursal</th><th>Lote</th><th>Vence</th><th>Stock</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{lotes.filter(l=>!producto||l.producto_id===Number(producto)).map(l=><tr key={l.id} className={l.vencido?'bg-red-50':l.alerta_vencimiento?'bg-amber-50':''}><td>{l.producto}</td><td>{l.sucursal}</td><td>{l.codigo}</td><td>{l.vencimiento}{l.vencido?' · Vencido':''}</td><td>{l.cantidad}</td><td>{l.estado}</td><td><button disabled={ocupado} className="p-2 underline" onClick={()=>accion(async()=>setHistorial((await apiClient.get<Traza[]>(`/inventario/drogueria/lotes/${l.id}/historial`)).data),'Historial cargado')}>Historial</button><select aria-label={`Estado de lote ${l.codigo}`} value={l.estado} disabled={ocupado} onChange={e=>{const estado=e.target.value;const motivo=window.prompt('Motivo y evaluación del cambio de estado');if(motivo?.trim())accion(()=>apiClient.put(`/inventario/drogueria/lotes/${l.id}/estado`,{estado,motivo}),'Estado registrado');}}>{['DISPONIBLE','CUARENTENA','RETIRADO'].map(x=><option key={x}>{x}</option>)}</select></td></tr>)}</tbody></table></div>{historial.map((t,i)=><p key={i} className="text-xs">{t.fecha} · {t.direccion} {t.cantidad} · {t.referencia_tipo} #{t.referencia_id}</p>)}</section>
 <section className="border rounded-xl p-4 space-y-3"><h3 className="font-semibold">Lecturas de almacenamiento</h3><div className="grid sm:grid-cols-3 gap-2"><input aria-label="Temperatura °C" className="input" type="number" placeholder="Temperatura °C" value={temperatura} onChange={e=>setTemperatura(e.target.value)}/><input aria-label="Humedad %" className="input" type="number" placeholder="Humedad %" value={humedad} onChange={e=>setHumedad(e.target.value)}/><input aria-label="Observaciones" className="input" placeholder="Observaciones" value={obs} onChange={e=>setObs(e.target.value)}/></div><button disabled={ocupado||!sucursal||!temperatura||!humedad} className="border rounded p-2" onClick={()=>accion(()=>apiClient.post('/inventario/drogueria/almacenamiento',{sucursalId:Number(sucursal),productoId:producto?Number(producto):null,temperatura:Number(temperatura),humedad:Number(humedad),observaciones:obs}),'Lectura registrada')}>Registrar lectura</button>{lecturas.map(l=><p key={l.id} className={`text-sm ${l.alerta?'text-red-700':''}`}>{l.fecha} · {l.sucursal} · {l.producto??'Almacén'} · {l.temperatura} °C / {l.humedad}% {l.alerta?'Fuera de rango':''}</p>)}</section>
 <SoportesDispensacion/>
 {mensaje&&<p role="status" className="rounded bg-slate-100 p-3">{mensaje}</p>}</div>;
}
