import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {apiClient} from '@/api/client';
import {getApiErrorMessage} from '@/api/errors';
interface Pago{id:number;monto:number;metodo_pago:string;fecha:string}
interface Soporte{id:number;abono_id:number|null;nombre:string}
interface Cuenta{id:number;numero_factura_proveedor:string;estado:string;saldo_pendiente:number}
export function HistorialProveedor({proveedorId}:{proveedorId:number}){
 const [cuenta,setCuenta]=useState<number|null>(null);const [error,setError]=useState('');const [ocupado,setOcupado]=useState(false);const cache=useQueryClient();
 const {data:cuentas}=useQuery({queryKey:['compras-historial',proveedorId],queryFn:async()=>(await apiClient.get<Cuenta[]>(`/cuentas-por-pagar/proveedor/${proveedorId}/historial`)).data});
 const {data}=useQuery({enabled:!!cuenta,queryKey:['pagos-historial',cuenta],queryFn:async()=>(await apiClient.get<{pagos:Pago[];soportes:Soporte[]}>(`/cuentas-por-pagar/${cuenta}/historial`)).data});
 async function subir(pago:number|null,archivo?:File){if(!archivo||!cuenta)return;if(archivo.size>5*1024*1024){setError('El archivo supera 5 MB');return;}setOcupado(true);setError('');try{const form=new FormData();form.append('archivo',archivo);if(pago!==null)form.append('abonoId',String(pago));await apiClient.post(`/cuentas-por-pagar/${cuenta}/soportes`,form,{headers:{'Content-Type':'multipart/form-data'}});await cache.invalidateQueries({queryKey:['pagos-historial',cuenta]});}catch(e){setError(getApiErrorMessage(e,'No se pudo adjuntar el soporte'));}finally{setOcupado(false)}}
 async function descargar(s:Soporte){try{const r=await apiClient.get(`/cuentas-por-pagar/${cuenta}/soportes/${s.id}`,{responseType:'blob'});const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download=s.nombre;a.click();URL.revokeObjectURL(url);}catch(e){setError(getApiErrorMessage(e,'No se pudo descargar'));}}
 return <section className="rounded-xl border bg-white p-4"><h3 className="font-semibold">Historial de pagos y soportes</h3><select className="input my-3" value={cuenta??''} onChange={e=>setCuenta(e.target.value?Number(e.target.value):null)}><option value="">Selecciona una factura, incluso saldada</option>{cuentas?.map(c=><option key={c.id} value={c.id}>{c.numero_factura_proveedor} · {c.estado} · Saldo ${Number(c.saldo_pendiente).toLocaleString('es-CO')}</option>)}</select>{error&&<p role="alert" className="text-red-600">{error}</p>}{cuenta&&<div className="my-3 rounded bg-ink-50 p-3"><label>Adjuntar factura del proveedor<input disabled={ocupado} type="file" accept="image/jpeg,image/png,application/pdf" onChange={e=>subir(null,e.target.files?.[0])}/></label>{data?.soportes.filter(s=>s.abono_id===null).map(s=><button key={s.id} className="mr-3 text-teal-700 underline" onClick={()=>descargar(s)}>{s.nombre}</button>)}</div>}{data?.pagos.map(p=><div key={p.id} className="border-t py-3"><p>{p.fecha} · {p.metodo_pago} · ${Number(p.monto).toLocaleString('es-CO')}</p><label className="mt-2 block text-sm">Adjuntar foto o PDF<input disabled={ocupado} type="file" accept="image/jpeg,image/png,application/pdf" onChange={e=>subir(p.id,e.target.files?.[0])}/></label><label className="block text-sm md:hidden">Tomar foto<input disabled={ocupado} type="file" accept="image/*" capture="environment" onChange={e=>subir(p.id,e.target.files?.[0])}/></label>{data.soportes.filter(s=>s.abono_id===p.id).map(s=><button key={s.id} className="mr-3 text-sm text-teal-700 underline" onClick={()=>descargar(s)}>{s.nombre}</button>)}</div>)}{cuenta&&data?.pagos.length===0&&<p>No hay pagos registrados.</p>}</section>
}
