import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {apiClient} from '@/api/client';
import {getApiErrorMessage} from '@/api/errors';
import {Modal} from '@/components/ui/Modal';
interface Registro {id:number;cuenta_id?:number;fecha?:string;fecha_emision?:string;responsable?:string;numero_factura_proveedor?:string;total?:number;saldo_pendiente?:number;estado?:string;monto?:number;metodo_pago?:string}
interface Soporte {id:number;nombre:string;abono_id?:number|null}
function guardar(blob:Blob,nombre:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=nombre;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function HistorialOrden({id,onClose}:{id:number;onClose:()=>void}){
 const [ocupado,setOcupado]=useState(false),[error,setError]=useState(''),[soportes,setSoportes]=useState<Record<number,Soporte[]>>({});
 const {data,isLoading,isError}=useQuery({queryKey:['historial-orden',id],queryFn:async()=>(await apiClient.get<{recepciones:Registro[];facturas:Registro[];pagos:Registro[]}>(`/ordenes-compra/${id}/historial`)).data});
 async function pdf(r:Registro){setOcupado(true);setError('');try{const {data}=await apiClient.get<Blob>(`/facturas-compra/${r.id}/pdf`,{responseType:'blob'});guardar(data,`compra-${r.id}.pdf`);}catch(e){setError(getApiErrorMessage(e,'No se pudo descargar el PDF'));}finally{setOcupado(false);}}
 async function cargar(cuenta:number){setOcupado(true);setError('');try{const {data}=await apiClient.get<{soportes:Soporte[]}>(`/cuentas-por-pagar/${cuenta}/historial`);setSoportes(s=>({...s,[cuenta]:data.soportes}));}catch(e){setError(getApiErrorMessage(e,'No se pudieron consultar los soportes'));}finally{setOcupado(false);}}
 async function soporte(cuenta:number,s:Soporte){setOcupado(true);setError('');try{const {data}=await apiClient.get<Blob>(`/cuentas-por-pagar/${cuenta}/soportes/${s.id}`,{responseType:'blob'});guardar(data,s.nombre);}catch(e){setError(getApiErrorMessage(e,'No se pudo descargar el soporte'));}finally{setOcupado(false);}}
 return <Modal isOpen={true} onClose={onClose} title="Seguimiento de la compra" size="lg">{isLoading?<p>Cargando…</p>:isError?<p>No se pudo consultar el historial.</p>:<div className="space-y-5">{error&&<p role="alert" className="text-red-700">{error}</p>}{(['recepciones','facturas','pagos'] as const).map(tipo=><section key={tipo}><h3 className="font-semibold capitalize">{tipo}</h3>{data?.[tipo].length===0?<p className="text-sm text-ink-400">Sin registros</p>:data?.[tipo].map(r=><div className="border-t py-3 text-sm" key={r.id}><p>{r.fecha??r.fecha_emision} · {r.numero_factura_proveedor??`#${r.id}`} {r.estado} {r.responsable}</p>{r.total!=null&&<p>Total: ${Number(r.total).toLocaleString('es-CO')} · Saldo: ${Number(r.saldo_pendiente??0).toLocaleString('es-CO')}</p>}{r.monto!=null&&<p>{r.metodo_pago}: ${Number(r.monto).toLocaleString('es-CO')}</p>}{tipo==='facturas'&&<div className="mt-2 space-y-2"><div className="flex gap-2 flex-wrap"><button disabled={ocupado} onClick={()=>pdf(r)} className="rounded bg-slate-800 px-3 py-2 text-white disabled:opacity-50">Descargar factura en PDF</button>{r.cuenta_id!=null&&<button disabled={ocupado} onClick={()=>cargar(r.cuenta_id!)} className="rounded border px-3 py-2">Ver soportes originales</button>}</div><p className="text-xs text-slate-500">PDF del registro interno de SICOM. El documento original del proveedor se conserva como soporte adjunto.</p>{r.cuenta_id!=null&&soportes[r.cuenta_id]?.map(s=><button key={s.id} disabled={ocupado} onClick={()=>soporte(r.cuenta_id!,s)} className="block text-blue-700 underline">{s.nombre}{s.abono_id?` · Pago #${s.abono_id}`:' · Factura'}</button>)}{r.cuenta_id!=null&&soportes[r.cuenta_id]?.length===0&&<p>Sin soportes adjuntos.</p>}</div>}</div>)}</section>)}</div>}</Modal>;
}
