import {useEffect,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {apiClient} from '@/api/client';
import {getApiErrorMessage} from '@/api/errors';
import {useSicom} from './api';
import type {Producto,Combo} from '@/types/inventario';
const ETIQUETAS:Record<string,string>={SIN_CONFIGURAR:'Sin configurar',IVA:'IVA',INC:'Impuesto al consumo (INC)',EXENTO:'Exento',EXCLUIDO:'Excluido',NO_APLICA:'No aplica'};
const TIPOS=['SIN_CONFIGURAR','IVA','INC','EXENTO','EXCLUIDO','NO_APLICA'];
function ReglaArticulo({item,ruta}:{item:Producto|Combo;ruta:'productos'|'combos'}){
 const qc=useQueryClient();const [tipo,setTipo]=useState(item.impuestoTipo??'SIN_CONFIGURAR'),[tarifa,setTarifa]=useState(String(item.impuestoTarifa??0)),[ocupado,setOcupado]=useState(false),[mensaje,setMensaje]=useState('');
 useEffect(()=>{setTipo(item.impuestoTipo??'SIN_CONFIGURAR');setTarifa(String(item.impuestoTarifa??0));},[item]);
 async function guardar(){setOcupado(true);try{await apiClient.put(`/${ruta}/${item.id}/impuesto`,{tipo,tarifa:['IVA','INC'].includes(tipo)?Number(tarifa):0});await qc.invalidateQueries({queryKey:['impuestos-catalogo']});await qc.invalidateQueries({queryKey:[ruta]});await qc.invalidateQueries({queryKey:['calculo-venta']});setMensaje('Guardado');}catch(e){setMensaje(getApiErrorMessage(e,'No se pudo guardar'));}finally{setOcupado(false);}}
 return <div className="border-t py-3"><div className="grid gap-2 sm:grid-cols-[1fr_160px_110px_90px] items-center"><span>{item.nombre}<span className="block text-xs text-slate-500">{ruta==='combos'?'Combo':'Producto / servicio'}</span></span><select aria-label={`Impuesto de ${item.nombre}`} value={tipo} onChange={e=>setTipo(e.target.value)} className="input">{TIPOS.map(t=><option key={t} value={t}>{ETIQUETAS[t]}</option>)}</select><input aria-label={`Tarifa de ${item.nombre}`} className="input" type="number" min="0" max="100" step="0.01" disabled={!['IVA','INC'].includes(tipo)} value={tarifa} onChange={e=>setTarifa(e.target.value)}/><button type="button" disabled={ocupado} className="rounded bg-slate-800 text-white p-2" onClick={guardar}>Guardar</button></div>{mensaje&&<p role="status" className="text-xs mt-1">{mensaje}</p>}</div>;
}
export default function ImpuestosConfiguracion(){
 const {data:cfg}=useSicom();const qc=useQueryClient();const [activa,setActiva]=useState(false),[modo,setModo]=useState('INCLUIDO'),[busqueda,setBusqueda]=useState(''),[ocupado,setOcupado]=useState(false),[mensaje,setMensaje]=useState('');
 const {data,isError}=useQuery({queryKey:['impuestos-catalogo'],queryFn:async()=>{const [p,c]=await Promise.all([apiClient.get<Producto[]>('/productos'),apiClient.get<Combo[]>('/combos')]);return {productos:p.data,combos:c.data};}});
 useEffect(()=>{if(cfg){setActiva(cfg.impuestos_activos);setModo(cfg.modo_impuesto);}},[cfg]);
 async function guardar(e:React.FormEvent){e.preventDefault();setOcupado(true);try{await apiClient.put('/sicom/impuestos',{activa,modo});await qc.invalidateQueries({queryKey:['sicom-config']});await qc.invalidateQueries({queryKey:['calculo-venta']});setMensaje('Configuración de impuestos guardada');}catch(e){setMensaje(getApiErrorMessage(e,'No se pudo guardar'));}finally{setOcupado(false);}}
 const pendientes=[...(data?.productos??[]),...(data?.combos??[])].filter(x=>x.estado&&x.impuestoTipo==='SIN_CONFIGURAR').length;
 return <section className="rounded-xl border bg-slate-50 p-4 space-y-3"><h3 className="font-semibold text-lg">Impuestos y precios de esta empresa</h3><form onSubmit={guardar} className="space-y-3"><label className="flex gap-2"><input type="checkbox" checked={activa} onChange={e=>setActiva(e.target.checked)}/>Activar impuestos en ventas</label><select aria-label="Modalidad de precios" className="input" value={modo} onChange={e=>setModo(e.target.value)}><option value="INCLUIDO">Precio con impuesto incluido</option><option value="ADICIONAL">Sumar impuesto al precio</option></select><p className="text-sm text-slate-600">Las tarifas se definen por artículo. El cambio aplica a ventas nuevas; los valores históricos se conservan. Al activar, un artículo sin configurar no se puede vender.</p><p className="text-sm text-slate-600">IVA e INC se registran por separado. Si usas contabilidad, configura sus cuentas antes de cobrar. La clasificación de cada artículo debe corresponder a tu empresa y actividad.</p><button disabled={ocupado||!cfg} className="rounded bg-slate-800 text-white p-2">Guardar modalidad</button></form>{mensaje&&<p role="status">{mensaje}</p>}<p className="text-sm">Artículos activos sin configurar: {pendientes}</p><input aria-label="Buscar artículo para impuestos" className="input" placeholder="Buscar producto o combo…" value={busqueda} onChange={e=>setBusqueda(e.target.value)}/>{isError&&<p>No se pudo cargar el catálogo.</p>}<div className="max-h-96 overflow-auto">{(['productos','combos'] as const).flatMap(r=>(data?.[r]??[]).filter(x=>x.estado&&x.nombre.toLowerCase().includes(busqueda.toLowerCase())).map(x=><ReglaArticulo key={`${r}-${x.id}`} item={x} ruta={r}/>))}</div></section>;
}
