import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {apiClient} from '@/api/client';
import {getApiErrorMessage} from '@/api/errors';
type Categoria={id:number;nombre:string;padreId:number|null;impuestoTipo:string|null;impuestoTarifa:number|null};
type Vista={huella:string;cantidad:number;ejemplos:{id:number;nombre:string;tipoAnterior:string;tarifaAnterior:number;precio:number;totalIncluido:number;totalAdicional:number}[]};
export default function ImpuestosMasivos(){
 const qc=useQueryClient();
 const {data:categorias=[]}=useQuery({queryKey:['categorias'],queryFn:async()=>(await apiClient.get<Categoria[]>('/categorias')).data});
 const [alcance,setAlcance]=useState('CATEGORIA'),[categoria,setCategoria]=useState(''),[ids,setIds]=useState(''),[tipo,setTipo]=useState('IVA'),[tarifa,setTarifa]=useState('19'),[solo,setSolo]=useState(true),[excepciones,setExcepciones]=useState(false),[vista,setVista]=useState<Vista|null>(null),[ocupado,setOcupado]=useState(false),[mensaje,setMensaje]=useState('');
 const [padre,setPadre]=useState('');
 function cambio(f:()=>void){f();setVista(null);setMensaje('');}
 function solicitud(){return {alcance,categoriaId:categoria?Number(categoria):null,productoIds:ids.split(',').map(x=>x.trim()).filter(Boolean).map(Number),tipo,tarifa:['IVA','INC'].includes(tipo)?Number(tarifa):0,soloSinConfigurar:solo,reemplazarExcepciones:excepciones};}
 async function ejecutar(aplicar:boolean){setOcupado(true);try{const r=await apiClient.post<Vista>(`/productos/impuestos-masivos/${aplicar?'aplicar':'vista-previa'}`,{...solicitud(),huella:aplicar?vista?.huella:undefined});setVista(r.data);if(aplicar){setMensaje(`Se actualizaron ${r.data.cantidad} productos.`);setVista(null);await qc.invalidateQueries({queryKey:['impuestos-catalogo']});await qc.invalidateQueries({queryKey:['productos']});await qc.invalidateQueries({queryKey:['calculo-venta']});}}catch(e){setMensaje(getApiErrorMessage(e,'No se pudo procesar'));setVista(null);}finally{setOcupado(false);}}
 async function regla(){setOcupado(true);try{await apiClient.put(`/productos/impuestos-masivos/categorias/${categoria}`,{padreId:padre?Number(padre):null,tipo,tarifa:['IVA','INC'].includes(tipo)?Number(tarifa):0});setMensaje('Regla guardada. Los productos nuevos sin excepción heredarán esta clasificación. Los existentes se modifican con la aplicación masiva.');await qc.invalidateQueries({queryKey:['categorias']});}catch(e){setMensaje(getApiErrorMessage(e,'No se pudo guardar la regla'));}finally{setOcupado(false);}}
 return <section className="rounded-xl border bg-white p-4 space-y-3"><h4 className="font-semibold">Aplicación masiva y reglas por categoría</h4><p className="text-sm text-slate-600">Configura la clasificación que corresponda. Las categorías organizan el catálogo y no determinan por sí mismas el impuesto legal.</p>
 <select className="input" aria-label="Alcance" value={alcance} onChange={e=>cambio(()=>setAlcance(e.target.value))}><option value="TODOS">Todos los productos activos</option><option value="CATEGORIA">Categoría y subcategorías</option><option value="SELECCION">Productos por identificación</option></select>
 <select className="input" aria-label="Categoría" value={categoria} onChange={e=>cambio(()=>{setCategoria(e.target.value);const c=categorias.find(x=>x.id===Number(e.target.value));setPadre(c?.padreId?String(c.padreId):'');})}><option value="">Selecciona categoría</option>{categorias.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select>
 {alcance==='SELECCION'&&<input className="input" placeholder="Identificaciones separadas por coma" value={ids} onChange={e=>cambio(()=>setIds(e.target.value))}/>}
 <div className="flex gap-2"><select className="input" aria-label="Clasificación masiva" value={tipo} onChange={e=>cambio(()=>setTipo(e.target.value))}>{['IVA','INC','EXENTO','EXCLUIDO','NO_APLICA','SIN_CONFIGURAR'].map(t=><option key={t}>{t}</option>)}</select><input className="input" aria-label="Tarifa masiva" type="number" min="0" max="100" step="0.01" disabled={!['IVA','INC'].includes(tipo)} value={tarifa} onChange={e=>cambio(()=>setTarifa(e.target.value))}/></div>
 <label className="flex gap-2"><input type="checkbox" checked={solo} onChange={e=>cambio(()=>setSolo(e.target.checked))}/>Solo productos sin configurar</label>
 <label className="flex gap-2"><input type="checkbox" checked={excepciones} onChange={e=>cambio(()=>setExcepciones(e.target.checked))}/>Reemplazar también excepciones individuales</label>
 <button type="button" disabled={ocupado} className="rounded border p-2" onClick={()=>ejecutar(false)}>Ver productos afectados</button>
 {vista&&<div className="space-y-2"><p>{vista.cantidad} productos afectados. Muestra de hasta 20:</p><div className="overflow-auto"><table className="text-sm w-full"><thead><tr><th>Producto</th><th>Impuesto anterior</th><th>Total incluido</th><th>Total adicional</th></tr></thead><tbody>{vista.ejemplos.map(e=><tr key={e.id}><td>{e.nombre}</td><td>{e.tipoAnterior} {e.tarifaAnterior}%</td><td>{e.totalIncluido.toLocaleString('es-CO')}</td><td>{e.totalAdicional.toLocaleString('es-CO')}</td></tr>)}</tbody></table></div><button type="button" disabled={ocupado||!vista.cantidad} className="rounded bg-slate-800 p-2 text-white" onClick={()=>ejecutar(true)}>Aplicar a estos productos</button></div>}
 <div className="border-t pt-3 space-y-2"><p className="font-medium">Regla para nuevos productos de la categoría seleccionada</p><select aria-label="Categoría superior" className="input" value={padre} onChange={e=>setPadre(e.target.value)}><option value="">Sin categoría superior</option>{categorias.filter(c=>c.id!==Number(categoria)).map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select><button type="button" disabled={ocupado||!categoria} className="rounded border p-2" onClick={regla}>Guardar jerarquía y regla</button></div>
 {mensaje&&<p role="status">{mensaje}</p>}</section>;
}
