import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {apiClient} from '@/api/client';
import {useCajaAbierta} from '@/hooks/usePos';
import {usePosStore} from '@/stores/posStore';
import {getApiErrorMessage} from '@/api/errors';
interface Traslado {id:number;monto:number;cuenta_destino:string;referencia:string;fecha:string;responsable:string}
export default function TrasladosBanco(){const sucursal=usePosStore(s=>s.sucursalId);const {data:caja}=useCajaAbierta(sucursal);const qc=useQueryClient();const [monto,setMonto]=useState(''),[destino,setDestino]=useState(''),[referencia,setReferencia]=useState(''),[mensaje,setMensaje]=useState(''),[ocupado,setOcupado]=useState(false);
 const {data}=useQuery({queryKey:['sicom-traslados'],queryFn:async()=>(await apiClient.get<Traslado[]>('/sicom/traslados')).data});
 async function guardar(e:React.FormEvent){e.preventDefault();if(!caja||ocupado)return;setOcupado(true);try{await apiClient.post('/sicom/traslados',{cajaSesionId:caja.id,monto:Number(monto),cuentaDestino:destino,referencia});setMonto('');setReferencia('');setMensaje('Traslado registrado');await qc.invalidateQueries({queryKey:['sicom-traslados']});await qc.invalidateQueries({queryKey:['caja-movimientos']});}catch(e){setMensaje(getApiErrorMessage(e,'No se pudo registrar'));}finally{setOcupado(false);}}
 return <section className="rounded-xl bg-white border p-5"><h2 className="font-semibold text-lg">Traslado de efectivo a banco</h2><p className="text-sm text-slate-500 mb-4">Registra una consignación realizada. Esta acción registra el movimiento en SICOM.</p><form onSubmit={guardar} className="grid sm:grid-cols-4 gap-3"><label>Monto<input className="input" required type="number" min="0.01" step="0.01" value={monto} onChange={e=>setMonto(e.target.value)}/></label><label>Banco y cuenta destino<input className="input" required maxLength={150} value={destino} onChange={e=>setDestino(e.target.value)}/></label><label>Referencia<input className="input" maxLength={150} value={referencia} onChange={e=>setReferencia(e.target.value)}/></label><button disabled={!caja||ocupado} className="rounded bg-slate-800 text-white disabled:opacity-50">Registrar traslado</button></form>{!caja&&<p>Abre una caja para trasladar efectivo.</p>}{mensaje&&<p role="status" className="my-3">{mensaje}</p>}<div className="overflow-auto mt-5"><table className="w-full text-sm"><thead><tr><th>Fecha</th><th>Destino</th><th>Monto</th><th>Responsable</th><th>Referencia</th></tr></thead><tbody>{data?.map(t=><tr key={t.id}><td>{new Date(t.fecha).toLocaleString('es-CO')}</td><td>{t.cuenta_destino}</td><td>${Number(t.monto).toLocaleString('es-CO')}</td><td>{t.responsable}</td><td>{t.referencia}</td></tr>)}</tbody></table></div></section>;
}
