import {useState} from 'react';
import {useLocation} from 'react-router-dom';
import {useGuia,coincide,abrirTutorial} from '@/features/tutorial/guia';
import {getApiErrorMessage} from '@/api/errors';
import {useRegistrarConsultaSinRespuesta} from '@/hooks/useAyuda';
export default function GuiaAyuda(){const q=useGuia(),loc=useLocation(),registrar=useRegistrarConsultaSinRespuesta();const [buscar,setBuscar]=useState(''),[modulo,setModulo]=useState('actual'),[seleccion,setSeleccion]=useState(''),[enviada,setEnviada]=useState(false),[error,setError]=useState('');
 const actuales=(q.data?.modulos??[]).filter(m=>m.ruta.split('?')[0]===loc.pathname);const filtro=modulo==='actual'?(actuales.length?actuales.map(m=>m.id):[]):modulo?[modulo]:[];
 const resultados=(q.data?.modulos??[]).filter(m=>!filtro.length||filtro.includes(m.id)).flatMap(m=>m.pasos.map(p=>({modulo:m,paso:p}))).filter(x=>coincide(x.modulo.nombre+' '+x.paso.boton+' '+x.paso.explicacion,buscar));const elegido=resultados.find(x=>x.paso.id===seleccion);
 async function avisar(){if(registrar.isPending||enviada)return;setError('');try{await registrar.mutateAsync({rutaResumen:'Guía de uso · '+loc.pathname,comentarioAdicional:buscar});setEnviada(true);}catch(e){setError(getApiErrorMessage(e,'No se pudo registrar la pregunta. Intenta de nuevo.'));}}
 return <div className="space-y-3"><p className="text-xs text-ink-500">Explicaciones preparadas de SICOM. No consulta saldos ni ejecuta acciones del negocio.</p><input aria-label="Buscar pregunta de ayuda" className="input" placeholder="¿Cómo pagar una cuota, crear una cita…?" value={buscar} onChange={e=>{setBuscar(e.target.value);setSeleccion('');setEnviada(false);}} maxLength={500}/><select aria-label="Módulo de ayuda" className="input" value={modulo} onChange={e=>{setModulo(e.target.value);setSeleccion('');}}><option value="actual">Este módulo</option><option value="">Todos mis módulos</option>{q.data?.modulos.map(m=><option key={m.id} value={m.id}>{m.nombre}</option>)}</select>
 {q.isLoading&&<p className="text-sm">Cargando guía…</p>}{q.error&&<p role="alert" className="text-sm text-red-700">{getApiErrorMessage(q.error,'No se pudo cargar la guía. Puedes consultar las preguntas configuradas.')}</p>}
 {elegido?<div className="rounded-lg border bg-ink-50 p-3"><button onClick={()=>setSeleccion('')} className="mb-2 text-xs underline">Volver a preguntas</button><p className="text-xs text-ink-400">{elegido.modulo.nombre}</p><h3 className="mt-1 text-sm font-semibold">{elegido.paso.titulo}</h3><p className="mt-2 text-sm leading-relaxed">{elegido.paso.explicacion}</p><button className="mt-3 rounded border bg-white px-3 py-2 text-xs" onClick={()=>abrirTutorial(elegido.modulo.id,elegido.paso.id)}>Mostrar este paso en el tutorial</button></div>:<div className="max-h-64 space-y-2 overflow-y-auto">{resultados.map(x=><button key={x.paso.id} onClick={()=>setSeleccion(x.paso.id)} className="block w-full rounded-lg border px-3 py-2 text-left text-sm hover:bg-ink-50"><span className="block text-xs text-ink-400">{x.modulo.nombre}</span>{x.paso.titulo}</button>)}</div>}
 {!q.isLoading&&!q.error&&!resultados.length&&<p className="text-sm">No hay una respuesta preparada que coincida. Prueba otra palabra o selecciona Todos mis módulos.</p>}
 <button className="rounded border px-3 py-2 text-xs" onClick={()=>abrirTutorial()}>Abrir tutorial completo</button>
 {buscar.trim().length>=5&&<div className="border-t pt-3"><p className="mb-2 text-xs text-ink-500">Si no resuelve tu duda, puedes registrar esta pregunta para revisión del superadministrador. Se enviará el texto que escribiste; no saldos ni datos automáticos.</p>{enviada?<p role="status" className="text-xs text-green-700">Pregunta registrada para revisión.</p>:<button disabled={registrar.isPending} className="rounded bg-ink-800 px-3 py-2 text-xs text-white disabled:opacity-40" onClick={avisar}>{registrar.isPending?'Registrando…':'Registrar esta pregunta'}</button>}{error&&<p role="alert" className="mt-2 text-xs text-red-700">{error}</p>}</div>}
 </div>;
}
