import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {Search} from 'lucide-react';
import {apiClient} from '@/api/client';
import {getApiErrorMessage} from '@/api/errors';
import {useAuthStore} from '@/stores/authStore';
import {Modal} from '@/components/ui/Modal';
export default function BuscadorGeneral(){const a=useAuthStore();const [open,setOpen]=useState(false),[texto,setTexto]=useState(''),[busqueda,setBusqueda]=useState('');const q=useQuery({queryKey:['busqueda-general',a.empresaId,a.usuarioId,a.permisos.join('|'),busqueda],queryFn:async()=>(await apiClient.get<{id:number;tipo:string;titulo:string;detalle:string;ruta:string}[]>('/ayuda/buscar',{params:{q:busqueda}})).data,enabled:open&&busqueda.length>=2,retry:false});return <><button aria-label="Abrir buscador general" title="Buscar en SICOM" className="rounded-lg border px-2 py-1.5 text-sm text-ink-600" onClick={()=>setOpen(true)}><Search size={16}/></button><Modal isOpen={open} title="Buscar en SICOM" size="lg" onClose={()=>setOpen(false)}><div className="space-y-3"><form className="flex gap-2" onSubmit={e=>{e.preventDefault();setBusqueda(texto.trim());}}><input aria-label="Buscar en todo SICOM" autoFocus required minLength={2} maxLength={80} className="input min-w-0 flex-1" placeholder="Nombre, documento, código o código de barras" value={texto} onChange={e=>setTexto(e.target.value)}/><button className="rounded bg-ink-800 px-3 py-2 text-sm text-white">Buscar</button></form><p className="text-xs text-ink-500">Empresa: {a.nombreEmpresa}. Hasta 15 coincidencias por tipo, según tus permisos y plan. Abrir un resultado no registra una operación.</p>{!busqueda&&<p className="text-sm text-ink-400">Escribe al menos dos caracteres y pulsa Buscar.</p>}{q.isFetching&&<p className="text-sm">Buscando…</p>}{q.error&&<p role="alert" className="text-sm text-red-700">{getApiErrorMessage(q.error,'No se pudo realizar la búsqueda. Intenta de nuevo.')}</p>}{!q.isFetching&&!q.error&&q.data?.length===0&&<p className="text-sm">No hay coincidencias en los módulos que puedes consultar.</p>}<div className="max-h-[50vh] space-y-2 overflow-y-auto">{!q.isFetching&&!q.error&&q.data?.map(r=><Link key={r.tipo+'-'+r.id} to={r.ruta} onClick={()=>setOpen(false)} className="block rounded-lg border p-3 hover:bg-ink-50"><span className="text-xs text-ink-400">{r.tipo} #{r.id}</span><p className="text-sm font-semibold">{r.titulo}</p><p className="text-xs text-ink-500">{r.detalle}</p><span className="text-xs underline">Abrir módulo</span></Link>)}</div></div></Modal></>;}
