import {useState} from 'react';
import {Tabla} from '@/components/ui/FormularioOperacion';
import {dinero,importe,fecha,leerImporte,legible} from './formatoPrestamos';
import type {Fila} from './formatoPrestamos';
import {getApiErrorMessage} from '@/api/errors';
type Pago={tipo:string;cuotaNumero:number|null;monto:number;metodo:string;referencia:string|null;excedenteSiguientes:boolean};
export function CobroPrestamo({cuotas,saldo,busy,previsualizar,registrar}:{cuotas:Fila[];saldo:number;busy:boolean;previsualizar:(p:Pago)=>Promise<Fila>;registrar:(p:Pago)=>Promise<void>}){
 const pendientes=cuotas.filter(q=>Number(q.saldo)>0),primera=pendientes[0];
 const [tipo,setTipo]=useState('CUOTAS'),[numero,setNumero]=useState(String(primera?.numero_cuota??'')),[valor,setValor]=useState(importe(primera?.saldo??0)),[medio,setMedio]=useState('EFECTIVO'),[referencia,setReferencia]=useState(''),[siguientes,setSiguientes]=useState(false),[vista,setVista]=useState<Fila|null>(null),[error,setError]=useState(''),[cargando,setCargando]=useState(false);
 const q=cuotas.find(c=>String(c.numero_cuota)===numero),debe=tipo==='CANCELACION'?saldo:Number(q?.saldo??0),monto=leerImporte(valor),pagado=Number(q?.capital_pagado??0)+Number(q?.interes_pagado??0)+Number(q?.mora_pagada??0);
 const cambiar=(f:()=>void)=>{f();setVista(null);setError('');};
 const payload=():Pago=>{if(!Number.isFinite(monto)||monto<=0)throw new Error('Escribe un importe positivo. Ejemplo: 106.410,25');if(tipo==='CUOTAS'&&!numero)throw new Error('Selecciona la cuota');if(tipo==='CUOTAS'&&monto>debe&&!siguientes)throw new Error('Elige aplicar el excedente a las siguientes cuotas o corrige el importe');if(medio==='TRANSFERENCIA'&&!referencia.trim())throw new Error('Indica banco y referencia');return {tipo,cuotaNumero:tipo==='CUOTAS'?Number(numero):null,monto,metodo:medio,referencia:referencia||null,excedenteSiguientes:tipo==='CUOTAS'&&siguientes};};
 return <form className="rounded border p-4 space-y-3" onSubmit={async e=>{e.preventDefault();if(!vista)return;try{await registrar(payload());}catch(e){setError(getApiErrorMessage(e,'No se pudo registrar'));}}}><h3 className="font-semibold">Registrar pago del cliente</h3><div className="grid gap-3 md:grid-cols-3"><label className="text-sm">Qué quiere pagar<select className="block w-full rounded border p-2" value={tipo} onChange={e=>cambiar(()=>{setTipo(e.target.value);setValor(importe(e.target.value==='CANCELACION'?saldo:q?.saldo));setSiguientes(false);})}><option value="CUOTAS">Una cuota o parte de ella</option><option value="CANCELACION">Cancelar todo el préstamo hoy</option></select></label>
 {tipo==='CUOTAS'&&<label className="text-sm">Número de cuota<select required className="block w-full rounded border p-2" value={numero} onChange={e=>cambiar(()=>{setNumero(e.target.value);setValor(importe(cuotas.find(c=>String(c.numero_cuota)===e.target.value)?.saldo));setSiguientes(false);})}>{pendientes.map(c=><option key={String(c.id)} value={String(c.numero_cuota)}>Cuota {String(c.numero_cuota)} · {fecha(c.fecha_vencimiento)} · {dinero(c.saldo)}</option>)}</select></label>}
 <label className="text-sm">Cuánto paga el cliente ($)<input required inputMode="decimal" className="block w-full rounded border p-2" value={valor} onChange={e=>cambiar(()=>setValor(e.target.value))} placeholder="106.410,25" onBlur={()=>{if(Number.isFinite(monto))setValor(importe(monto));}}/></label><label className="text-sm">Medio de pago<select className="block w-full rounded border p-2" value={medio} onChange={e=>cambiar(()=>setMedio(e.target.value))}><option value="EFECTIVO">Efectivo</option><option value="TRANSFERENCIA">Transferencia</option></select></label>{medio==='TRANSFERENCIA'&&<label className="text-sm">Banco y referencia del ingreso<input required className="block w-full rounded border p-2" value={referencia} onChange={e=>cambiar(()=>setReferencia(e.target.value))}/></label>}</div>
 <p className="text-sm">{tipo==='CUOTAS'?<>Valor pactado de cuota {numero}: <strong>{dinero(q?.monto_cuota)}</strong> · Abonado: {dinero(pagado)} · Mora pendiente: {dinero(q?.moraPendiente)}<br/>Pendiente exacto de esta cuota: <strong>{dinero(debe)}</strong></>:<>Saldo exacto para cerrar hoy: <strong>{dinero(debe)}</strong>. Se elimina el interés futuro pendiente.</>}</p>
 {tipo==='CUOTAS'&&pendientes.some(c=>Number(c.numero_cuota)<Number(numero))&&<p className="text-sm text-amber-700">Hay cuotas anteriores pendientes. Este pago se aplicará a la cuota seleccionada.</p>}
 {tipo==='CUOTAS'&&Number.isFinite(monto)&&monto>debe&&<label className="block text-sm"><input type="checkbox" checked={siguientes} onChange={e=>cambiar(()=>setSiguientes(e.target.checked))}/> Aplicar excedente de {dinero(monto-debe)} a las cuotas siguientes. Revisa la distribución antes de guardar.</label>}
 {Number.isFinite(monto)&&monto>0&&monto<=debe&&<p className="text-sm">Después de este pago quedará pendiente: <strong>{dinero(debe-monto)}</strong>.</p>}
 {error&&<p role="alert" className="text-red-700">{error}</p>}
 <button type="button" className="rounded border px-4 py-2 disabled:opacity-50" disabled={busy||cargando} onClick={async()=>{setCargando(true);setError('');try{setVista(await previsualizar(payload()));}catch(e){setError(getApiErrorMessage(e,'No se pudo revisar el pago'));}finally{setCargando(false);}}}>Revisar pago</button>
 {vista&&<div className="space-y-3"><p>Recibido: <strong>{dinero(vista.monto)}</strong>. Comprueba la aplicación:</p><Tabla rows={legible(vista.aplicaciones as Fila[])} cols={ [['numero','Cuota'],['capital','Capital'],['interes','Interés'],['mora','Mora']] }/><button disabled={busy} className="rounded bg-ink-800 px-4 py-2 text-white disabled:opacity-50">Confirmar y registrar pago</button></div>}
 </form>;
}
