import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {apiClient} from '@/api/client';
import {getApiErrorMessage} from '@/api/errors';
import {useAuthStore} from '@/stores/authStore';
import {Formulario,Tabla as TablaBase} from '@/components/ui/FormularioOperacion';
import {dinero,legible,fecha} from './formatoPrestamos';
import type {Fila} from './formatoPrestamos';
import type {ComponentProps} from 'react';
const Tabla=(props:ComponentProps<typeof TablaBase>)=><TablaBase {...props} rows={legible(props.rows)} acciones={props.acciones?r=>props.acciones!((r.__original as Record<string,unknown>)??r):undefined}/>;
const path='/prestamos/cobranza';
const hoy=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bogota',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const filas=(v:unknown)=>Array.isArray(v)?v as Fila[]:[];
type Props={tipo:string;sucursal:string;cajaId?:number;contratos:Fila[];busy:boolean;ejecutar:(f:()=>Promise<unknown>,texto?:string)=>Promise<void>};
export function CobranzaPrestamos({tipo,sucursal,cajaId,contratos,busy,ejecutar}:Props){
 const auth=useAuthStore(),qc=useQueryClient();const puede=(p:string)=>auth.esSuperadmin||auth.esAdministradorTotal||auth.permisos.includes(p);
 const [contrato,setContrato]=useState(''),[rutaId,setRutaId]=useState(''),[visitas,setVisitas]=useState<Fila[]>([]),[desde,setDesde]=useState(hoy().slice(0,8)+'01'),[hasta,setHasta]=useState(hoy());
 const consulta=(nombre:string,enabled=true,params?:Record<string,string>)=>useQuery({queryKey:['prestamos-cobranza',nombre,params],queryFn:async()=>(await apiClient.get(`${path}/${nombre}`,{params})).data,enabled});
 const empleados=consulta('empleados',tipo!=='control');const agenda=consulta('agenda',tipo==='cobranza'&&puede('PRESTAMOS_COBRANZA'));const promesas=consulta('promesas',tipo==='cobranza'&&puede('PRESTAMOS_COBRANZA'));const rutas=consulta('rutas',tipo==='rutas'&&(puede('PRESTAMOS_RUTAS')||puede('PRESTAMOS_COBRAR_RUTA')));const ruta=consulta(`rutas/${rutaId}`,tipo==='rutas'&&!!rutaId);const reversos=consulta('reversiones',tipo==='control'&&(puede('PRESTAMOS_AUTORIZAR_REVERSO')||puede('PRESTAMOS_SOLICITAR_REVERSO')));const alertas=consulta('alertas',tipo==='control'&&puede('PRESTAMOS_REPORTES'));const rentabilidad=consulta('rentabilidad',tipo==='control'&&puede('PRESTAMOS_REPORTES'),{desde,hasta});
 const detalle=useQuery({queryKey:['prestamos-cobranza','cuotas',contrato],queryFn:async()=>(await apiClient.get(`/prestamos/operacion/${contrato}`)).data,enabled:!!contrato&&tipo!=='control'});
 const cuotas=filas(detalle.data?.cuotas).filter(q=>Number(q.saldo)>0),opcionesCuotas=cuotas.map(q=>({id:String(q.numero_cuota),nombre:`Cuota ${q.numero_cuota} · ${fecha(q.fecha_vencimiento)} · ${dinero(q.saldo)}`}));
 const clave=(tipo:string,r:Record<string,string>)=>{const k='prestamos6:'+tipo,datos=JSON.stringify(r),anterior=JSON.parse(sessionStorage.getItem(k)||'null');if(anterior?.datos===datos)return anterior.clave as string;const v={datos,clave:crypto.randomUUID()};sessionStorage.setItem(k,JSON.stringify(v));return v.clave;};
 const guardar=async(url:string,r:unknown,mensaje='Registro guardado')=>ejecutar(async()=>{await apiClient.post(`${path}/${url}`,r);const k=url==='recogidas'?'recogida':url==='costos'?'costo':null;if(k)sessionStorage.removeItem('prestamos6:'+k);await qc.invalidateQueries({queryKey:['prestamos-cobranza']});},mensaje);
 const accion=(texto:string,f:()=>Promise<unknown>)=><button disabled={busy} className="m-1 rounded border px-3 py-2 disabled:opacity-50" onClick={()=>ejecutar(async()=>{await f();await qc.invalidateQueries({queryKey:['prestamos-cobranza']});})}>{texto}</button>;
 const nota=(texto:string)=>{const v=window.prompt(texto);if(!v?.trim())throw new Error('Escribe el motivo o resultado');return v;};
 const errores=[agenda,promesas,rutas,ruta,reversos,alertas,rentabilidad,detalle].filter(q=>q.isError);
 return <div className="space-y-4">{errores.map((q,i)=><p key={i} role="alert" className="rounded bg-red-50 p-3 text-red-700">{getApiErrorMessage(q.error,'No se pudo consultar')}</p>)}
 {tipo==='cobranza'&&puede('PRESTAMOS_COBRANZA')&&<><label className="block text-sm">Contrato para seguimiento o promesa<select className="ml-2 rounded border p-2" value={contrato} onChange={e=>setContrato(e.target.value)}><option value="">Seleccionar</option>{contratos.map(c=><option key={String(c.id)} value={String(c.id)}>#{String(c.id)} · {String(c.cliente)} · {String(c.estado)}</option>)}</select></label>
 {contrato&&<><Formulario key={`agenda-${contrato}`} busy={busy} titulo="Agendar seguimiento" campos={[{nombre:'responsableId',titulo:'Empleado responsable',opciones:filas(empleados.data).map(e=>({id:String(e.id),nombre:String(e.nombre)})),valor:String(auth.usuarioId??'')},{nombre:'fechaCita',titulo:'Fecha y hora (Colombia)',tipo:'datetime-local'},{nombre:'canal',titulo:'Cómo se hará el seguimiento',opciones:['LLAMADA','VISITA','MENSAJE','OTRO'].map(c=>({id:c,nombre:c}))},{nombre:'nota',titulo:'Qué se debe revisar'}]} enviar={async r=>guardar('agenda',{...r,prestamoId:Number(contrato),responsableId:Number(r.responsableId),fechaCita:r.fechaCita+':00-05:00'})}/><p className="text-sm">La agenda registra tareas internas. No envía mensajes ni llamadas automáticamente.</p>
 {opcionesCuotas.length>0&&<Formulario key={`promesa-${contrato}`} busy={busy} titulo="Registrar promesa del cliente" campos={[{nombre:'cuotaNumero',titulo:'Cuota que promete pagar',opciones:opcionesCuotas},{nombre:'monto',titulo:'Cuánto promete pagar ($)',tipo:'moneda'},{nombre:'vence',titulo:'Fecha prometida',tipo:'date',valor:hoy()},{nombre:'nota',titulo:'Acuerdo y observaciones'}]} enviar={async r=>guardar('promesas',{...r,prestamoId:Number(contrato),cuotaNumero:Number(r.cuotaNumero),monto:Number(r.monto)})}/>}</>}
 <h3 className="font-semibold">Agenda de seguimiento</h3><Tabla rows={filas(agenda.data)} cols={ [['prestamo_id','Contrato'],['cliente','Cliente'],['fecha_cita','Fecha y hora'],['responsable','Responsable'],['canal','Canal'],['nota','Tarea'],['estado','Estado'],['resultado','Resultado']] } acciones={r=>r.estado==='PENDIENTE'&&<>{accion('Realizado',()=>apiClient.post(`${path}/agenda/${r.id}/resolver`,{estado:'REALIZADO',resultado:nota('Resultado del seguimiento')}))}{accion('Cancelar',()=>apiClient.post(`${path}/agenda/${r.id}/resolver`,{estado:'CANCELADO',resultado:nota('Motivo de cancelación')}))}</>}/>
 <h3 className="font-semibold">Promesas de pago</h3><p className="text-sm">Cumplida exige pagos reales aplicados a esa cuota desde que se registró la promesa. Una promesa no reduce la deuda.</p><Tabla rows={filas(promesas.data)} cols={ [['prestamo_id','Contrato'],['cliente','Cliente'],['cuota_numero','Cuota'],['monto','Prometido'],['vence','Fecha'],['situacion','Situación'],['nota','Acuerdo'],['resultado','Resultado']] } acciones={r=>r.estado==='VIGENTE'&&<>{accion('Verificar cumplimiento',()=>apiClient.post(`${path}/promesas/${r.id}/resolver`,{estado:'CUMPLIDA',resultado:nota('Constancia de cumplimiento')}))}{accion('Cancelar promesa',()=>apiClient.post(`${path}/promesas/${r.id}/resolver`,{estado:'CANCELADA',resultado:nota('Motivo de cancelación')}))}</>}/></>}
 {tipo==='rutas'&&<><p className="text-sm">El cobrador registra dinero recogido. El supervisor confirma la entrega de efectivo o verifica el ingreso bancario; entonces se aplica a la cuota y se genera el comprobante. Mientras esté por entregar, se bloquean otros pagos directos de ese contrato para evitar duplicar el cobro.</p>
 {puede('PRESTAMOS_RUTAS')&&<details className="rounded border p-3"><summary className="cursor-pointer font-semibold">Crear ruta de cobro</summary><div className="space-y-3 mt-3"><label className="text-sm">Contrato<select className="block rounded border p-2" value={contrato} onChange={e=>setContrato(e.target.value)}><option value="">Seleccionar</option>{contratos.filter(c=>['ACTIVO','EN_MORA'].includes(String(c.estado))&&String(c.sucursal_id)===sucursal).map(c=><option key={String(c.id)} value={String(c.id)}>#{String(c.id)} · {String(c.cliente)}</option>)}</select></label>
 {contrato&&<Formulario key={`visita-${contrato}-${visitas.length}`} busy={busy} titulo="Añadir visita" campos={[{nombre:'cuotaNumero',titulo:'Cuota',opciones:opcionesCuotas},{nombre:'orden',titulo:'Orden de visita',tipo:'number',valor:String(visitas.length+1)},{nombre:'direccion',titulo:'Dirección e indicaciones'}]} enviar={async r=>{setVisitas(v=>[...v,{prestamoId:Number(contrato),cliente:contratos.find(c=>String(c.id)===contrato)?.cliente,cuotaNumero:Number(r.cuotaNumero),orden:Number(r.orden),direccion:r.direccion}]);}}/>}
 <Tabla rows={visitas} cols={ [['orden','Orden'],['prestamoId','Contrato'],['cliente','Cliente'],['cuotaNumero','Cuota'],['direccion','Dirección']] } acciones={r=><button className="rounded border p-2" onClick={()=>setVisitas(v=>v.filter(c=>c!==r))}>Quitar</button>}/>
 <Formulario busy={busy} titulo="Guardar ruta con estas visitas" campos={[{nombre:'nombre',titulo:'Nombre de ruta'},{nombre:'fecha',titulo:'Día de ruta',tipo:'date',valor:hoy()},{nombre:'cobradorId',titulo:'Cobrador asignado',opciones:filas(empleados.data).map(e=>({id:String(e.id),nombre:String(e.nombre)}))}]} enviar={async r=>guardar('rutas',{...r,sucursalId:Number(sucursal),cobradorId:Number(r.cobradorId),visitas:visitas.map(({cliente,...v})=>v)})}/></div></details>}
 <Tabla rows={filas(rutas.data)} cols={ [['id','Ruta'],['nombre','Nombre'],['fecha_ruta','Día'],['cobrador','Cobrador'],['sucursal','Sucursal'],['por_entregar','Por entregar'],['estado','Estado']] } acciones={r=><button className="rounded border p-2" onClick={()=>setRutaId(String(r.id))}>Abrir</button>}/>
 {ruta.data&&<section className="rounded border p-4 space-y-4"><h3 className="font-semibold">Ruta #{rutaId} · {String(ruta.data.nombre)} · {String(ruta.data.estado)}</h3><Tabla rows={filas(ruta.data.visitas)} cols={ [['orden','Orden'],['prestamo_id','Contrato'],['cliente','Cliente'],['cuota_numero','Cuota'],['pendiente','Pendiente'],['direccion','Dirección'],['estado','Visita'],['resultado','Resultado']] } acciones={r=>ruta.data.estado==='ABIERTA'&&r.estado==='PENDIENTE'&&<>{accion('Visitado sin pago',()=>apiClient.post(`${path}/visitas/${r.id}/resolver`,{estado:'VISITADO',resultado:nota('Resultado de visita')}))}{accion('No localizado',()=>apiClient.post(`${path}/visitas/${r.id}/resolver`,{estado:'NO_LOCALIZADO',resultado:nota('Resultado e indicaciones')}))}{accion('Cancelar visita',()=>apiClient.post(`${path}/visitas/${r.id}/resolver`,{estado:'CANCELADO',resultado:nota('Motivo de cancelación')}))}</>}/>
 {ruta.data.estado==='ABIERTA'&&Number(ruta.data.cobrador_id)===auth.usuarioId&&puede('PRESTAMOS_COBRAR_RUTA')&&<Formulario key={`recogida-${rutaId}`} busy={busy} titulo="Registrar dinero recogido (todavía no entregado)" campos={[{nombre:'visitaId',titulo:'Visita y cuota',opciones:filas(ruta.data.visitas).filter(v=>['PENDIENTE','VISITADO'].includes(String(v.estado))&&Number(v.pendiente)>0).map(v=>({id:String(v.id),nombre:`${v.cliente} · Cuota ${v.cuota_numero} · ${dinero(v.pendiente)}`}))},{nombre:'monto',titulo:'Cuánto entregó el cliente ($)',tipo:'moneda'},{nombre:'metodo',titulo:'Medio',opciones:[{id:'EFECTIVO',nombre:'Efectivo'},{id:'TRANSFERENCIA',nombre:'Transferencia'}]},{nombre:'referencia',titulo:'Referencia / banco (obligatorio para transferencia)',opcional:true}]} enviar={async r=>guardar('recogidas',{...r,clave:clave('recogida',r),visitaId:Number(r.visitaId),monto:Number(r.monto)},'Dinero recogido registrado. Falta entrega y conciliación.')}/>}
 <h3 className="font-semibold">Control del dinero del cobrador</h3><Tabla rows={filas(ruta.data.recaudos)} cols={ [['id','Recogida'],['prestamo_id','Contrato'],['cuota_numero','Cuota'],['fecha','Recogido'],['metodo','Medio'],['monto','Importe'],['estado','Estado'],['pago_id','Comprobante'],['motivo_devolucion','Devolución']] } acciones={r=>r.estado==='POR_ENTREGAR'&&puede('PRESTAMOS_RUTAS')&&<>{accion('Confirmar entrega / banco',()=>{if(!window.confirm(`Confirma que recibiste o verificaste ${dinero(r.monto)}. Se aplicará a la cuota.`))return Promise.resolve();const referencia=r.metodo==='TRANSFERENCIA'?nota('Banco y referencia verificada del ingreso'):null;return apiClient.post(`${path}/recogidas/${r.id}/conciliar`,{cajaId,referencia});})}{accion('Documentar devolución',()=>apiClient.post(`${path}/recogidas/${r.id}/devolver`,{motivo:nota('Constancia de devolución real al cliente, fecha y responsable')}))}</>}/>
 {ruta.data.estado==='ABIERTA'&&puede('PRESTAMOS_RUTAS')&&accion('Cerrar ruta',()=>apiClient.post(`${path}/rutas/${rutaId}/cerrar`))}</section>}</>}
 {tipo==='control'&&<><h3 className="font-semibold">Reversiones con autorización</h3><p className="text-sm">La solicita un usuario y la autoriza otro con permiso. Se conserva el pago original y se registra devolución de dinero. Si hay pagos posteriores, deben revertirse primero. No se revierten históricos ni cadenas refinanciadas desde aquí.</p><Tabla rows={filas(reversos.data)} cols={ [['id','Solicitud'],['pago_id','Pago'],['prestamo_id','Contrato'],['monto','Importe'],['metodo','Medio'],['solicitante','Solicitante'],['motivo','Motivo'],['estado','Estado'],['autorizador','Autorizador'],['respuesta','Respuesta']] } acciones={r=>r.estado==='PENDIENTE'&&puede('PRESTAMOS_AUTORIZAR_REVERSO')&&Number(r.solicitado_por)!==auth.usuarioId&&<>{accion('Autorizar y devolver',()=>{if(!window.confirm(`Se devolverán ${dinero(r.monto)} y se reabrirá el saldo. Confirma la operación real.`))return Promise.resolve();return apiClient.post(`${path}/reversiones/${r.id}/resolver`,{autorizar:true,cajaId,referencia:r.metodo==='TRANSFERENCIA'?nota('Banco y referencia de devolución'):null,respuesta:nota('Motivo de autorización y constancia de devolución')});})}{accion('Rechazar',()=>apiClient.post(`${path}/reversiones/${r.id}/resolver`,{autorizar:false,respuesta:nota('Motivo de rechazo')}))}</>}/>
 {puede('PRESTAMOS_REPORTES')&&<><h3 className="font-semibold">Alertas e inconsistencias</h3><Tabla rows={filas(alertas.data)} cols={ [['tipo','Alerta'],['prestamo_id','Contrato'],['detalle','Qué revisar']] }/>
 <h3 className="font-semibold">Rentabilidad de la cartera</h3><div className="flex flex-wrap gap-3"><label className="text-sm">Desde<input type="date" className="block rounded border p-2" value={desde} onChange={e=>setDesde(e.target.value)}/></label><label className="text-sm">Hasta<input type="date" className="block rounded border p-2" value={hasta} onChange={e=>setHasta(e.target.value)}/></label></div><p className="text-sm">Ingresos cobrados: <strong>{dinero(rentabilidad.data?.ingresos_cobrados)}</strong> · Costos de operación: {dinero(rentabilidad.data?.costos_operacion)} · Costos de financiación: {dinero(rentabilidad.data?.costos_financiacion)} · Resultado: <strong>{dinero(rentabilidad.data?.resultado_neto)}</strong> · Margen: {rentabilidad.data?.margen_porcentaje==null?'Sin ingresos para calcularlo':`${Number(rentabilidad.data.margen_porcentaje).toLocaleString('es-CO')} %`}</p><p className="text-sm">El capital recuperado ({dinero(rentabilidad.data?.capital_recaudado)}) no es ganancia. Se excluyen pagos revertidos, históricos y refinanciación interna. Resultado operativo de cobros menos costos registrados; no es una tasa de retorno ni incluye pérdidas/provisiones sin registrar.</p>
 {puede('PRESTAMOS_COSTOS')&&<details className="rounded border p-3"><summary className="cursor-pointer">Registrar costo soportado</summary><p className="text-sm mt-2">Registra costos ya pagados o contabilizados, con referencia al soporte. No vuelve a sacar dinero de caja ni genera otro asiento.</p><Formulario busy={busy} titulo="Costo de cartera" campos={[{nombre:'prestamoId',titulo:'Contrato (opcional)',opcional:true,opciones:contratos.map(c=>({id:String(c.id),nombre:`#${c.id} · ${c.cliente}`}))},{nombre:'fecha',titulo:'Fecha del costo',tipo:'date',valor:hoy()},{nombre:'tipo',titulo:'Tipo',opciones:[{id:'OPERACION',nombre:'Operación / cobranza'},{id:'FINANCIACION',nombre:'Financiación del capital'}]},{nombre:'monto',titulo:'Importe ($)',tipo:'moneda'},{nombre:'concepto',titulo:'Qué se pagó'},{nombre:'referencia',titulo:'Referencia de comprobante o asiento existente'}]} enviar={async r=>guardar('costos',{...r,clave:clave('costo',r),prestamoId:r.prestamoId?Number(r.prestamoId):null,monto:Number(r.monto)})}/></details>}
 <Tabla rows={filas(rentabilidad.data?.costos)} cols={ [['fecha_costo','Fecha'],['prestamo_id','Contrato'],['tipo','Tipo'],['concepto','Concepto'],['monto','Costo'],['referencia','Soporte']] }/></>}
 </>}
 </div>;
}
