import {usePermisosOperacion} from '@/hooks/usePermisosOperacion';
import {useState} from 'react';import {useQuery,useQueryClient} from '@tanstack/react-query';import {apiClient} from '@/api/client';import {getApiErrorMessage} from '@/api/errors';import {useClientes,useCajaAbierta} from '@/hooks/usePos';import {useSucursales} from '@/hooks/useSucursales';import {Formulario,Tabla as TablaBase} from '@/components/ui/FormularioOperacion';import type {Campo} from '@/components/ui/FormularioOperacion';
import {CobroPrestamo} from './CobroPrestamo';import {CobranzaPrestamos} from './CobranzaPrestamos';import {dinero,legible,importe} from './formatoPrestamos';import type {ComponentProps} from 'react';
const Tabla=(props:ComponentProps<typeof TablaBase>)=><TablaBase {...props} rows={legible(props.rows)} acciones={props.acciones?r=>props.acciones!((r.__original as Record<string,unknown>)??r):undefined}/>;
type Row=Record<string,unknown>;type Plan={capital:number;tasa:number;unidad:string;metodo:string;cuotas:number;frecuencia:string;inicio:string};type Sim={capital:number;intereses:number;total:number;cuotas:Row[];unidadTasa:string;metodo:string;tasaPeriodo:number};
const path='/prestamos/operacion';const rows=(r:unknown)=>Array.isArray(r)?r as Row[]:[];
const hoy=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bogota',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function OperacionPrestamos(){
 const permisos=usePermisosOperacion('PRESTAMOS');const visible=(t:string)=>['simulador','cartera'].includes(t)||(permisos.empresa&&(t==='config'?permisos.administrar:t==='control'?permisos.reportes&&permisos.costos:permisos.administrar));
 const [tab,setTab]=useState('simulador'),[error,setError]=useState(''),[mensaje,setMensaje]=useState(''),[busy,setBusy]=useState(false),[seleccion,setSeleccion]=useState<number|null>(null),[sucursal,setSucursal]=useState(''),[planes,setPlanes]=useState<{plan:Plan;sim:Sim}[]>([]),[elegido,setElegido]=useState(0);
 const {data:clientes}=useClientes(),{data:sucursales}=useSucursales(),{data:caja}=useCajaAbierta(sucursal?Number(sucursal):null);const qc=useQueryClient();const key=['prestamos-operacion'];
 const lista=useQuery({queryKey:[...key,'lista'],queryFn:async()=>(await apiClient.get<Row[]>(path)).data});const detalle=useQuery({queryKey:[...key,'detalle',seleccion],queryFn:async()=>(await apiClient.get<Row>(`${path}/${seleccion}`)).data,enabled:seleccion!=null});const config=useQuery({queryKey:[...key,'config'],queryFn:async()=>(await apiClient.get<Row>(`${path}/config`)).data,enabled:permisos.administrar&&permisos.empresa});const reportes=useQuery({queryKey:[...key,'reportes'],queryFn:async()=>(await apiClient.get<Row>(`${path}/reportes`)).data,enabled:permisos.reportes});const bancos=useQuery({queryKey:[...key,'bancos'],queryFn:async()=>(await apiClient.get<Row[]>(`${path}/bancos`)).data,enabled:tab==='bancos'});
 const d=detalle.data,saldo=d?.saldoHoy as Row|undefined;
 const camposPlan:Campo[]=[{nombre:'capital',titulo:'Capital ($)',tipo:'moneda'},{nombre:'tasa',titulo:'Tasa nominal (%)',tipo:'number'},{nombre:'unidad',titulo:'Unidad explícita',opciones:[{id:'MENSUAL',nombre:'Nominal mensual'},{id:'ANUAL',nombre:'Nominal anual'}]},{nombre:'metodo',titulo:'Método de cálculo',opciones:[{id:'CUOTA_FIJA',nombre:'Cuota fija sobre saldo'},{id:'CAPITAL_CONSTANTE',nombre:'Capital constante sobre saldo'},{id:'FIJO',nombre:'Interés fijo sobre capital inicial'}]},{nombre:'cuotas',titulo:'Número de cuotas',tipo:'number',valor:'12'},{nombre:'frecuencia',titulo:'Frecuencia',opciones:['MENSUAL','QUINCENAL','SEMANAL'].map(v=>({id:v,nombre:v}))},{nombre:'inicio',titulo:'Inicio (primera cuota un período después)',tipo:'date',valor:hoy()}];
 const metodo:Campo={nombre:'metodo',titulo:'Medio de pago',opciones:[{id:'EFECTIVO',nombre:'Efectivo'},{id:'TRANSFERENCIA',nombre:'Transferencia'}]};
 const referencia:Campo={nombre:'referencia',titulo:'Banco / referencia (obligatoria para transferencia)',opcional:true};
 const p=(r:Record<string,string>):Plan=>({capital:Number(r.capital),tasa:Number(r.tasa),unidad:r.unidad,metodo:r.metodo,cuotas:Number(r.cuotas),frecuencia:r.frecuencia,inicio:r.inicio});
 const clave=(tipo:string)=>{let v=sessionStorage.getItem(`prestamos5:${seleccion}:${tipo}`);if(!v){v=crypto.randomUUID();sessionStorage.setItem(`prestamos5:${seleccion}:${tipo}`,v);}return v;};const liberar=(tipo:string)=>sessionStorage.removeItem(`prestamos5:${seleccion}:${tipo}`);
 async function ejecutar(f:()=>Promise<unknown>,texto='Operación registrada'){if(busy)return;setBusy(true);setError('');setMensaje('');try{await f();await qc.invalidateQueries({queryKey:key});setMensaje(texto);}catch(e){setError(getApiErrorMessage(e,'No se pudo registrar'));}finally{setBusy(false);}}
 const post=(url:string,r:unknown={})=>apiClient.post(`${path}${url}`,r);
 const boton=(t:string,f:()=>Promise<unknown>)=><button className="m-1 rounded border px-3 py-2 disabled:opacity-50" disabled={busy} onClick={()=>ejecutar(f)}>{t}</button>;
 async function descargarPdf(url:string,nombre:string){const b=(await apiClient.get(`${path}${url}`,{responseType:'blob'})).data;const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=nombre;a.click();URL.revokeObjectURL(u);}
 function descargar(nombre:string,contenido:unknown){const blob=new Blob([JSON.stringify(contenido,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=nombre;a.click();URL.revokeObjectURL(url);}
 return <div className="space-y-4"><h1 className="text-2xl font-semibold">Préstamos: planes y recaudos</h1><p className="text-sm text-ink-500">Simula y compara antes de aprobar. El desembolso y cada recaudo generan un movimiento real.</p><div className="flex flex-wrap gap-2">{['simulador','cartera','bancos','config','cobranza','rutas','control'].filter(visible).map(t=><button key={t} className={`rounded border p-2 ${tab===t?'bg-ink-800 text-white':''}`} onClick={()=>setTab(t)}>{({simulador:'Simulador y comparador',cartera:'Contratos y cuotas',bancos:'Registro bancario',config:'Límites y reglas',cobranza:'Seguimiento y promesas',rutas:'Rutas y cobradores',control:'Control y rentabilidad'} as Record<string,string>)[t]}</button>)}</div>
 <label className="block text-sm">Sucursal de caja<select className="ml-2 rounded border p-2" value={sucursal} onChange={e=>setSucursal(e.target.value)}><option value="">Seleccionar</option>{sucursales?.map(s=><option key={s.id} value={s.id}>{s.nombre}</option>)}</select><span className="ml-3">{caja?`Caja #${caja.id}`:'Selecciona una sucursal con caja abierta'}</span></label>
 {error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}</p>}{mensaje&&<p className="rounded bg-green-50 p-3 text-green-700">{mensaje}</p>}
 {tab==='simulador'&&<><Formulario busy={busy} titulo="Simular un plan" campos={camposPlan} enviar={async r=>ejecutar(async()=>{const plan=p(r);const sim=(await post('/simular',plan)).data as Sim;setPlanes(a=>[...a.slice(-4),{plan,sim}]);setElegido(Math.min(planes.length,4));})}/><p className="text-sm">Tasas nominales: mensual ×12 para anual; períodos de 12 meses, 24 quincenas o 52 semanas al año. No son tasas efectivas anuales. El interés fijo usa capital inicial; los otros métodos usan saldo.</p>
 {planes.length>0&&<><Tabla rows={planes.map((v,i)=>({id:i+1,metodo:v.plan.metodo,tasa:`${v.plan.tasa}% ${v.plan.unidad}`,capital:dinero(v.sim.capital),intereses:dinero(v.sim.intereses),total:dinero(v.sim.total),cuota:dinero(v.sim.cuotas[0]?.total)}))} cols={ [['id','Plan'],['metodo','Método'],['tasa','Tasa'],['capital','Capital'],['intereses','Intereses'],['total','Total'],['cuota','Primera cuota']] } acciones={r=><button className="rounded border p-2" onClick={()=>setElegido(Number(r.id)-1)}>Elegir</button>}/><h3 className="font-semibold">Plan elegido #{elegido+1}</h3><Tabla rows={planes[elegido]?.sim.cuotas??[]} cols={ [['numero','Cuota'],['vencimiento','Vence'],['capital','Capital'],['interes','Interés'],['total','Total'],['saldoCapital','Capital restante']] }/>
 <Formulario busy={busy} titulo="Guardar solicitud del plan elegido" campos={[{nombre:'clienteId',titulo:'Cliente',opciones:clientes??[]},{nombre:'sucursalId',titulo:'Sucursal',opciones:sucursales??[],valor:sucursal},{nombre:'notas',titulo:'Notas',opcional:true}]} enviar={async r=>ejecutar(async()=>{if(!planes[elegido])throw new Error('Selecciona un plan');const v=(await post('',{clave:clave('solicitud'),clienteId:Number(r.clienteId),sucursalId:Number(r.sucursalId),notas:r.notas||null,plan:planes[elegido].plan})).data;liberar('solicitud');setSeleccion(Number(v.id));setSucursal(r.sucursalId);setTab('cartera');},'Solicitud guardada. Revisa, aprueba y desembolsa.')}/></> }</>}
 {tab==='cartera'&&<><p className="text-sm">Recaudos registrados desde esta entrega; los históricos importados se consultan por contrato.</p>{permisos.reportes&&<p className="text-sm">Capital pendiente {dinero(reportes.data?.capital_pendiente)} · Capital recaudado {dinero(reportes.data?.capital_recaudado)} · Intereses cobrados {dinero(reportes.data?.intereses_cobrados)} · Mora cobrada {dinero(reportes.data?.mora_cobrada)}</p>}<Tabla rows={lista.data??[]} cols={ [['id','Contrato'],['cliente','Cliente'],['estado','Estado'],['monto_principal','Capital'],['tasa','Tasa'],['unidad','Unidad'],['metodo','Método']] } acciones={r=><button className="rounded border p-2" onClick={()=>{setSeleccion(Number(r.id));setSucursal(String(r.sucursal_id));}}>Abrir</button>}/>
 {d&&seleccion&&<section className="rounded border p-4 space-y-4"><h2 className="text-lg font-semibold">Contrato #{seleccion} · {String(d.estado)}</h2><p>Tasa {importe(d.tasa??d.tasa_interes)}% · {String(d.unidad??'TOTAL HISTÓRICO')} · {String(d.metodo??'Pendiente de revisar')} · Mora nominal anual {importe(d.mora_nominal_anual??0)}% · Gracia {String(d.gracia_dias??0)} días</p>
 {!d.metodo&&<><p>Contrato histórico: sus importes no se modifican. Comprueba las cuotas y pagos antes de incorporarlo. La incorporación no mueve dinero ni reconstruye contabilidad.</p><Tabla rows={rows(d.cuotasHistoricas)} cols={ [['numero_cuota','Cuota'],['fecha_vencimiento','Vence'],['monto_cuota','Importe original'],['monto_pagado','Pago registrado'],['estado','Estado']] }/>{boton('Incorporar contrato revisado',async()=>{const motivo=window.prompt('Motivo y constancia de revisión del contrato y sus pagos');if(!motivo)throw new Error('Revisión requerida');return post(`/${seleccion}/incorporar`,{motivo});})}</>}
 {Boolean(d.metodo)&&<><p className="rounded bg-blue-50 p-3">Saldo para cancelar hoy: <strong>{dinero(saldo?.total)}</strong> = capital {dinero(saldo?.capital)} + interés devengado {dinero(saldo?.interesDevengado)} + mora {dinero(saldo?.mora)}. Fecha: {String(saldo?.fecha)}</p><p className="text-sm">La cancelación anticipada elimina el interés futuro no devengado. El interés del período en curso se prorratea por días reales del período.</p>
 {permisos.administrar&&d.estado==='SOLICITADO'&&boton('Aprobar solicitud',()=>post(`/${seleccion}/aprobar`))}
 {permisos.administrar&&d.estado==='APROBADO'&&<Formulario busy={busy} titulo="Desembolsar capital aprobado" campos={[metodo,referencia]} enviar={async r=>ejecutar(()=>post(`/${seleccion}/desembolsar`,{cajaId:caja?.id,metodo:r.metodo,referencia:r.referencia||null}))}/>}
 {permisos.operar&&['ACTIVO','EN_MORA'].includes(String(d.estado))&&<><CobroPrestamo key={`${seleccion}:${JSON.stringify(d.cuotas)}`} cuotas={rows(d.cuotas)} saldo={Number(saldo?.total??0)} busy={busy} previsualizar={async r=>(await post(`/${seleccion}/previsualizar-pago`,r)).data} registrar={async r=>ejecutar(async()=>{await post(`/${seleccion}/pagos`,{...r,clave:clave('pago'),cajaId:caja?.id});liberar('pago');},'Pago registrado con comprobante y aplicación por cuota.')}/>
 {permisos.administrar&&<details className="rounded border"><summary className="cursor-pointer p-3 font-semibold">Refinanciar préstamo</summary><Formulario busy={busy} titulo="Refinanciar conservando el contrato anterior" campos={camposPlan.map(c=>c.nombre==='capital'?{...c,valor:String(saldo?.total??'')}:c).concat([{nombre:'aceptaCapitalizacion',titulo:'Aceptación de capitalizar interés/mora',opciones:[{id:'false',nombre:'No'},{id:'true',nombre:'Sí, acuerdo expreso'}]},{nombre:'motivo',titulo:'Motivo y soporte del acuerdo'}])} enviar={async r=>ejecutar(async()=>{await post(`/${seleccion}/refinanciar`,{clave:clave('refinanciacion'),plan:p(r),aceptaCapitalizacion:r.aceptaCapitalizacion==='true',motivo:r.motivo});liberar('refinanciacion');},'Refinanciación registrada sin entrada/salida ficticia de dinero.')}/></details>}</>}
 <Tabla rows={rows(d.cuotas)} cols={ [['numero_cuota','Cuota'],['fecha_vencimiento','Vence'],['capital','Capital'],['interes','Interés pactado'],['capital_pagado','Capital pagado'],['interes_pagado','Interés pagado'],['interes_condonado','Interés eliminado'],['moraPendiente','Mora pendiente'],['saldo','Saldo'],['estado','Estado']] }/>
 <Tabla rows={rows(d.pagos)} cols={ [['id','Comprobante'],['fecha','Fecha'],['tipo','Tipo'],['metodo','Medio'],['capital','Capital'],['interes','Interés'],['mora','Mora'],['monto','Total'],['estado_pago','Estado']] } acciones={r=><>{boton('Descargar',async()=>{await descargarPdf(`/pagos/${r.id}/pdf`,`comprobante-prestamo-${seleccion}-${r.id}.pdf`);})}{r.estado_pago!=='REVERTIDO'&&['EFECTIVO','TRANSFERENCIA'].includes(String(r.metodo))&&boton('Solicitar reversión',async()=>{const motivo=window.prompt('Motivo de reversión. Otro usuario deberá autorizarla.');if(!motivo)throw new Error('Indica el motivo');return apiClient.post(`/prestamos/cobranza/pagos/${r.id}/reversion`,{motivo});})}</>}/>
 {boton('Descargar estado de cuenta',async()=>{await descargarPdf(`/${seleccion}/estado-pdf`,`estado-prestamo-${seleccion}.pdf`);})}</>}
 <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);ejecutar(()=>apiClient.post(`${path}/${seleccion}/soportes`,f,{headers:{'Content-Type':undefined}}));}} className="flex flex-wrap gap-3"><input required name="archivo" type="file" accept="application/pdf,image/png,image/jpeg"/><button disabled={busy} className="rounded border p-2">Subir contrato o soporte (5 MB)</button></form><Tabla rows={rows(d.soportes)} cols={ [['nombre','Documento'],['fecha','Fecha']] } acciones={r=>boton('Descargar',async()=>{const blob=(await apiClient.get(`${path}/documentos/${r.id}`,{responseType:'blob'})).data;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=String(r.nombre);a.click();URL.revokeObjectURL(url);})}/>
 </section>}</>}
 {tab==='bancos'&&<Tabla rows={bancos.data??[]} cols={ [['fecha','Fecha'],['tipo','Movimiento'],['monto','Importe'],['origen','Origen'],['referencia_id','Referencia'],['cuenta','Banco / soporte']] }/>}
 {tab==='config'&&<><p className="text-sm">Estas son reglas internas configuradas por el administrador/contador, con vigencia. El sistema no determina una tasa legal automáticamente. La mora usa capital vencido, días efectivos y año de 365 días; no cobra interés sobre interés.</p><Formulario key={JSON.stringify(config.data)} busy={busy} titulo="Límites y reglas de aprobación" campos={[{nombre:'limiteAprobacion',titulo:'Hasta cuánto puede aprobar el operador ($)',tipo:'moneda',ayuda:'Por encima de este importe se exige permiso especial de aprobación. Cero exige ese permiso para cualquier préstamo.',valor:String(config.data?.limite_aprobacion??0)},{nombre:'tasaNominalAnualMax',titulo:'Tope de tasa nominal anual (%)',ayuda:'Ejemplo de conversión: 2 % mensual equivale a 24 % nominal anual. Configura el tope autorizado para tu empresa.',tipo:'number',valor:String(config.data?.tasa_nominal_anual_max??0)},{nombre:'vigenteHasta',titulo:'Fecha hasta la que valen estas reglas',ayuda:'Al vencer, se bloquea la aprobación y el desembolso de nuevos préstamos.',tipo:'date',valor:String(config.data?.vigente_hasta??hoy()).slice(0,10)},{nombre:'moraNominalAnual',titulo:'Tasa anual por atraso (%)',ayuda:'Cero desactiva la mora. Se calcula por días sobre capital vencido; no sobre intereses.',tipo:'number',valor:String(config.data?.mora_nominal_anual??0)},{nombre:'graciaDias',titulo:'Días de espera antes de cobrar mora',ayuda:'Ejemplo: 3 permite tres días después del vencimiento antes de iniciar la mora.',tipo:'number',valor:String(config.data?.gracia_dias??0)},{nombre:'capitalizarRefinanciacion',titulo:'Permitir sumar intereses y mora al nuevo préstamo',ayuda:'Solo en refinanciación, con aceptación expresa del cliente. No ocurre automáticamente.',opciones:[{id:'false',nombre:'No'},{id:'true',nombre:'Sí'}],valor:String(config.data?.capitalizar_refinanciacion??false)}]} enviar={async r=>ejecutar(()=>apiClient.put(`${path}/config`,{limiteAprobacion:Number(r.limiteAprobacion),tasaNominalAnualMax:Number(r.tasaNominalAnualMax),vigenteHasta:r.vigenteHasta,moraNominalAnual:Number(r.moraNominalAnual),graciaDias:Number(r.graciaDias),capitalizarRefinanciacion:r.capitalizarRefinanciacion==='true'}))}/></>}
 { ['cobranza','rutas','control'].includes(tab)&&<CobranzaPrestamos tipo={tab} sucursal={sucursal} cajaId={caja?.id} contratos={lista.data??[]} busy={busy} ejecutar={ejecutar}/> }
 </div>;
}
