import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {useSearchParams} from 'react-router-dom';
import {apiClient} from '@/api/client';
import {useAuthStore} from '@/stores/authStore';
import {getApiErrorMessage} from '@/api/errors';
import {FiltrosReportes,useFiltrosReportes} from './FiltrosReportes';
import {DetalleReporte} from './DetalleReporte';
export function CentroReportes(){const [url,setUrl]=useSearchParams();const {f,cambiar}=useFiltrosReportes();const [tipo,setTipo]=useState(url.get('tipo')||'ventas');const auth=useAuthStore();const tipos=useQuery({queryKey:['reportes-catalogo',auth.usuarioId],queryFn:async()=>(await apiClient.get<{id:string;nombre:string}[]>('/reportes/vista/catalogo')).data});return <div className="space-y-4"><div className="rounded-xl border border-ink-100 bg-white p-4 shadow-card space-y-3"><label className="text-xs font-medium text-ink-600">Reporte<select aria-label="Reporte" className="input mt-1 max-w-lg" value={tipo} onChange={e=>{setTipo(e.target.value);cambiar({...f,estado:''});const p=new URLSearchParams(url);p.set('tipo',e.target.value);p.delete('estado');setUrl(p,{replace:true});}}>{tipos.data?.map(t=><option key={t.id} value={t.id}>{t.nombre}</option>)}</select></label><FiltrosReportes f={f} cambiar={cambiar} completo/><label className="text-xs font-medium text-ink-600">Estado o tipo<select aria-label="Estado del reporte" className="input mt-1 max-w-xs" value={f.estado} onChange={e=>cambiar({...f,estado:e.target.value})}><option value="">Todos</option>{({inventario:['BAJO','AGOTADO','NORMAL'],caja:['INGRESO','EGRESO'],cajas:['ABIERTA'],ventas:['COMPLETADA'],compras:['PENDIENTE','PAGADA'],cxp:['PENDIENTE','PARCIAL','VENCIDA'],cxc:['PENDIENTE','PARCIAL','VENCIDA'],recepciones:['ENVIADA','PARCIALMENTE_RECIBIDA'],clientes:['ACTIVO','INACTIVO'],proveedores:['ACTIVO','INACTIVO'],arqueos:['CERRADA'],citas:['PROGRAMADA','CONFIRMADA','EN_CURSO','COMPLETADA','CANCELADA','NO_ASISTIO'],ordenes:['RECIBIDA','EN_PROCESO','ESPERANDO_REPUESTOS','LISTA','ENTREGADA','CANCELADA'],prestamos:['SOLICITADO','ACTIVO','EN_MORA','PAGADO','REFINANCIADO','RENOVADO','CANCELADO'],restaurante:['ABIERTA','CERRADA','CANCELADA'],gastos:['EFECTIVO','TARJETA','TRANSFERENCIA'],kardex:['ENTRADA','SALIDA','AJUSTE_ENTRADA','AJUSTE_SALIDA']} as Record<string,string[]>)[tipo]?.map(e=><option key={e} value={e}>{e.toLowerCase().replaceAll('_',' ')}</option>)}</select></label><p className="text-xs text-ink-400">Los saldos y existencias son actuales. Cada reporte explica qué filtros aplica; no se muestran como movimientos del período.</p></div>{tipos.error?<p role="alert">{getApiErrorMessage(tipos.error,'No se pudieron cargar los reportes')}</p>:tipos.data&&<DetalleReporte tipo={tipo} f={f}/>}</div>}
