import {useState,useEffect} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {apiClient} from '@/api/client';
import {getApiErrorMessage} from '@/api/errors';
import {useAuthStore} from '@/stores/authStore';
import {puedeVerRuta} from '@/lib/permisos';
import {LoadingState} from '@/components/ui/States';
import {params,type Filtro} from './FiltrosReportes';
export type Vista={tipo:string;titulo:string;explicacion:string;fechaConsulta:string;filtros:Filtro;columnas:{clave:string;titulo:string;tipo:string}[];filas:Record<string,unknown>[];totales:Record<string,number>;ruta:string};
export const dinero=(n:unknown)=>Number(n??0).toLocaleString('es-CO',{style:'currency',currency:'COP',minimumFractionDigits:2,maximumFractionDigits:2});
export function texto(v:unknown,tipo:string){if(v==null)return '—';return tipo==='dinero'?dinero(v):tipo==='numero'?Number(v).toLocaleString('es-CO',{maximumFractionDigits:3}):String(v);}
export function csvVista(v:Vista,filas:Record<string,unknown>[],buscar:string){const celda=(x:unknown)=>'"'+String(x??'').replace(/^[=+@\t\r-]/,m=>"'"+m).replaceAll('"','""')+'"';const grid=[[v.titulo],['Desde',v.filtros.desde,'Hasta',v.filtros.hasta,'Sucursal',v.filtros.sucursalId??'Todas','Empleado',v.filtros.usuarioId??'Todos','Estado',v.filtros.estado??'Todos'],['Consultado',v.fechaConsulta,'Búsqueda',buscar],['Explicación',v.explicacion],[],v.columnas.map(c=>c.titulo),...filas.map(r=>v.columnas.map(c=>texto(r[c.clave],c.tipo)))];return '\uFEFF'+grid.map(a=>a.map(celda).join(';')).join('\r\n');}
export function rutaAccion(v:Vista,r:Record<string,unknown>,f:Filtro){const p=new URLSearchParams({origen:'reporte',referencia:String(r.orden_id??r.producto_id??r.id),desde:f.desde,hasta:f.hasta});if(f.sucursalId)p.set('sucursalId',f.sucursalId);if(v.tipo==='recepciones')p.set('tab','ordenes');if(v.tipo==='compras'||v.tipo==='cxp'){p.set('tab','facturas');if(r.proveedor_id)p.set('proveedorId',String(r.proveedor_id));}if(v.tipo==='cxc'){p.set('tab','cuentas');if(r.cliente_id)p.set('clienteId',String(r.cliente_id));}if(v.tipo==='clientes')p.set('tab','clientes');if(v.tipo==='proveedores')p.set('tab','proveedores');if(['caja','cajas','arqueos'].includes(v.tipo))p.set('tab','documentos');if(v.tipo==='citas')p.set('tab','citas');if(v.tipo==='ordenes')p.set('tab','ordenes');return `${v.ruta}?${p}`;}
export function DetalleReporte({tipo,f,onData}:{tipo:string;f:Filtro;onData?:(v:Vista)=>void}){const [buscar,setBuscar]=useState(''),[pagina,setPagina]=useState(0);const auth=useAuthStore();const q=useQuery({queryKey:['reporte-vista',tipo,f],queryFn:async()=>(await apiClient.get<Vista>(`/reportes/vista/${tipo}`,{params:params(f)})).data,enabled:!!f.desde&&!!f.hasta&&f.desde<=f.hasta,retry:false});useEffect(()=>{setPagina(0);setBuscar('');},[tipo,JSON.stringify(f)]);useEffect(()=>{if(q.data)onData?.(q.data);},[q.data]);const v=q.data;const filas=(v?.filas??[]).filter(r=>(v?.columnas??[]).some(c=>texto(r[c.clave],c.tipo).toLocaleLowerCase().includes(buscar.toLocaleLowerCase())));const puedeAbrir=auth.esAdministradorTotal||auth.esSuperadmin||(v?.ruta==='/caja'?auth.permisos.some(p=>p.startsWith('CAJA_')):v&&puedeVerRuta(auth.permisos,v.ruta));
 function descargar(){if(!v)return;const blob=new Blob([csvVista(v,filas,buscar)],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`sicom-${tipo}-${f.desde}-${f.hasta}.csv`;a.click();URL.revokeObjectURL(url);}
 if(q.isLoading)return <LoadingState/>;if(q.error)return <p role="alert" className="rounded bg-red-50 p-3 text-sm text-red-700">{getApiErrorMessage(q.error,'No se pudo consultar el reporte. No se muestran totales como cero.')}</p>;if(!v)return <p className="text-sm text-ink-400">Selecciona un período válido.</p>;
 return <section className="space-y-3"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">{v.titulo}</h2><button className="rounded border px-3 py-2 text-xs" onClick={descargar}>Descargar lo que estoy viendo (CSV / Excel)</button></div><details className="rounded border bg-ink-50 p-3 text-sm" open><summary className="cursor-pointer font-medium">¿Cómo se calcula?</summary><p className="mt-2 text-ink-600">{v.explicacion}</p><p className="mt-1 text-xs text-ink-400">Consultado: {v.fechaConsulta.replace('T',' ').slice(0,19)} · {f.desde} a {f.hasta}</p></details><div className="flex flex-wrap items-center gap-3"><input aria-label="Buscar en reporte" className="input max-w-md" placeholder="Buscar por nombre, documento, código o código de barras" value={buscar} onChange={e=>{setBuscar(e.target.value);setPagina(0);}}/><span className="text-xs text-ink-500">{filas.length.toLocaleString('es-CO')} registros con estos filtros</span></div><div className="flex flex-wrap gap-3 text-sm">{v.tipo==='caja'&&['INGRESO','EGRESO'].map(e=><span key={e} className="rounded border px-3 py-2">{e==='INGRESO'?'Entradas':'Salidas'}: <strong>{dinero(filas.filter(r=>r.estado===e).reduce((s,r)=>s+Number(r.monto),0))}</strong></span>)}{v.columnas.filter(c=>c.tipo==='dinero'&&c.clave!=='costo'&&v.tipo!=='caja').map(c=><span key={c.clave} className="rounded border px-3 py-2">{c.titulo}: <strong>{dinero(filas.reduce((s,r)=>s+Number(r[c.clave]??0),0))}</strong></span>)}</div><div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead><tr>{v.columnas.map(c=><th key={c.clave} className="whitespace-nowrap border-b p-3">{c.titulo}</th>)}{puedeAbrir&&<th className="p-3">Acción</th>}</tr></thead><tbody>{filas.slice(pagina*50,(pagina+1)*50).map((r,i)=><tr key={String(r.id??i)}>{v.columnas.map(c=><td key={c.clave} className="border-b p-3">{texto(r[c.clave],c.tipo)}</td>)}{puedeAbrir&&<td className="border-b p-3"><Link className="text-xs underline" to={rutaAccion(v,r,f)}>Ir al módulo · #{String(r.orden_id??r.producto_id??r.id)}</Link></td>}</tr>)}</tbody></table>{!filas.length&&<p className="p-4 text-sm text-ink-400">No hay registros con estos filtros.</p>}</div><div className="flex items-center justify-between text-xs"><button disabled={pagina===0} className="rounded border px-3 py-2 disabled:opacity-40" onClick={()=>setPagina(pagina-1)}>Anterior</button><span>Página {pagina+1} de {Math.max(1,Math.ceil(filas.length/50))}. La descarga incluye todas las filas filtradas.</span><button disabled={(pagina+1)*50>=filas.length} className="rounded border px-3 py-2 disabled:opacity-40" onClick={()=>setPagina(pagina+1)}>Siguiente</button></div></section>;
}
