import {useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {apiClient} from '@/api/client';
import {useAuthStore} from '@/stores/authStore';
export type Filtro={desde:string;hasta:string;sucursalId:string;usuarioId:string;estado:string};
export const hoy=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Bogota',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const inicial=():Filtro=>({desde:hoy().slice(0,7)+'-01',hasta:hoy(),sucursalId:'',usuarioId:'',estado:''});
export const params=(f:Filtro)=>({...f,sucursalId:f.sucursalId||undefined,usuarioId:f.usuarioId||undefined,estado:f.estado||undefined});
export function useFiltrosReportes(){const auth=useAuthStore();const key=`reportes-filtros:${auth.empresaId}:${auth.usuarioId}`;const [url,setUrl]=useSearchParams();const [f,setF]=useState<Filtro>(()=>{let base=inicial();try{base={...base,...JSON.parse(localStorage.getItem(key)||'{}')};}catch{}for(const k of Object.keys(base) as (keyof Filtro)[])if(url.has(k))base[k]=url.get(k)||'';return base;});function cambiar(n:Filtro){setF(n);localStorage.setItem(key,JSON.stringify(n));const p=new URLSearchParams(url);for(const k of Object.keys(n) as (keyof Filtro)[]){if(n[k])p.set(k,n[k]);else p.delete(k);}setUrl(p,{replace:true});}return {f,cambiar};}
export function FiltrosReportes({f,cambiar,completo=false}:{f:Filtro;cambiar:(f:Filtro)=>void;completo?:boolean}){const opciones=useQuery({queryKey:['reportes-opciones'],queryFn:async()=>(await apiClient.get<{sucursales:{id:number;nombre:string}[];empleados:{id:number;nombre:string}[]}>('/reportes/vista/opciones')).data});const label=(titulo:string,input:React.ReactNode)=><label className="text-xs font-medium text-ink-600"><span className="mb-1 block">{titulo}</span>{input}</label>;return <div className="flex flex-wrap items-end gap-3">{label('Desde',<input aria-label="Desde" className="input w-auto" type="date" value={f.desde} onChange={e=>cambiar({...f,desde:e.target.value})}/>)}{label('Hasta',<input aria-label="Hasta" className="input w-auto" type="date" value={f.hasta} onChange={e=>cambiar({...f,hasta:e.target.value})}/>)}{label('Sucursal',<select aria-label="Sucursal" className="input w-auto" value={f.sucursalId} onChange={e=>cambiar({...f,sucursalId:e.target.value})}><option value="">Todas las sucursales</option>{opciones.data?.sucursales.map(s=><option key={s.id} value={s.id}>{s.nombre}</option>)}</select>)}{completo&&label('Empleado',<select aria-label="Empleado" className="input w-auto" value={f.usuarioId} onChange={e=>cambiar({...f,usuarioId:e.target.value})}><option value="">Todos los empleados</option>{opciones.data?.empleados.map(s=><option key={s.id} value={s.id}>{s.nombre}</option>)}</select>)}<button className="rounded border px-3 py-2 text-xs" onClick={()=>cambiar({...f,desde:hoy(),hasta:hoy()})}>Hoy</button><button className="rounded border px-3 py-2 text-xs" onClick={()=>cambiar({...f,desde:hoy().slice(0,7)+'-01',hasta:hoy()})}>Este mes</button><button className="rounded border px-3 py-2 text-xs" onClick={()=>cambiar(inicial())}>Limpiar filtros</button>{(!f.desde||!f.hasta||f.desde>f.hasta)&&<p role="alert" className="text-xs text-red-700">Selecciona un rango de fechas válido.</p>}{opciones.error&&<p className="text-xs text-red-700">No se pudieron cargar las sucursales y empleados.</p>}</div>}
