import {usePermisosOperacion} from '@/hooks/usePermisosOperacion';
import {useEffect,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {apiClient} from '@/api/client';
import {getApiErrorMessage} from '@/api/errors';
import {useSucursales} from '@/hooks/useSucursales';
import {useUsuarios} from '@/hooks/useNucleo';
import {useProductos} from '@/hooks/useInventario';
import {useCombos} from '@/hooks/useCombos';
import {useCajaAbierta} from '@/hooks/usePos';
import {useCuentasContables} from '@/hooks/useContabilidad';
import type {ReactNode} from 'react';
type Row=Record<string,unknown>;
const path='/restaurante/operacion';
const dinero=(v:unknown)=>Number(v||0).toLocaleString('es-CO',{style:'currency',currency:'COP'});
function Tabla({rows,columns,actions}:{rows:Row[];columns:[string,string][];actions?:(r:Row)=>ReactNode}){return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{columns.map(([k,t])=><th className="border-b p-2" key={k}>{t}</th>)}{actions&&<th className="p-2">Acciones</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={String(r.id??i)}>{columns.map(([k])=><td className="border-b p-2" key={k}>{r[k]==null?'—':String(r[k])}</td>)}{actions&&<td className="border-b p-2">{actions(r)}</td>}</tr>)}</tbody></table>{!rows.length&&<p className="py-4 text-ink-400">No hay registros.</p>}</div>;}
function useDatos(tipo:string,enabled=true){return useQuery({queryKey:['rest-operacion',tipo],queryFn:async()=>(await apiClient.get<Row[]>(`${path}/${tipo}`)).data,enabled});}
export function OperacionRestaurante(){
 const permisos=usePermisosOperacion('RESTAURANTE'); const visible=(k:string)=>k==='turnos'||(permisos.empresa&&(k==='config'?permisos.administrar:k==='reportes'?permisos.reportes&&permisos.costos:k==='recetas'?permisos.costos:permisos.administrar));
 const [tab,setTab]=useState('turnos'),[sucursal,setSucursal]=useState(''),[error,setError]=useState(''),[mensaje,setMensaje]=useState(''),[busy,setBusy]=useState(false);
 const {data:sucursales}=useSucursales(),{data:usuarios}=useUsuarios(),{data:productos}=useProductos(),{data:combos}=useCombos();
 const sid=sucursal||String(sucursales?.[0]?.id||'');const {data:caja}=useCajaAbierta(sid?Number(sid):null);const client=useQueryClient();
 const turnos=useDatos('turnos',tab==='turnos'),propinas=useDatos('propinas',tab==='propinas'),repartos=useDatos('repartos',tab==='propinas'),mermas=useDatos('mermas',tab==='mermas'),recetas=useDatos('recetas',tab==='recetas'),plataformas=useDatos('plataformas',tab==='plataformas'),bancos=useDatos('bancos',tab==='bancos');
 const disponibilidad=useQuery({queryKey:['rest-operacion','disponibilidad',sid],queryFn:async()=>(await apiClient.get<Row[]>(`${path}/disponibilidad`,{params:{sucursalId:sid}})).data,enabled:!!sid&&tab==='recetas',refetchInterval:15000});
 const [desde,setDesde]=useState(()=>new Date().toISOString().slice(0,10)),[hasta,setHasta]=useState(()=>new Date().toISOString().slice(0,10));
 const reportes=useQuery({queryKey:['rest-operacion','reportes',desde,hasta],queryFn:async()=>(await apiClient.get<Record<string,Row[]>>(`${path}/reportes`,{params:{desde,hasta}})).data,enabled:tab==='reportes'});
 const [nombreTurno,setNombreTurno]=useState(''),[observaciones,setObservaciones]=useState('');
 const [producto,setProducto]=useState(''),[cantidad,setCantidad]=useState(''),[motivo,setMotivo]=useState(''),[claveMerma,setClaveMerma]=useState(()=>crypto.randomUUID());
 const [propina,setPropina]=useState(''),[empleado,setEmpleado]=useState(''),[monto,setMonto]=useState('');
 const [combo,setCombo]=useState(''),[porciones,setPorciones]=useState('1'),[ingredientes,setIngredientes]=useState<{productoId:string;cantidad:string}[]>([{productoId:'',cantidad:''}]);
 const [liquidacion,setLiquidacion]=useState(''),[recibido,setRecibido]=useState(''),[cuenta,setCuenta]=useState(''),[referencia,setReferencia]=useState('');
 async function ejecutar(fn:()=>Promise<unknown>,ok:string){if(busy)return;if(!permisos.operar){setError('Tu rol solo permite consultar.');return;}setBusy(true);setError('');setMensaje('');try{await fn();await Promise.all([client.invalidateQueries({queryKey:['rest-operacion']}),client.invalidateQueries({queryKey:['combos']}),client.invalidateQueries({queryKey:['productos']})]);setMensaje(ok);}catch(e){setError(getApiErrorMessage(e,'No se pudo completar la operación'));}finally{setBusy(false);}}
 const loadError=[reportes,turnos,propinas,repartos,mermas,recetas,plataformas,bancos,disponibilidad].find(q=>q.isError)?.error;
 const boton='rounded-lg bg-ink-800 px-3 py-2 text-sm text-white disabled:opacity-50';
 function selectSucursal(){return <label>Sucursal<select className="input" value={sid} onChange={e=>setSucursal(e.target.value)}>{sucursales?.map(s=><option value={s.id} key={s.id}>{s.nombre}</option>)}</select></label>;}
 const productoOptions=productos?.filter(p=>p.manejaInventario&&p.estado).map(p=><option key={p.id} value={p.id}>{p.nombre} · {p.unidadMedida}</option>);
 return <section className="mt-5 rounded-xl border bg-white p-4"><h2 className="text-lg font-semibold">Operación de restaurante</h2><div className="my-3 flex flex-wrap gap-2">{[['turnos','Turnos'],['propinas','Propinas'],['recetas','Recetas y disponibilidad'],['mermas','Mermas'],['plataformas','Plataformas'],['bancos','Recaudos bancarios'],['reportes','Preparación y margen'],['config','Límites y contabilidad']].filter(([k])=>visible(k)).map(([k,t])=><button key={k} className={tab===k?boton:'rounded-lg border px-3 py-2 text-sm'} onClick={()=>{setTab(k);setError('');setMensaje('');}}>{t}</button>)}</div>
 {(error||loadError)&&<p role="alert" className="mb-3 text-danger-600">{error||getApiErrorMessage(loadError,'Error al consultar registros')}</p>}{mensaje&&<p role="status" className="mb-3 text-success-600">{mensaje}</p>}
 {tab==='config'&&<Configuracion ejecutar={ejecutar} busy={busy}/>}
 {tab==='turnos'&&<><div className="grid gap-3 sm:grid-cols-3">{selectSucursal()}<label>Nombre del turno<input className="input" maxLength={100} value={nombreTurno} onChange={e=>setNombreTurno(e.target.value)}/></label><button disabled={busy||!permisos.operar} className={boton} onClick={()=>ejecutar(()=>apiClient.post(`${path}/turnos`,{sucursalId:Number(sid),nombre:nombreTurno}),'Turno abierto')}>Abrir mi turno</button></div><label className="my-3 block">Observaciones de cierre<input className="input" maxLength={500} value={observaciones} onChange={e=>setObservaciones(e.target.value)}/></label><p className="mb-3 text-sm">El cierre guarda ventas, abonos y movimientos de efectivo de cada empleado. El arqueo físico de caja se realiza en Caja.</p><Tabla rows={turnos.data??[]} columns={[["id","Turno"],["nombre","Nombre"],["empleado","Empleado"],["estado","Estado"],["inicio","Inicio"],["fin","Fin"]]} actions={r=>r.estado==='ABIERTO'?<button disabled={busy||!permisos.operar} onClick={()=>{if(window.confirm('Cerrar este turno y guardar su resumen?'))ejecutar(()=>apiClient.post(`${path}/turnos/${r.id}/cerrar`,{observaciones}),'Turno cerrado');}}>Cerrar</button>:<button onClick={()=>{const blob=new Blob([typeof r.resumen==='string'?r.resumen:JSON.stringify(r.resumen,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`turno-${r.id}.json`;a.click();URL.revokeObjectURL(url);}}>Descargar resumen</button>}/></>}
 {tab==='mermas'&&<><div className="grid gap-3 sm:grid-cols-2">{selectSucursal()}<label>Ingrediente<select className="input" value={producto} onChange={e=>setProducto(e.target.value)}><option value="">Selecciona</option>{productoOptions}</select></label><label>Cantidad en unidad base<input className="input" type="number" min="0.01" step="0.01" value={cantidad} onChange={e=>setCantidad(e.target.value)}/></label><label>Motivo<input className="input" maxLength={500} value={motivo} onChange={e=>setMotivo(e.target.value)}/></label></div><button className={`${boton} my-3`} disabled={busy||!permisos.operar} onClick={()=>ejecutar(async()=>{await apiClient.post(`${path}/mermas`,{clave:claveMerma,sucursalId:Number(sid),productoId:Number(producto),cantidad:Number(cantidad),motivo});setClaveMerma(crypto.randomUUID());setCantidad('');setMotivo('');},'Merma descontada del inventario')}>Registrar merma</button><Tabla rows={mermas.data??[]} columns={[["id","Registro"],["producto","Ingrediente"],["cantidad","Cantidad"],["costo","Costo"],["motivo","Motivo"],["fecha","Fecha"]]}/></>}
 {tab==='propinas'&&<><p className="mb-3 text-sm">Primero asigna la propina; después registra su entrega al empleado desde una caja abierta de la sucursal original.</p><div className="grid gap-3 sm:grid-cols-3"><label>Propina<select className="input" value={propina} onChange={e=>setPropina(e.target.value)}><option value="">Selecciona</option>{propinas.data?.map(p=><option key={String(p.id)} value={String(p.id)}>#{String(p.id)} · mesa/cuenta {String(p.comanda_id)} · disponible {dinero(Number(p.monto)-Number(p.repartido))}</option>)}</select></label><label>Empleado<select className="input" value={empleado} onChange={e=>setEmpleado(e.target.value)}><option value="">Selecciona</option>{usuarios?.map(u=><option key={u.id} value={u.id}>{u.nombre}</option>)}</select></label><label>Importe<input className="input" type="number" step="0.01" min="0.01" value={monto} onChange={e=>setMonto(e.target.value)}/></label></div><button disabled={busy||!permisos.operar} className={`${boton} my-3`} onClick={()=>ejecutar(()=>apiClient.post(`${path}/propinas/repartir`,{propinaId:Number(propina),usuarioId:Number(empleado),monto:Number(monto)}),'Propina asignada')}>Asignar importe</button>{selectSucursal()}<Tabla rows={repartos.data??[]} columns={[["id","Reparto"],["propina_id","Propina"],["nombre","Empleado"],["monto","Importe"],["pagado_en","Pagado"]]} actions={r=>!r.pagado_en?<button disabled={busy||!caja} onClick={()=>{if(window.confirm(`Registrar entrega real de ${dinero(r.monto)} a ${r.nombre}?`))ejecutar(()=>apiClient.post(`${path}/repartos/${r.id}/pagar`,{cajaSesionId:caja?.id}),'Pago de propina registrado');}}>Registrar pago</button>:null}/></>}
 {tab==='recetas'&&<><p className="mb-3 text-sm">Registra cantidades para el lote completo y su rendimiento. El sistema guarda el consumo por porción y lo descuenta al facturar.</p><div className="grid gap-3 sm:grid-cols-2"><label>Plato<select className="input" value={combo} onChange={async e=>{setCombo(e.target.value);if(!e.target.value)return;try{const rs=(await apiClient.get<{producto_id:number;cantidad:number}[]>(`${path}/recetas/${e.target.value}`)).data;setPorciones('1');setIngredientes(rs.length?rs.map(i=>({productoId:String(i.producto_id),cantidad:String(i.cantidad)})):[{productoId:'',cantidad:''}]);}catch(e){setError(getApiErrorMessage(e,'No se pudo cargar receta'));}}}><option value="">Selecciona</option>{combos?.filter(c=>c.estado).map(c=><option value={c.id} key={c.id}>{c.nombre}</option>)}</select></label><label>Porciones obtenidas<input className="input" type="number" step="0.01" min="0.01" value={porciones} onChange={e=>setPorciones(e.target.value)}/></label></div>{ingredientes.map((i,idx)=><div key={idx} className="my-2 flex gap-2"><select aria-label="Ingrediente" className="input" value={i.productoId} onChange={e=>setIngredientes(prev=>prev.map((r,n)=>n===idx?{...r,productoId:e.target.value}:r))}><option value="">Ingrediente</option>{productoOptions}</select><input aria-label="Cantidad por lote" className="input" type="number" min="0.01" step="0.01" value={i.cantidad} onChange={e=>setIngredientes(prev=>prev.map((r,n)=>n===idx?{...r,cantidad:e.target.value}:r))}/><button onClick={()=>setIngredientes(prev=>prev.filter((_,n)=>n!==idx))}>Quitar</button></div>)}<button className="mr-3" onClick={()=>setIngredientes(prev=>[...prev,{productoId:'',cantidad:''}])}>Agregar ingrediente</button><button disabled={busy||!combo} className={boton} onClick={()=>ejecutar(()=>apiClient.put(`${path}/recetas`,{comboId:Number(combo),porciones:Number(porciones),ingredientes:ingredientes.map(i=>({productoId:Number(i.productoId),cantidad:Number(i.cantidad)}))}),'Receta guardada')}>Guardar receta</button><h3 className="my-3 font-semibold">Costo actual por receta</h3><Tabla rows={(recetas.data??[]).map(r=>({...r,margen:Number(r.precio_venta)-Number(r.costo_por_porcion)}))} columns={[["nombre","Plato"],["porciones","Rendimiento"],["precio_venta","Precio catálogo"],["costo_por_porcion","Costo por porción"],["margen","Diferencia precio / costo actual"]]}/><h3 className="my-3 font-semibold">Disponibilidad por ingredientes</h3>{selectSucursal()}<Tabla rows={disponibilidad.data??[]} columns={[["nombre","Plato"],["porciones_disponibles","Porciones disponibles"]]}/></>}
 {tab==='plataformas'&&<><p className="mb-3 text-sm">Los pedidos de plataforma se facturan a crédito al cliente configurado. La liquidación cancela esa cartera y separa el depósito neto de la comisión.</p><div className="grid gap-3 sm:grid-cols-2"><label>Liquidación<select className="input" value={liquidacion} onChange={e=>{setLiquidacion(e.target.value);const l=plataformas.data?.find(r=>String(r.id)===e.target.value);setRecibido(String(l?.neto??''));}}><option value="">Selecciona</option>{plataformas.data?.filter(l=>!l.liquidado_en).map(l=><option key={String(l.id)} value={String(l.id)}>#{String(l.id)} · {String(l.plataforma)} · neto {dinero(l.neto)}</option>)}</select></label><label>Depósito recibido<input className="input" type="number" min="0" step="0.01" value={recibido} onChange={e=>setRecibido(e.target.value)}/></label><label>Cuenta bancaria<input className="input" maxLength={150} value={cuenta} onChange={e=>setCuenta(e.target.value)}/></label><label>Referencia del depósito<input className="input" maxLength={150} value={referencia} onChange={e=>setReferencia(e.target.value)}/></label></div><button className={`${boton} my-3`} disabled={busy||!liquidacion} onClick={()=>ejecutar(()=>apiClient.post(`${path}/plataformas/${liquidacion}/liquidar`,{recibido:Number(recibido),cuenta,referencia}),'Plataforma liquidada')}>Registrar liquidación</button><Tabla rows={plataformas.data??[]} columns={[["id","Liquidación"],["plataforma","Plataforma"],["domicilio_id","Pedido"],["bruto","Venta"],["comision","Comisión"],["neto","Neto"],["liquidado_en","Liquidada"]]}/></>}
 {tab==='reportes'&&<><div className="mb-3 flex gap-3"><label>Desde<input className="input" type="date" value={desde} onChange={e=>setDesde(e.target.value)}/></label><label>Hasta<input className="input" type="date" value={hasta} onChange={e=>setHasta(e.target.value)}/></label></div><p className="mb-3 text-sm">El margen registra ingreso sin impuestos y costo real de ingredientes al facturar desde esta actualización. Las ventas anteriores conservan su historial; no se reconstruye su receta.</p><h3 className="my-3 font-semibold">Margen de ventas</h3><Tabla rows={reportes.data?.margen??[]} columns={[["articulo","Plato / producto"],["cantidad","Cantidad"],["ingreso_sin_impuestos","Ingreso neto"],["costo_real","Costo real"],["margen_bruto","Margen bruto"]]}/><h3 className="my-3 font-semibold">Preparación por estación</h3><Tabla rows={reportes.data?.preparacion??[]} columns={[["plato","Plato"],["estacion","Estación"],["preparaciones","Preparaciones"],["minutos_preparacion","Minutos promedio"]]}/><h3 className="my-3 font-semibold">Ventas por mesero</h3><Tabla rows={reportes.data?.meseros??[]} columns={[["mesero","Mesero"],["cuentas","Cuentas"],["ventas","Ventas"]]}/><h3 className="my-3 font-semibold">Ventas por horario</h3><Tabla rows={reportes.data?.horas??[]} columns={[["hora","Hora"],["cuentas","Pedidos"],["ventas","Ventas"]]}/></>}
 {tab==='bancos'&&<Tabla rows={bancos.data??[]} columns={[["fecha","Fecha"],["tipo","Tipo"],["monto","Importe"],["cuenta","Cuenta / referencia"],["origen","Origen"],["referencia_id","Registro"]]}/>}
 </section>;
}
function Configuracion({ejecutar,busy}:{ejecutar:(fn:()=>Promise<unknown>,ok:string)=>Promise<void>;busy:boolean}){
 const {data,error}=useQuery({queryKey:['rest-operacion','config'],queryFn:async()=>(await apiClient.get<Row>(`${path}/config`)).data});
 const cuentas=useCuentasContables();const [limite,setLimite]=useState('0'),[anticipos,setAnticipos]=useState(''),[propinas,setPropinas]=useState('');
 useEffect(()=>{if(data){setLimite(String(data.limite_descuento));setAnticipos(String(data.cuenta_anticipos??''));setPropinas(String(data.cuenta_propinas??''));}},[data]);
 const options=cuentas.data?.filter(c=>c.tipo==='PASIVO'&&c.estado&&c.permiteMovimientos).map(c=><option key={c.id} value={c.id}>{c.codigo} · {c.nombre}</option>);
 return <div className="space-y-3">{(error||cuentas.error)&&<p className="text-danger-600">{getApiErrorMessage(error||cuentas.error,'No se pudo consultar configuración')}</p>}<p>Los descuentos superiores al límite y las cortesías requieren aprobación y motivo. Si usas contabilidad, selecciona las cuentas de pasivo para anticipos y propinas.</p><label className="block">Límite de descuento sin aprobación (%)<input className="input" type="number" min="0" max="100" step="0.01" value={limite} onChange={e=>setLimite(e.target.value)}/></label><label className="block">Cuenta de anticipos<select className="input" value={anticipos} onChange={e=>setAnticipos(e.target.value)}><option value="">Sin configurar</option>{options}</select></label><label className="block">Cuenta de propinas<select className="input" value={propinas} onChange={e=>setPropinas(e.target.value)}><option value="">Sin configurar</option>{options}</select></label><button disabled={busy} className="rounded bg-ink-800 px-3 py-2 text-white" onClick={()=>ejecutar(()=>apiClient.put(`${path}/config`,{limiteDescuento:Number(limite),cuentaAnticipos:anticipos?Number(anticipos):null,cuentaPropinas:propinas?Number(propinas):null}),'Configuración guardada')}>Guardar configuración</button></div>;
}
