import {useState,useEffect,useRef} from 'react';
import {useAuthStore} from '@/stores/authStore';
import {getApiErrorMessage} from '@/api/errors';
import {useGuia,coincide,type Modulo} from './guia';
type Progreso={modulo:string;paso:string;vistos:string[]};
export default function TutorialUso({inicialModulo,inicialPaso}:{inicialModulo?:string;inicialPaso?:string}){
 const a=useAuthStore(),q=useGuia();const [buscar,setBuscar]=useState(''),[progreso,setProgreso]=useState<Progreso>({modulo:inicialModulo??'inicio',paso:inicialPaso??'',vistos:[]}),[listo,setListo]=useState(false);const foco=useRef<HTMLButtonElement>(null);
 const key=`sicom-tutorial:${a.empresaId}:${a.usuarioId}:${q.data?.version}`;
 useEffect(()=>{if(!q.data)return;let p:Progreso={modulo:'inicio',paso:'',vistos:[]};try{const guardado=JSON.parse(localStorage.getItem(key)||'null');if(guardado&&Array.isArray(guardado.vistos)&&typeof guardado.modulo==='string'&&typeof guardado.paso==='string')p=guardado;}catch{}if(inicialModulo)p.modulo=inicialModulo;if(inicialPaso)p.paso=inicialPaso;setProgreso(p);setListo(true);},[key,inicialModulo,inicialPaso]);
 const modulos=q.data?.modulos??[],modulo=modulos.find(m=>m.id===progreso.modulo)??modulos[0],paso=modulo?.pasos.find(p=>p.id===progreso.paso)??modulo?.pasos[0],indice=modulo?.pasos.findIndex(p=>p.id===paso?.id)??0;
 function elegir(m:Modulo,id:string){const n={modulo:m.id,paso:id,vistos:Array.from(new Set([...progreso.vistos,id]))};setProgreso(n);try{localStorage.setItem(key,JSON.stringify(n));}catch{}}
 useEffect(()=>{foco.current?.focus({preventScroll:true});},[paso?.id]);
 if(q.isLoading||!listo&&!q.error)return <p className="p-4 text-sm">Cargando tutorial…</p>;
 if(q.error)return <p role="alert" className="rounded bg-red-50 p-3 text-sm text-red-700">{getApiErrorMessage(q.error,'No se pudo cargar el tutorial. Intenta abrirlo de nuevo.')}</p>;
 if(!modulo||!paso)return <p>No hay guías disponibles para tu perfil.</p>;
 const visibles=modulos.filter(m=>coincide(m.nombre+' '+m.pasos.map(p=>p.boton+' '+p.explicacion).join(' '),buscar));const total=modulos.reduce((n,m)=>n+m.pasos.length,0),vistos=modulos.flatMap(m=>m.pasos).filter(p=>progreso.vistos.includes(p.id)).length;
 return <div className="space-y-4"><div className="rounded-xl border bg-ink-50 p-4"><h2 className="font-semibold">Tutorial del sistema</h2><p className="mt-1 text-sm text-ink-600">Pantalla de práctica con ejemplos. Los botones solo muestran explicaciones: no guardan, cobran, anulan ni cambian datos del negocio.</p><div className="mt-2 flex flex-wrap items-center gap-3 text-xs"><span>{vistos} de {total} pasos consultados en este navegador</span><button className="underline" onClick={()=>{setProgreso({modulo:'inicio',paso:'',vistos:[]});try{localStorage.removeItem(key);}catch{}}}>Reiniciar tutorial</button></div></div>
 <div className="grid gap-4 lg:grid-cols-[220px_minmax(0,1fr)]"><aside className="rounded-xl border bg-white p-3"><label className="text-xs font-medium">Buscar módulo o acción<input aria-label="Buscar módulo del tutorial" className="input mt-1" value={buscar} onChange={e=>setBuscar(e.target.value)} placeholder="Cuota, cita, impuestos…"/></label><nav aria-label="Módulos del tutorial" className="mt-3 flex max-h-[45vh] flex-col gap-1 overflow-y-auto">{visibles.map(m=><button key={m.id} aria-current={m.id===modulo.id?'step':undefined} className={`rounded-lg px-3 py-2 text-left text-sm ${m.id===modulo.id?'bg-ink-800 text-white':'hover:bg-ink-50'}`} onClick={()=>elegir(m,m.pasos[0].id)}>{m.nombre}<span className="ml-1 text-xs opacity-60">({m.pasos.length})</span></button>)}{!visibles.length&&<p className="text-sm">No hay una guía que coincida con esa búsqueda y tus permisos.</p>}</nav></aside>
 <div className="min-w-0 space-y-4"><div className="rounded-xl border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">{modulo.nombre}</h3><span className="rounded bg-amber-50 px-2 py-1 text-xs text-amber-800">Ejemplo · sin operaciones reales</span></div><p className="mt-1 text-xs text-ink-500">Selecciona un botón de muestra para saber para qué sirve.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{modulo.pasos.map((p,i)=><button ref={p.id===paso.id?foco:undefined} key={p.id} data-tutorial-target={p.id} aria-describedby={p.id===paso.id?'explicacion-tutorial':undefined} aria-pressed={p.id===paso.id} className={`rounded-xl border p-4 text-left transition-colors ${p.id===paso.id?'border-sicom-green bg-sicom-green/10 ring-2 ring-sicom-green':'border-ink-100 bg-ink-50 hover:border-ink-300'}`} onClick={()=>elegir(modulo,p.id)}><span className="mb-2 block text-xs text-ink-500">{i+1} · {p.seccion}</span><strong className="text-sm">{p.boton}</strong>{progreso.vistos.includes(p.id)&&<span className="ml-2 text-xs">✓ Consultado</span>}</button>)}</div></div>
 <div id="explicacion-tutorial" aria-live="polite" className="rounded-xl border border-sicom-green bg-white p-4"><p className="text-xs font-medium text-sicom-green">Botón señalado · paso {indice+1} de {modulo.pasos.length}</p><h3 className="mt-1 font-semibold">{paso.titulo}</h3><p className="mt-2 whitespace-pre-line text-sm leading-relaxed text-ink-600">{paso.explicacion}</p><p className="mt-3 text-xs text-ink-400">Cuando salgas del tutorial, podrás usar la pantalla real con tus permisos habituales.</p></div>
 <div className="flex flex-wrap justify-between gap-2"><button disabled={indice<=0} className="rounded border px-4 py-2 text-sm disabled:opacity-40" onClick={()=>elegir(modulo,modulo.pasos[indice-1].id)}>Anterior</button><button className="rounded border px-4 py-2 text-sm" onClick={()=>elegir(modulo,modulo.pasos[0].id)}>Volver al primer paso</button><button className="rounded bg-ink-800 px-4 py-2 text-sm text-white" onClick={()=>{if(indice<modulo.pasos.length-1)elegir(modulo,modulo.pasos[indice+1].id);else {const n=modulos.indexOf(modulo);if(n<modulos.length-1)elegir(modulos[n+1],modulos[n+1].pasos[0].id);else elegir(modulo,paso.id);}}}>{indice<modulo.pasos.length-1?'Siguiente':modulos.indexOf(modulo)<modulos.length-1?'Siguiente módulo':'Marcar último paso consultado'}</button></div>
 </div></div></div>;
}
export function TutorialGlobal(){const [inicio,setInicio]=useState<{modulo?:string;paso?:string}|null>(null),dialogo=useRef<HTMLDivElement>(null),anterior=useRef<HTMLElement|null>(null);
 useEffect(()=>{const abrir=(e:Event)=>{anterior.current=document.activeElement as HTMLElement;setInicio((e as CustomEvent).detail??{});};window.addEventListener('sicom-abrir-tutorial',abrir);return()=>window.removeEventListener('sicom-abrir-tutorial',abrir);},[]);
 function cerrar(){setInicio(null);anterior.current?.focus();}
 useEffect(()=>{if(!inicio)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';const tecla=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();cerrar();}if(e.key==='Tab'){const elementos=Array.from(dialogo.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea,a[href]')??[]);const first=elementos[0],last=elementos[elementos.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};window.addEventListener('keydown',tecla);dialogo.current?.focus();return()=>{document.body.style.overflow=old;window.removeEventListener('keydown',tecla);};},[inicio]);
 if(!inicio)return null;return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-ink-900/60 p-2 sm:p-6"><div ref={dialogo} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="titulo-tutorial-global" className="max-h-[95vh] w-full max-w-5xl overflow-y-auto rounded-xl bg-white p-4 sm:p-6"><div className="mb-4 flex items-center justify-between"><h2 id="titulo-tutorial-global" className="font-semibold">Aprender a usar SICOM</h2><button className="rounded border px-3 py-2 text-sm" onClick={cerrar}>Cerrar tutorial</button></div><TutorialUso inicialModulo={inicio.modulo} inicialPaso={inicio.paso}/></div></div>;
}
