import {usePermisosOperacion} from '@/hooks/usePermisosOperacion';
import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {apiClient} from '@/api/client';
import {getApiErrorMessage} from '@/api/errors';
import {useSucursales} from '@/hooks/useSucursales';
import {useUsuarios} from '@/hooks/useNucleo';
import {useProductos} from '@/hooks/useInventario';
import {useCajaAbierta,useClientes} from '@/hooks/usePos';
import {useCuentasContables} from '@/hooks/useContabilidad';
import {useTiposServicio,useCitas,useCitasHistorial} from '@/hooks/useServicios';
import type {ReactNode,FormEvent} from 'react';
type Row=Record<string,unknown>;
type Campo={nombre:string;titulo:string;tipo?:string;opciones?:{id:number|string;nombre:string}[];opcional?:boolean;valor?:string};
const dinero=(n:unknown)=>Number(n||0).toLocaleString('es-CO',{style:'currency',currency:'COP'});
function Tabla({rows,cols,acciones}:{rows:Row[];cols:[string,string][];acciones?:(r:Row)=>ReactNode}){return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{cols.map(([k,t])=><th key={k} className="p-2 border-b">{t}</th>)}{acciones&&<th>Acciones</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={String(r.id??r.cotizacion_id??i)}>{cols.map(([k])=><td key={k} className="p-2 border-b">{String(r[k]??'—')}</td>)}{acciones&&<td className="p-2 border-b">{acciones(r)}</td>}</tr>)}</tbody></table>{!rows.length&&<p className="p-4 text-ink-400">No hay registros.</p>}</div>}
function Formulario({titulo,campos,enviar,busy}:{titulo:string;campos:Campo[];enviar:(r:Record<string,string>)=>Promise<void>;busy:boolean}){return <form className="rounded border p-4 space-y-3" onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=e.currentTarget;const d=Object.fromEntries(new FormData(f).entries()) as Record<string,string>;await enviar(d);}}><h3 className="font-semibold">{titulo}</h3><div className="grid gap-3 md:grid-cols-3">{campos.map(c=><label key={c.nombre} className="text-sm">{c.titulo}{c.opciones?<select name={c.nombre} required={!c.opcional} defaultValue={c.valor||''} className="block w-full rounded border p-2"><option value="">Seleccionar</option>{c.opciones.map(o=><option value={o.id} key={o.id}>{o.nombre}</option>)}</select>:<input name={c.nombre} type={c.tipo||'text'} required={!c.opcional} defaultValue={c.valor} min={c.tipo==='number'?'0':undefined} step={c.tipo==='number'?'0.01':undefined} className="block w-full rounded border p-2"/>}</label>)}</div><button disabled={busy} className="rounded bg-ink-800 px-4 py-2 text-white disabled:opacity-50">Guardar</button></form>}
export function OperacionServicios({base}:{base:string}){
 const permisos=usePermisosOperacion(base==='ordenes'?'SERVICIOS_ORDENES':'SERVICIOS_CITAS');const visible=(t:string)=>['cotizaciones','agenda'].includes(t)||(permisos.empresa&&(t==='config'||t==='comisiones'||t==='bancos'?permisos.administrar:true));
 const path=`/servicios/${base}/operacion`;const qc=useQueryClient();
 const [tab,setTab]=useState('cotizaciones'),[seleccion,setSeleccion]=useState<number|null>(null),[error,setError]=useState(''),[mensaje,setMensaje]=useState(''),[busy,setBusy]=useState(false),[sucursal,setSucursal]=useState(''),[clienteHistorial,setClienteHistorial]=useState('');
 const {data:sucursales}=useSucursales(),{data:usuarios}=useUsuarios(),{data:productos}=useProductos(),{data:clientes}=useClientes(),{data:cuentas}=useCuentasContables(),{data:tipos}=useTiposServicio(),{data:citas}=useCitas(),{data:historial}=useCitasHistorial();
 const {data:caja}=useCajaAbierta(sucursal?Number(sucursal):null);
 const key=['servicios-operacion',base];
 function datos(tipo:string,enabled=true){return useQuery({queryKey:[...key,tipo],queryFn:async()=>(await apiClient.get<Row[]>(`${path}/${tipo}`)).data,enabled});}
 const bancos=datos('bancos',tab==='bancos');const cotizaciones=datos('cotizaciones'),disponibilidad=datos('disponibilidad',tab==='agenda'),paquetes=datos('paquetes',tab==='paquetes'),seguimientos=datos('seguimientos',tab==='seguimiento'),recordatorios=datos('recordatorios',tab==='recordatorios'),comisiones=datos('comisiones',tab==='comisiones'),vinculados=datos('tipos',tab==='paquetes');
 const config=useQuery({queryKey:[...key,'config'],queryFn:async()=>(await apiClient.get<Row>(`${path}/config`)).data,enabled:tab==='config'});
 const expediente=useQuery({queryKey:[...key,'cliente',clienteHistorial],queryFn:async()=>(await apiClient.get<Row>(`${path}/clientes/${clienteHistorial}/historial`)).data,enabled:tab==='seguimiento'&&!!clienteHistorial});
 const detalle=useQuery({queryKey:[...key,'detalle',seleccion],queryFn:async()=>(await apiClient.get<Row>(`${path}/cotizaciones/${seleccion}`)).data,enabled:seleccion!=null});
 const c=detalle.data;const sid=sucursal;const servicios=(productos??[]).filter(p=>!p.manejaInventario&&p.estado);const materiales=(productos??[]).filter(p=>p.manejaInventario&&p.estado);
 const op=(a:{id:number;nombre:string}[]|undefined)=>a??[];
 const n=(v:string)=>v?Number(v):null;
 const clientesCampo:Campo={nombre:'clienteId',titulo:'Cliente',opciones:op(clientes)};
 const empleadoCampo:Campo={nombre:'empleadoId',titulo:'Empleado',opciones:op(usuarios),opcional:true};
 const productoCampo:Campo={nombre:'productoId',titulo:'Servicio',opciones:op(servicios)};
 const sucursalCampo:Campo={nombre:'sucursalId',titulo:'Sucursal',opciones:op(sucursales),valor:sid};
 const metodoCampo:Campo={nombre:'metodo',titulo:'Medio de pago',opciones:['EFECTIVO','TRANSFERENCIA','TARJETA'].map(v=>({id:v,nombre:v}))};
 const uuid=(tipo:string)=>{const k=`servicios-operacion:${base}:${seleccion}:${tipo}`;let id=sessionStorage.getItem(k);if(!id){id=crypto.randomUUID();sessionStorage.setItem(k,id);}return id;};
 const liberar=(tipo:string)=>sessionStorage.removeItem(`servicios-operacion:${base}:${seleccion}:${tipo}`);
 async function ejecutar(f:()=>Promise<unknown>,texto='Operación registrada'){if(busy)return;if(!permisos.operar){setError('Tu rol solo permite consultar.');return;}setBusy(true);setError('');setMensaje('');try{await f();await qc.invalidateQueries({queryKey:key});await qc.invalidateQueries({queryKey:['ordenes']});await qc.invalidateQueries({queryKey:['citas']});setMensaje(texto);}catch(e){setError(getApiErrorMessage(e,'No se pudo registrar la operación'));}finally{setBusy(false);}}
 const post=(url:string,r:unknown={})=>apiClient.post(`${path}/${url}`,r);
 function accion(t:string,f:()=>Promise<unknown>){return <button disabled={busy||!permisos.operar} className="m-1 rounded border px-2 py-1 disabled:opacity-50" onClick={()=>ejecutar(f)}>{t}</button>}
 const rows=(v:unknown)=>Array.isArray(v)?v as Row[]:[];
 return <div className="space-y-4"><h2 className="text-xl font-semibold">Operación de servicios</h2><p className="text-sm text-ink-500">Agenda → cotización aprobada → orden → entrega → factura y pago.</p><label className="block text-sm">Sucursal para caja<select value={sucursal} onChange={e=>setSucursal(e.target.value)} className="ml-3 rounded border p-2"><option value="">Seleccionar</option>{sucursales?.map(s=><option key={s.id} value={s.id}>{s.nombre}</option>)}</select><span className="ml-3">{caja?`Caja abierta #${caja.id}`:'Selecciona una sucursal con caja abierta para cobrar.'}</span></label>
 <div className="flex flex-wrap gap-2">{['cotizaciones','agenda','paquetes','seguimiento','recordatorios','comisiones','bancos','config'].filter(visible).map(t=><button key={t} className={`rounded border px-3 py-2 ${t===tab?'bg-ink-800 text-white':''}`} onClick={()=>setTab(t)}>{({cotizaciones:'Cotizaciones y cobros',agenda:'Disponibilidad y recurrencia',paquetes:'Bonos y sesiones',seguimiento:'Seguimiento y garantías',recordatorios:'Recordatorios',comisiones:'Comisiones',bancos:'Movimientos bancarios',config:'Configuración'} as Record<string,string>)[t]}</button>)}</div>
 {error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-700">{error}</p>}{mensaje&&<p role="status" className="rounded bg-green-50 p-3 text-green-700">{mensaje}</p>}
 {tab==='cotizaciones'&&<><Formulario busy={busy||!permisos.operar} titulo="Nueva cotización" campos={[sucursalCampo,clientesCampo,empleadoCampo,{nombre:'titulo',titulo:'Trabajo'},productoCampo,{nombre:'cantidad',titulo:'Cantidad de servicios',tipo:'number',valor:'1'},{nombre:'precio',titulo:'Precio unitario sin impuesto',tipo:'number'},{nombre:'garantiaDias',titulo:'Garantía en días',tipo:'number',valor:'0'},{nombre:'citaId',titulo:'Cita asociada',opcional:true,opciones:(citas??[]).map(x=>({id:x.id,nombre:`${x.fechaHora} · ${x.clienteNombre??''}`}))}]} enviar={async r=>ejecutar(()=>post('cotizaciones',{...r,sucursalId:n(r.sucursalId),clienteId:n(r.clienteId),empleadoId:n(r.empleadoId),citaId:n(r.citaId),garantiaDias:n(r.garantiaDias),lineas:[{productoId:n(r.productoId),cantidad:n(r.cantidad),precio:n(r.precio)}]}))}/>
 <Tabla rows={cotizaciones.data??[]} cols={ [['id','Número'],['titulo','Trabajo'],['cliente','Cliente'],['empleado','Empleado'],['estado','Estado'],['total','Total'],['abonado','Anticipos'],['venta_id','Venta']] } acciones={r=><button className="rounded border p-2" onClick={()=>{setSeleccion(Number(r.id));setSucursal(String(r.sucursal_id));}}>Abrir</button>}/>
 {seleccion&&c&&<section className="rounded border p-4 space-y-4"><h3 className="font-semibold">Cotización #{seleccion}: {String(c.titulo)}</h3><p>Total {dinero(c.total)} · Estado {String(c.estado)} · Orden {String(c.orden_id??'pendiente')} · Venta {String(c.venta_id??'pendiente')}</p>
 {c.estado==='BORRADOR'&&<>{accion('Aprobar',()=>post(`cotizaciones/${seleccion}/aprobar`,{acepta:true}))}{accion('Rechazar',()=>post(`cotizaciones/${seleccion}/aprobar`,{acepta:false}))}</>}
 {c.estado==='APROBADA'&&accion('Crear orden de trabajo',()=>post(`cotizaciones/${seleccion}/orden`))}
 {c.orden_id!=null&&c.venta_id==null&&<p className="text-sm">Estado de la orden: {String(c.estado_orden)}. Entregar no registra dinero; factura después para cobrar.</p>}
 {c.orden_id!=null&&c.venta_id==null&&!['ENTREGADA','CANCELADA'].includes(String(c.estado_orden))&&<div>{['EN_PROCESO','ESPERANDO_REPUESTOS','LISTA','ENTREGADA','CANCELADA'].map(e=><span key={e}>{accion(e,()=>post(`cotizaciones/${seleccion}/estado-orden`,{estado:e}))}</span>)}</div>}
 {c.venta_id==null&&['APROBADA','ORDENADA'].includes(String(c.estado))&&<Formulario busy={busy||!permisos.operar} titulo="Registrar anticipo" campos={[{nombre:'monto',titulo:'Importe',tipo:'number'},metodoCampo,{nombre:'referencia',titulo:'Referencia bancaria',opcional:true}]} enviar={async r=>ejecutar(async()=>{await post(`cotizaciones/${seleccion}/anticipos`,{clave:uuid('anticipo'),cajaId:caja?.id,monto:n(r.monto),metodo:r.metodo,referencia:r.referencia||null});liberar('anticipo');})}/>}
 <Tabla rows={rows(c.anticipos)} cols={ [['id','Anticipo'],['monto','Importe'],['metodo','Medio'],['revertido_en','Reintegro']] } acciones={r=>!r.revertido_en&&!c.venta_id&&accion('Reintegrar',async()=>{const motivo=window.prompt('Motivo del reintegro autorizado');if(!motivo)throw new Error('Indica el motivo');return post(`cotizaciones/${seleccion}/anticipos/${r.id}/revertir`,{cajaId:caja?.id,motivo});})}/>
 {c.orden_id!=null&&c.venta_id==null&&<Formulario busy={busy||!permisos.operar} titulo="Facturar después de entregar: cobra solo el saldo" campos={[{nombre:'monto',titulo:'Saldo recibido (0 si ya está pagado)',tipo:'number',valor:String(Math.max(0,Number(c.total)-rows(c.anticipos).filter(a=>!a.revertido_en).reduce((a,b)=>a+Number(b.monto),0)))},metodoCampo]} enviar={async r=>ejecutar(async()=>{await post(`cotizaciones/${seleccion}/facturar`,{clave:uuid('factura'),cajaId:caja?.id,pagos:Number(r.monto)>0?[{metodoPago:r.metodo,monto:Number(r.monto)}]:[]});liberar('factura');})}/>}
 {c.orden_id!=null&&c.venta_id==null&&<Formulario busy={busy||!permisos.operar} titulo="Material consumido" campos={[{nombre:'productoId',titulo:'Material',opciones:op(materiales)},{nombre:'cantidad',titulo:'Cantidad en unidad base',tipo:'number'},{nombre:'motivo',titulo:'Motivo'}]} enviar={async r=>ejecutar(async()=>{await post(`cotizaciones/${seleccion}/materiales`,{clave:uuid('material'),productoId:n(r.productoId),cantidad:n(r.cantidad),motivo:r.motivo});liberar('material');})}/>}
 <Tabla rows={rows(c.materiales)} cols={ [['producto','Material'],['cantidad','Consumo'],['costo','Costo real'],['motivo','Motivo']] }/>
 <form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);ejecutar(()=>apiClient.post(`${path}/cotizaciones/${seleccion}/soportes`,f,{headers:{'Content-Type':undefined}}));}}><select name="etapa" className="rounded border p-2"><option value="ANTES">Antes del trabajo</option><option value="DESPUES">Después del trabajo</option></select><input name="archivo" type="file" required accept="image/jpeg,image/png,application/pdf"/><button disabled={busy||!permisos.operar} className="rounded border p-2">Subir soporte (hasta 5 MB)</button></form>
 <Tabla rows={rows(c.soportes)} cols={ [['etapa','Etapa'],['nombre','Documento'],['fecha','Fecha']] } acciones={r=>accion('Descargar',async()=>{const b=(await apiClient.get(`${path}/soportes/${r.id}`,{responseType:'blob'})).data;const url=URL.createObjectURL(b);const a=document.createElement('a');a.href=url;a.download=String(r.nombre);a.click();URL.revokeObjectURL(url);})}/></section>}</>}
 {tab==='agenda'&&<><Formulario busy={busy||!permisos.operar} titulo="Disponibilidad del empleado" campos={[{...empleadoCampo,nombre:'usuarioId',opcional:false},sucursalCampo,{nombre:'dia',titulo:'Día',opciones:['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'].map((v,i)=>({id:i+1,nombre:v}))},{nombre:'desde',titulo:'Desde',tipo:'time'},{nombre:'hasta',titulo:'Hasta',tipo:'time'}]} enviar={async r=>ejecutar(()=>post('disponibilidad',{...r,usuarioId:n(r.usuarioId),sucursalId:n(r.sucursalId),dia:n(r.dia)}))}/><Tabla rows={disponibilidad.data??[]} cols={ [['empleado','Empleado'],['sucursal','Sucursal'],['dia','Día'],['desde','Desde'],['hasta','Hasta']] } acciones={r=>accion('Quitar',()=>apiClient.delete(`${path}/disponibilidad/${r.id}`))}/>
 <Formulario busy={busy||!permisos.operar} titulo="Programar servicio recurrente" campos={[sucursalCampo,clientesCampo,{...empleadoCampo,opcional:false},{nombre:'tipoServicioId',titulo:'Tipo de servicio',opciones:op(tipos)},{nombre:'fechaHora',titulo:'Primera cita',tipo:'datetime-local'},{nombre:'duracionMinutos',titulo:'Duración en minutos',tipo:'number',valor:'30'},{nombre:'veces',titulo:'Número de citas',tipo:'number',valor:'4'},{nombre:'cadaDias',titulo:'Repetir cada tantos días',tipo:'number',valor:'7'}]} enviar={async r=>ejecutar(()=>apiClient.post('/servicios/citas/recurrentes',{cita:{sucursalId:n(r.sucursalId),clienteId:n(r.clienteId),asignadoAUsuarioId:n(r.empleadoId),tipoServicioId:n(r.tipoServicioId),fechaHora:r.fechaHora,duracionMinutos:n(r.duracionMinutos)},veces:n(r.veces),cadaDias:n(r.cadaDias)}))}/><p className="text-sm">Crea todas las citas o ninguna si hay un conflicto. Sin horario configurado se permite cualquier hora, siempre sin superposición.</p></>}
 {tab==='paquetes'&&<><Formulario busy={busy||!permisos.operar} titulo="Vincular tipo de cita al producto facturable" campos={[{nombre:'tipoId',titulo:'Tipo de servicio',opciones:op(tipos)},productoCampo]} enviar={async r=>ejecutar(()=>apiClient.put(`${path}/tipos/${r.tipoId}/producto`,{productoId:n(r.productoId)}))}/><Tabla rows={vinculados.data??[]} cols={ [['nombre','Tipo'],['producto_id','Producto vinculado']] }/><Formulario busy={busy||!permisos.operar} titulo="Bono de sesiones comprado" campos={[clientesCampo,productoCampo,{nombre:'ventaId',titulo:'Venta pagada del bono',tipo:'number'},{nombre:'sesiones',titulo:'Sesiones',tipo:'number'},{nombre:'vence',titulo:'Vencimiento',tipo:'date'}]} enviar={async r=>ejecutar(()=>post('paquetes',{...r,clienteId:n(r.clienteId),productoId:n(r.productoId),ventaId:n(r.ventaId),sesiones:n(r.sesiones)}))}/><Tabla rows={paquetes.data??[]} cols={ [['id','Bono'],['cliente','Cliente'],['servicio','Servicio'],['sesiones','Sesiones'],['utilizadas','Usadas'],['vence','Vence'],['codigo','Código']] }/><Formulario busy={busy||!permisos.operar} titulo="Aplicar una sesión completada" campos={[{nombre:'paqueteId',titulo:'Bono',opciones:(paquetes.data??[]).map(p=>({id:String(p.id),nombre:`#${p.id} · ${p.cliente} · ${p.servicio}`}))},{nombre:'citaId',titulo:'Cita completada',opciones:(historial??[]).filter(c=>c.estado==='COMPLETADA').map(c=>({id:c.id,nombre:`#${c.id} · ${c.clienteNombre} · ${c.tipoServicioNombre}`}))}]} enviar={async r=>ejecutar(()=>post(`paquetes/${r.paqueteId}/sesiones`,{citaId:n(r.citaId)}))}/></>}
 {tab==='seguimiento'&&<><label className="block">Historial del cliente<select className="ml-2 rounded border p-2" value={clienteHistorial} onChange={e=>setClienteHistorial(e.target.value)}><option value="">Seleccionar</option>{clientes?.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label>{expediente.data&&<><Tabla rows={rows(expediente.data.citas)} cols={ [['fecha_hora','Cita'],['servicio','Servicio'],['estado','Estado'],['notas','Notas']] }/><Tabla rows={rows(expediente.data.trabajos)} cols={ [['titulo','Trabajo'],['total','Total'],['venta_id','Venta'],['garantia_hasta','Garantía']] }/></>}<Formulario busy={busy||!permisos.operar} titulo="Garantía o seguimiento del cliente" campos={[clientesCampo,{nombre:'cotizacionId',titulo:'Trabajo vinculado',opcional:true,opciones:(cotizaciones.data??[]).map(c=>({id:String(c.id),nombre:`#${c.id} · ${c.titulo}`}))},{nombre:'fecha',titulo:'Fecha de seguimiento',tipo:'datetime-local'},{nombre:'motivo',titulo:'Motivo / garantía'}]} enviar={async r=>ejecutar(()=>post('seguimientos',{...r,clienteId:n(r.clienteId),cotizacionId:n(r.cotizacionId)}))}/><Tabla rows={seguimientos.data??[]} cols={ [['cliente','Cliente'],['fecha','Fecha'],['motivo','Motivo'],['resultado','Resultado']] } acciones={r=>!r.resuelto_en&&accion('Resolver',async()=>{const resultado=window.prompt('Resultado del seguimiento');if(!resultado)throw new Error('Indica un resultado');return post(`seguimientos/${r.id}/resolver`,{resultado});})}/><Tabla rows={cotizaciones.data??[]} cols={ [['cliente','Cliente'],['titulo','Trabajo'],['venta_id','Venta'],['garantia_hasta','Garantía hasta']] }/></>}
 {tab==='recordatorios'&&<><Formulario busy={busy||!permisos.operar} titulo="Autorización de comunicaciones" campos={[clientesCampo,{nombre:'autorizado',titulo:'Autorización obtenida',opciones:[{id:'true',nombre:'Sí, autoriza'},{id:'false',nombre:'No, revocada'}]},{nombre:'canal',titulo:'Canal',opciones:[{id:'EMAIL',nombre:'Correo'},{id:'WHATSAPP',nombre:'WhatsApp'}]},{nombre:'destino',titulo:'Correo o teléfono internacional'}]} enviar={async r=>ejecutar(()=>apiClient.put(`${path}/consentimientos`,{...r,clienteId:n(r.clienteId),autorizado:r.autorizado==='true'}))}/><p className="text-sm">Bandeja de envío manual. Contacta al cliente por el canal autorizado y marca enviado después. No envía mensajes automáticamente.</p><Tabla rows={recordatorios.data??[]} cols={ [['id','Cita'],['cliente','Cliente'],['servicio','Servicio'],['fecha_hora','Fecha'],['canal','Canal'],['destino','Destino']] } acciones={r=>accion('Marcar enviado',()=>post(`recordatorios/${r.id}/enviado`))}/></>}
 {tab==='comisiones'&&<><p className="text-sm">Comisiones calculadas al facturar sobre el total con impuestos. El porcentaje se conserva en el importe generado; pagar produce una salida real de caja.</p>{comisiones.error&&<p className="text-red-700">{getApiErrorMessage(comisiones.error,'Sin acceso a comisiones')}</p>}<Tabla rows={comisiones.data??[]} cols={ [['cotizacion_id','Trabajo'],['empleado','Empleado'],['monto','Comisión'],['pagado_en','Pagada']] } acciones={r=>!r.pagado_en&&accion('Pagar en caja',()=>post(`comisiones/${r.cotizacion_id}/pagar`,{cajaId:caja?.id}))}/></>}
 {tab==='bancos'&&<Tabla rows={bancos.data??[]} cols={ [['fecha','Fecha'],['tipo','Movimiento'],['monto','Importe'],['origen','Origen'],['referencia_id','Referencia'],['cuenta','Referencia bancaria']] }/>}
 {tab==='config'&&<Formulario key={JSON.stringify(config.data)} busy={busy||!permisos.operar} titulo="Configuración de servicios" campos={[{nombre:'cuentaAnticipos',titulo:'Pasivo de anticipos',opcional:true,opciones:(cuentas??[]).filter(c=>c.tipo==='PASIVO'&&c.estado&&c.permiteMovimientos).map(c=>({id:c.id,nombre:`${c.codigo} · ${c.nombre}`})),valor:String(config.data?.cuenta_anticipos??'')},{nombre:'comisionPorcentaje',titulo:'Comisión del empleado (%)',tipo:'number',valor:String(config.data?.comision_porcentaje??0)},{nombre:'recordatorioHoras',titulo:'Mostrar recordatorios hasta (horas)',tipo:'number',valor:String(config.data?.recordatorio_horas??24)}]} enviar={async r=>ejecutar(()=>apiClient.put(`${path}/config`,{cuentaAnticipos:n(r.cuentaAnticipos),comisionPorcentaje:n(r.comisionPorcentaje),recordatorioHoras:n(r.recordatorioHoras)}))}/>}
 </div>;
}
