import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {apiClient} from '@/api/client';
import {getApiErrorMessage} from '@/api/errors';
import {useAuthStore} from '@/stores/authStore';
import {puedeVerRuta} from '@/lib/permisos';
import {Modal} from '@/components/ui/Modal';
import {hoy} from '@/features/reportes/FiltrosReportes';
import {dinero} from '@/features/reportes/DetalleReporte';
type Fila=Record<string,any>;
type Revision={desde:string;hasta:string;ingresos:number;costos:number;gastos:number;resultado:number;detalle:Fila[];pendientes:Fila[];descuadres:Fila[];bancos:Fila[];cajas:Fila[];cajasAbiertas:Fila[];asientosManuales:Fila[];puedeCerrar:boolean;explicacion:string};
type Periodo={id:number;anio:number;mes:number;estado:string;fechaCierre?:string};
const secciones=[['resumen','1. Resumen'],['pendientes','2. Operaciones pendientes'],['conciliar','3. Caja y bancos'],['cierre','4. Cierre e historial']] as const;
export default function RevisionCierre({initialMes}:{initialMes?:string}){
 const auth=useAuthStore(),qc=useQueryClient();const permiso=(p:string)=>auth.esAdministradorTotal||auth.esSuperadmin||auth.permisos.includes('CONTABILIDAD_'+p);
 const [mes,setMes]=useState(initialMes??hoy().slice(0,7)),[tab,setTab]=useState<string>('resumen'),[form,setForm]=useState<{tipo:string;r:Fila}|null>(null),[motivo,setMotivo]=useState(''),[asiento,setAsiento]=useState(''),[referencia,setReferencia]=useState(''),[importe,setImporte]=useState(''),[fecha,setFecha]=useState(hoy()),[confirmar,setConfirmar]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[aviso,setAviso]=useState('');
 const valido=/^\d{4}-\d{2}$/.test(mes);const [anio,m]=mes.split('-').map(Number);const desde=mes+'-01',hasta=valido?`${mes}-${new Date(anio,m,0).getDate()}`:'';
 const q=useQuery({queryKey:['contable-revision',auth.empresaId,mes],queryFn:async()=>(await apiClient.get<Revision>('/contabilidad/guiada/revision',{params:{desde,hasta}})).data,enabled:valido&&permiso('CONSULTAR'),retry:false});
 const periodos=useQuery({queryKey:['contable-periodos',auth.empresaId],queryFn:async()=>(await apiClient.get<Periodo[]>('/contabilidad/periodos')).data,enabled:permiso('CONSULTAR')});
 const historia=useQuery({queryKey:['contable-historial',auth.empresaId],queryFn:async()=>(await apiClient.get<Fila[]>('/contabilidad/guiada/historial')).data,enabled:permiso('CONSULTAR')});
 const v=q.data,p=periodos.data?.find(x=>x.anio===anio&&x.mes===m),cerrado=p?.estado==='CERRADO';
 function abrir(tipo:string,r:Fila){setForm({tipo,r});setMotivo('');setReferencia('');setAsiento('');setImporte('');setFecha(hoy());setConfirmar(false);setError('');setAviso('');}
 async function guardar(){if(!form||busy)return;setBusy(true);setError('');try{const {tipo,r}=form;
  if(tipo==='banco')await apiClient.post('/contabilidad/guiada/bancos',{movimientoId:r.id,fechaExtracto:fecha,referencia,monto:Number(importe)});
  if(tipo==='deshacer')await apiClient.post(`/contabilidad/guiada/bancos/${r.id}/deshacer`,{motivo});
  if(tipo==='caja')await apiClient.post(`/contabilidad/guiada/cajas/${r.id}/revisar`,{motivo});
  if(tipo==='enlace')await apiClient.post('/contabilidad/guiada/enlaces',{origen:r.origen,referenciaId:r.id,asientoId:Number(asiento),motivo});
  if(tipo==='cerrar'||tipo==='reabrir'){if(!confirmar)throw new Error('Confirma que revisaste el período');await apiClient.post(`/contabilidad/guiada/periodos/${r.id}/${tipo}`,{motivo});}
  if(tipo==='crear')await apiClient.post('/contabilidad/guiada/periodos',{anio,mes:m});
  setForm(null);setAviso('Cambio guardado. Revisión actualizada.');await qc.invalidateQueries({predicate:x=>String(x.queryKey[0]).startsWith('contable-')||String(x.queryKey[0]).includes('periodos')});
 }catch(e){setError(getApiErrorMessage(e,e instanceof Error?e.message:'No se pudo guardar'));}finally{setBusy(false);}}
 function descargar(){if(!v)return;let grupos:[string,Fila[]][]=tab==='resumen'?[['Resultado por cuenta',v.detalle]]:tab==='pendientes'?[['Operaciones sin asiento',v.pendientes],['Asientos descuadrados',v.descuadres]]:tab==='conciliar'?[['Bancos',v.bancos],['Cajas cerradas',v.cajas],['Cajas abiertas',v.cajasAbiertas]]:[['Historial',historia.data??[]]];const celda=(x:any)=>'"'+String(x??'').replace(/^[=+@\t\r-]/,s=>"'"+s).replaceAll('"','""')+'"';const filas:any[][]=[['SICOM · Revisión contable',mes],['Empresa',auth.empresaId],['Explicación',v.explicacion],['Ingresos',dinero(v.ingresos),'Costos',dinero(v.costos),'Gastos',dinero(v.gastos),'Resultado',dinero(v.resultado)]];for(const [titulo,rows]of grupos){filas.push([],[titulo]);const cols=Array.from(new Set(rows.flatMap(r=>Object.keys(r)))).filter(k=>k!=='ruta');filas.push(cols,...rows.map(r=>cols.map(c=>['monto','saldo','debito','credito','sistema','contado','diferencia'].includes(c)&&r[c]!=null?dinero(r[c]):r[c])));}const url=URL.createObjectURL(new Blob(['\uFEFF'+filas.map(r=>r.map(celda).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`sicom-contabilidad-${tab}-${mes}.csv`;a.click();URL.revokeObjectURL(url);}
 if(!permiso('CONSULTAR'))return <p className="text-sm text-ink-500">Tu rol no permite consultar la revisión contable.</p>;
 return <section className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3 rounded-xl border bg-white p-4"><label className="text-sm">Mes que vas a revisar<input aria-label="Mes que vas a revisar" type="month" className="input mt-1" value={mes} onChange={e=>{setMes(e.target.value);setAviso('');}}/></label><p className="text-xs text-ink-500">Empresa completa · {p?`${p.estado==='CERRADO'?'Cerrado':'Abierto'}${p.fechaCierre?' · '+p.fechaCierre.replace('T',' '):''}`:'Sin período creado'}<br/>El cierre incluye todas las sucursales.</p><button disabled={!v||q.isFetching} onClick={descargar} className="rounded border px-3 py-2 text-xs disabled:opacity-40">Descargar esta sección (CSV / Excel)</button></div>
 <nav className="flex flex-wrap gap-2">{secciones.map(([id,n])=><button key={id} onClick={()=>setTab(id)} className={`rounded-lg border px-3 py-2 text-sm ${tab===id?'bg-ink-800 text-white':'bg-white'}`}>{n}</button>)}</nav>
 {aviso&&<p role="status" className="rounded bg-green-50 p-3 text-sm">{aviso}</p>}{q.isLoading&&<p>Cargando revisión…</p>}{q.error&&<p role="alert" className="rounded bg-red-50 p-3 text-sm text-red-700">{getApiErrorMessage(q.error,'No se pudo revisar el período. No se muestran totales cero.')}</p>}
 {v&&<><details open className="rounded border bg-ink-50 p-3 text-sm"><summary>¿Qué estamos revisando?</summary><p className="mt-2">{v.explicacion}</p></details>
 {tab==='resumen'&&<><div className="grid gap-3 sm:grid-cols-4">{[['Ingresos',v.ingresos],['Costos',v.costos],['Gastos',v.gastos],['Resultado',v.resultado]].map(([n,x])=><div key={String(n)} className="rounded-xl border bg-white p-4"><p className="text-xs text-ink-500">{n}</p><strong>{dinero(x)}</strong></div>)}</div><Tabla cols={[['codigo','Código'],['nombre','Cuenta'],['tipo','Tipo'],['debito','Débitos'],['credito','Créditos'],['saldo','Saldo']]} rows={v.detalle}/><p className="text-xs text-ink-500">Resultado = ingresos − costos − gastos. Los impuestos y el capital de préstamos no se convierten en ingresos por recibirse en caja.</p></>}
 {tab==='pendientes'&&<><h3 className="font-semibold">Operaciones sin asiento vigente ({v.pendientes.length})</h3><p className="text-sm text-ink-500">Revisa el documento. Si necesita contabilizarse, crea su asiento en Libro Diario y vincúlalo aquí. El vínculo no crea una segunda venta ni mueve dinero. Un contador debe verificar las cuentas y los importes.</p><Tabla cols={[['origen','Operación'],['documento','Documento'],['fecha','Fecha'],['monto','Importe']]} rows={v.pendientes} accion={r=><div className="flex gap-2">{(auth.esAdministradorTotal||auth.esSuperadmin||puedeVerRuta(auth.permisos,r.ruta))&&<Link className="underline" to={`${r.ruta}?origen=revision&referencia=${r.id}`}>Ver documento #{r.id}</Link>}{permiso('VINCULAR')&&!cerrado&&<button className="underline" onClick={()=>abrir('enlace',r)}>Vincular asiento</button>}</div>}/><h3 className="font-semibold">Asientos descuadrados o sin líneas</h3><Tabla cols={[['numero','Asiento'],['fecha','Fecha'],['debito','Débitos'],['credito','Créditos']]} rows={v.descuadres}/></>}
 {tab==='conciliar'&&<><h3 className="font-semibold">Bancos</h3><p className="text-sm text-ink-500">Compara con el extracto de la cuenta mapeada como BANCOS. Ingreso positivo, salida negativa. Si el banco cobra una comisión, registra su asiento antes de conciliar. No se conecta a tu banco ni comprueba automáticamente el extracto.</p><Tabla cols={[['numero','Asiento'],['fecha','Fecha'],['concepto','Concepto'],['nombre','Cuenta'],['monto','Movimiento'],['referencia','Referencia extracto'],['estado','Estado']]} rows={v.bancos} accion={r=>permiso('CONCILIAR')&&!cerrado&&<button className="underline" onClick={()=>abrir(r.estado==='CONCILIADO'?'deshacer':'banco',r)}>{r.estado==='CONCILIADO'?'Deshacer con motivo':'Comparar con extracto'}</button>}/><h3 className="font-semibold">Cajas cerradas</h3><Tabla cols={[['id','Caja'],['sucursal','Sucursal'],['empleado','Responsable'],['sistema','Sistema'],['contado','Contado'],['diferencia','Diferencia'],['estado','Estado'],['motivo','Revisión']]} rows={v.cajas} accion={r=>permiso('CONCILIAR')&&!cerrado&&r.estado==='PENDIENTE'&&<button className="underline" onClick={()=>abrir('caja',r)}>Revisar diferencia</button>}/><p className="text-xs text-ink-500">Revisar una diferencia conserva el faltante o sobrante y su explicación; no ajusta efectivo ni contabilidad.</p><h3 className="font-semibold">Cajas aún abiertas</h3><Tabla cols={[['id','Caja'],['sucursal','Sucursal'],['fecha','Apertura']]} rows={v.cajasAbiertas} accion={()=> <Link to="/pos" className="underline">Ir a caja</Link>}/></>}
 {tab==='cierre'&&<><h3 className="font-semibold">Comprobaciones antes de cerrar</h3><ul className="space-y-2 text-sm">{[['Operaciones contabilizadas',v.pendientes.length],['Asientos cuadrados',v.descuadres.length],['Bancos conciliados',v.bancos.filter(r=>r.estado!=='CONCILIADO').length],['Cajas cerradas revisadas',v.cajas.filter(r=>r.estado!=='REVISADA').length],['Cajas sin sesiones abiertas anteriores al fin del mes',v.cajasAbiertas.length]].map(([n,c])=><li key={String(n)}>{Number(c)===0?'✓':'Pendiente:'} {n} · {c}</li>)}</ul><p className="text-sm text-ink-500">El mes debe haber terminado. El servidor vuelve a revisar al cerrar; no basta con esta pantalla. Un período cerrado bloquea crear, anular o modificar sus asientos y líneas.</p><div className="flex gap-3">{!p&&permiso('CERRAR')&&<button className="rounded bg-ink-800 px-4 py-2 text-white" onClick={()=>abrir('crear',{})}>Crear período para este mes</button>}{p&&!cerrado&&permiso('CERRAR')&&<button disabled={!v.puedeCerrar} className="rounded bg-ink-800 px-4 py-2 text-white disabled:opacity-40" onClick={()=>abrir('cerrar',p)}>Revisar y cerrar período</button>}{p&&cerrado&&permiso('REABRIR')&&<button className="rounded border px-4 py-2" onClick={()=>abrir('reabrir',p)}>Reabrir con motivo</button>}</div><h3 className="font-semibold">Historial de revisiones y cierres de la empresa</h3>{historia.error?<p role="alert">No se pudo cargar el historial.</p>:<Tabla cols={[['fecha','Fecha'],['usuario','Responsable'],['accion','Acción'],['referencia_id','Registro'],['motivo','Motivo']]} rows={historia.data??[]}/>}<p className="text-xs text-ink-500">Se muestran las últimas 500 acciones de toda la empresa; no solo el mes seleccionado.</p></>}
 </>}
 {form&&<Modal isOpen title={form.tipo==='banco'?'Comparar movimiento con el extracto':form.tipo==='enlace'?'Vincular asiento revisado':form.tipo==='caja'?'Explicar diferencia de caja':form.tipo==='crear'?'Crear período':form.tipo==='cerrar'?'Cerrar período':form.tipo==='reabrir'?'Reabrir período':'Deshacer conciliación'} onClose={()=>{if(!busy)setForm(null);}}><form className="space-y-3" onSubmit={e=>{e.preventDefault();void guardar();}}>
 {form.tipo==='banco'&&<><p>Movimiento del sistema: <strong>{dinero(form.r.monto)}</strong>. Escribe el importe y la referencia de la línea del extracto.</p><label className="block text-sm">Fecha en el extracto<input required type="date" className="input" value={fecha} onChange={e=>setFecha(e.target.value)}/></label><label className="block text-sm">Importe del extracto (negativo si es salida)<input aria-label="Importe del extracto" required type="number" step="0.01" className="input" value={importe} onChange={e=>setImporte(e.target.value)}/></label><label className="block text-sm">Referencia única: cuenta, extracto y línea<input required minLength={5} maxLength={200} className="input" value={referencia} onChange={e=>setReferencia(e.target.value)}/></label></>}
 {form.tipo==='enlace'&&<><p>{form.r.origen} #{form.r.id} · {dinero(form.r.monto)}. Verifica que el asiento corresponde a esta operación, incluidas cuentas e impuestos.</p><label className="block text-sm">Asiento manual del mes<select aria-label="Asiento manual del mes" required className="input" value={asiento} onChange={e=>setAsiento(e.target.value)}><option value="">Seleccionar</option>{v?.asientosManuales.map(r=><option key={r.id} value={r.id}>{r.numero} · {r.concepto}</option>)}</select></label>{!v?.asientosManuales.length&&<p>No hay asientos manuales disponibles. Créalo primero en Libro Diario.</p>}</>}
 {form.tipo==='caja'&&<p>Sistema {dinero(form.r.sistema)} · Contado {dinero(form.r.contado)} · Diferencia {dinero(form.r.diferencia)}. La diferencia permanecerá registrada.</p>}
 {form.tipo!=='banco'&&form.tipo!=='crear'&&<label className="block text-sm">Motivo y soporte de la revisión<textarea required minLength={5} maxLength={1000} className="input" value={motivo} onChange={e=>setMotivo(e.target.value)}/></label>}
 {['cerrar','reabrir'].includes(form.tipo)&&<label className="flex gap-2 text-sm"><input required type="checkbox" checked={confirmar} onChange={e=>setConfirmar(e.target.checked)}/>Confirmo la revisión del mes {mes} y autorizo {form.tipo==='cerrar'?'su cierre':'su reapertura'}.</label>}
 {form.tipo==='crear'&&<p>Se creará el mes {mes} abierto para revisarlo. No copia ni crea asientos.</p>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<button disabled={busy} type="submit" className="rounded bg-ink-800 px-4 py-2 text-white disabled:opacity-40">{busy?'Guardando…':'Confirmar y guardar'}</button>
 </form></Modal>}
 </section>;
}
function Tabla({cols,rows,accion}:{cols:[string,string][];rows:Fila[];accion?:(r:Fila)=>React.ReactNode}){return <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead><tr>{cols.map(([k,n])=><th key={k} className="whitespace-nowrap border-b p-3">{n}</th>)}{accion&&<th>Acción</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={String(r.id??r.codigo??i)+'-'+i}>{cols.map(([k])=><td key={k} className="border-b p-3">{r[k]==null?'—':['monto','saldo','debito','credito','sistema','contado','diferencia'].includes(k)?dinero(r[k]):String(r[k]).replace('T',' ')}</td>)}{accion&&<td className="border-b p-3 text-xs">{accion(r)}</td>}</tr>)}</tbody></table>{!rows.length&&<p className="p-4 text-sm text-ink-500">No hay registros en esta sección.</p>}</div>;}
